// GENERATED by scripts/fetch-rcl-sundays.mjs — do not edit by hand.
//
// The Sunday Eucharist readings (Revised Common Lectionary), keyed by date.
// Source: lectionarypage.net. Regenerate by running the script with the years
// you need; see its header for why this is fetched on a laptop and committed.
//
// Used to choose the week's Visio artwork: the RCL appoints the passages
// sacred art actually depicts, where the Daily Office's Sunday readings are
// semi-continuous and largely unpainted.

export type RclSunday = {
  /** The gospel appointed for the Sunday Eucharist. */
  gospel: string | null;
  /** Every OTHER New Testament reading — the epistle, and Acts where it stands
   *  in for the Old Testament through Eastertide. Both are matchable. */
  nt: string[];
  psalm: string | null;
  /** Old Testament readings, kept for completeness. After Pentecost the RCL
   *  offers two tracks and both appear here; the gospel and epistle above are
   *  shared between the tracks, which is why they are single values. */
  ot: string[];
};

export const RCL_SUNDAYS: Record<string, RclSunday> = {
  "2026-01-11": { gospel: "Matthew 3:13-17", nt: ["Acts 10:34-43"], psalm: "Psalm 29", ot: ["Isaiah 42:1-9"] },
  "2026-01-18": { gospel: "John 1:29-42", nt: ["1 Corinthians 1:1-9"], psalm: "Psalm 40:1-12", ot: ["Isaiah 49:1-7"] },
  "2026-01-25": { gospel: "Matthew 4:12-23", nt: ["1 Corinthians 1:10-18"], psalm: "Psalm 27:1, 5-13", ot: ["Isaiah 9:1-4"] },
  "2026-02-01": { gospel: "Matthew 5:1-12", nt: ["1 Corinthians 1:18-31"], psalm: "Psalm 15", ot: ["Micah 6:1-8"] },
  "2026-02-08": { gospel: "Matthew 5:13-20", nt: ["1 Corinthians 2:1-12, [13-16]"], psalm: "Psalm 112:1-9, (10)", ot: ["Isaiah 58:1-9a, [9b-12]"] },
  "2026-02-15": { gospel: "Matthew 17:1-9", nt: ["2 Peter 1:16-21"], psalm: "Psalm 2", ot: ["Exodus 24:12-18","Psalm 99"] },
  "2026-02-22": { gospel: "Matthew 4:1-11", nt: ["Romans 5:12-19"], psalm: "Psalm 32", ot: [] },
  "2026-03-01": { gospel: "John 3:1-17", nt: ["Romans 4:1-5, 13-17"], psalm: "Psalm 121", ot: ["Genesis 12:1-4a"] },
  "2026-03-08": { gospel: "John 4:5-42", nt: ["Romans 5:1-11"], psalm: "Psalm 95", ot: ["Exodus 17:1-7"] },
  "2026-03-15": { gospel: "John 9:1-41", nt: ["Ephesians 5:8-14"], psalm: "Psalm 23", ot: ["1 Samuel 16:1-13"] },
  "2026-03-22": { gospel: "John 11:1-45", nt: ["Romans 8:6-11"], psalm: "Psalm 130", ot: ["Ezekiel 37:1-14"] },
  "2026-03-29": { gospel: "Matthew 21:1-11", nt: ["Philippians 2:5-11"], psalm: "Psalm 118:1-2, 19-29", ot: ["Isaiah 50:4-9a","Matthew 26:14- 27:66","Matthew 27:11-54","Psalm 31:9-16"] },
  "2026-04-05": { gospel: "John 20:1-18", nt: ["Acts 10:34-43","Colossians 3:1-4","Acts 10:34-43"], psalm: "Psalm 118:1-2, 14-24", ot: ["Jeremiah 31:1-6","Matthew 28:1-10"] },
  "2026-04-12": { gospel: "John 20:19-31", nt: ["Acts 2:14a,22-32","1 Peter 1:3-9"], psalm: "Psalm 16", ot: [] },
  "2026-04-19": { gospel: "Luke 24:13-35", nt: ["Acts 2:14a,36-41","1 Peter 1:17-23"], psalm: "Psalm 116:1-3, 10-17", ot: [] },
  "2026-04-26": { gospel: "John 10:1-10", nt: ["Acts 2:42-47","1 Peter 2:19-25"], psalm: "Psalm 23", ot: [] },
  "2026-05-03": { gospel: "John 14:1-14", nt: ["Acts 7:55-60","1 Peter 2:2-10"], psalm: "Psalm 31:1-5, 15-16", ot: [] },
  "2026-05-10": { gospel: "John 14:15-21", nt: ["Acts 17:22-31","1 Peter 3:13-22"], psalm: "Psalm 66:7-18", ot: [] },
  "2026-05-17": { gospel: "John 17:1-11", nt: ["Acts 1:6-14"], psalm: "Psalm 68:1-10, 33-36", ot: [] },
  "2026-05-24": { gospel: "John 20:19-23", nt: ["Acts 2:1-21","1 Corinthians 12:3b-13","Acts 2:1-21"], psalm: "Psalm 104:25-35, 37", ot: ["Numbers 11:24-30","John 7:37-39"] },
  "2026-05-31": { gospel: "Matthew 28:16-20", nt: ["2 Corinthians 13:11-13"], psalm: "Psalm 8", ot: ["Genesis 1:1-2:4a","Canticle 13"] },
  "2026-06-07": { gospel: "Matthew 9:9-13, 18-26", nt: ["Romans 4:13-25","Romans 4:13-25"], psalm: "Psalm 33:1-12", ot: ["Track 1","Track 2","Genesis 12:1-9","Hosea 5:15-6:6","Psalm 50:7-15"] },
  "2026-06-14": { gospel: "Matthew 9:35-10:8(9-23)", nt: ["Romans 5:1-8","Romans 5:1-8"], psalm: "Psalm 116:1, 10-17", ot: ["Track 1","Track 2","Genesis 18:1-15, (21:1-7)","Exodus 19:2-8a","Psalm 100"] },
  "2026-06-21": { gospel: "Matthew 10:24-39", nt: ["Romans 6:1b-11","Romans 6:1b-11"], psalm: "Psalm 86:1-10, 16-17", ot: ["Track 1","Track 2","Genesis 21:8-21","Jeremiah 20:7-13","Psalm 69: 8-11, (12-17), 18-20"] },
  "2026-06-28": { gospel: "Matthew 10:40-42", nt: ["Romans 6:12-23","Romans 6:12-23"], psalm: "Psalm 13", ot: ["Track 1","Track 2","Genesis 22:1-14","Jeremiah 28:5-9","Psalm 89:1-4,15-18"] },
  "2026-07-05": { gospel: "Matthew 11:16-19, 25-30", nt: ["Romans 7:15-25a","Romans 7:15-25a"], psalm: "Psalm 45: 11-18", ot: ["Track 1","Track 2","Genesis 24:34-38, 42-49, 58-67","Zechariah 9:9-12","Psalm 145:8-15"] },
  "2026-07-12": { gospel: "Matthew 13:1-9,18-23", nt: ["Romans 8:1-11","Romans 8:1-11"], psalm: "Psalm 119:105-112", ot: ["Track 1","Track 2","Genesis 25:19-34","Isaiah 55:10-13","Psalm 65: (1-8), 9-14"] },
  "2026-07-19": { gospel: "Matthew 13:24-30,36-43", nt: ["Romans 8:12-25","Romans 8:12-25"], psalm: "Psalm 139: 1-11, 22-23", ot: ["Track 1","Track 2","Genesis 28:10-19a","Isaiah 44:6-8","Psalm 86:11-17"] },
  "2026-07-26": { gospel: "Matthew 13:31-33,44-52", nt: ["Romans 8:26-39","Romans 8:26-39"], psalm: "Psalm 105:1-11, 45b", ot: ["Track 1","Track 2","Genesis 29:15-28","Psalm 128","1 Kings 3:5-12","Psalm 119:129-136"] },
  "2026-08-02": { gospel: "Matthew 14:13-21", nt: ["Romans 9:1-5","Romans 9:1-5"], psalm: "Psalm 17:1-7,16", ot: ["Track 1","Track 2","Genesis 32:22-31","Isaiah 55:1-5","Psalm 145: 8-9, 15-22"] },
  "2026-08-09": { gospel: "Matthew 14:22-33", nt: ["Romans 10:5-15","Romans 10:5-15"], psalm: "Psalm 105:1-6, 16-22, 45b", ot: ["Track 1","Track 2","Genesis 37:1-4, 12-28","1 Kings 19:9-18","Psalm 85:8-13"] },
  "2026-08-16": { gospel: "Matthew 15: (10-20), 21-28", nt: ["Romans 11:1-2a, 29-32","Romans 11:1-2a, 29-32"], psalm: "Psalm 133", ot: ["Track 1","Track 2","Genesis 45:1-15","Isaiah 56:1,6-8","Psalm 67"] },
  "2026-08-23": { gospel: "Matthew 16:13-20", nt: ["Romans 12:1-8","Romans 12:1-8"], psalm: "Psalm 124", ot: ["Track 1","Track 2","Exodus 1:8-2:10","Isaiah 51:1-6","Psalm 138"] },
  "2026-08-30": { gospel: "Matthew 16:21-28", nt: ["Romans 12:9-21","Romans 12:9-21"], psalm: "Psalm 105:1-6, 23-26, 45c", ot: ["Track 1","Track 2","Exodus 3:1-15","Jeremiah 15:15-21","Psalm 26:1-8"] },
  "2026-09-06": { gospel: "Matthew 18:15-20", nt: ["Romans 13:8-14","Romans 13:8-14"], psalm: "Psalm 149", ot: ["Track 1","Track 2","Exodus 12:1-14","Ezekiel 33:7-11","Psalm 119:33-40"] },
  "2026-09-13": { gospel: "Matthew 18:21-35", nt: ["Romans 14:1-12","Romans 14:1-12"], psalm: "Psalm 114", ot: ["Track 1","Track 2","Exodus 14:19-31","Exodus 15:1b-11,20-21","Genesis 50:15-21","Psalm 103:(1-7), 8-13"] },
  "2026-09-20": { gospel: "Matthew 20:1-16", nt: ["Philippians 1:21-30","Philippians 1:21-30"], psalm: "Psalm 105:1-6, 37-45", ot: ["Track 1","Track 2","Exodus 16:2-15","Jonah 3:10-4:11","Psalm 145:1-8"] },
  "2026-09-27": { gospel: "Matthew 21:23-32", nt: ["Philippians 2:1-13","Philippians 2:1-13"], psalm: "Psalm 78:1-4, 12-16", ot: ["Track 1","Track 2","Exodus 17:1-7","Ezekiel 18:1-4,25-32","Psalm 25:1-8"] },
  "2026-10-04": { gospel: "Matthew 21:33-46", nt: ["Philippians 3:4b-14","Philippians 3:4b-14"], psalm: "Psalm 19", ot: ["Track 1","Track 2","Exodus 20:1-4, 7-9, 12-20","Isaiah 5:1-7","Psalm 80:7-14"] },
  "2026-10-11": { gospel: "Matthew 22:1-14", nt: ["Philippians 4:1-9","Philippians 4:1-9"], psalm: "Psalm 106:1-6, 19-23", ot: ["Track 1","Track 2","Exodus 32:1-14","Isaiah 25:1-9","Psalm 23"] },
  "2026-10-18": { gospel: "Matthew 22:15-22", nt: ["1 Thessalonians 1:1-10","1 Thessalonians 1:1-10"], psalm: "Psalm 99", ot: ["Track 1","Track 2","Exodus 33:12-23","Isaiah 45:1-7","Psalm 96:1-9, (10-13)"] },
  "2026-10-25": { gospel: "Matthew 22:34-46", nt: ["1 Thessalonians 2:1-8","1 Thessalonians 2:1-8"], psalm: "Psalm 90:1-6, 13-17", ot: ["Track 1","Track 2","Deuteronomy 34:1-12","Leviticus 19:1-2,15-18","Psalm 1"] },
  "2026-11-01": { gospel: "Matthew 5:1-12", nt: ["Revelation 7:9-17"], psalm: "Psalm 34:1-10, 22", ot: ["1 John 3:1-3"] },
  "2026-11-08": { gospel: "Matthew 25:1-13", nt: ["1 Thessalonians 4:13-18","1 Thessalonians 4:13-18"], psalm: "Psalm 78:1-7", ot: ["Track 1","Track 2","Joshua 24:1-3a, 14-25","Amos 5:18-24","Psalm 70"] },
  "2026-11-15": { gospel: "Matthew 25:14-30", nt: ["1 Thessalonians 5:1-11","1 Thessalonians 5:1-11"], psalm: "Psalm 123", ot: ["Track 1","Track 2","Judges 4:1-7","Zephaniah 1:7,12-18","Psalm 90:1-8, (9-11), 12"] },
  "2026-11-22": { gospel: "Matthew 25:31-46", nt: ["Ephesians 1:15-23","Ephesians 1:15-23"], psalm: "Psalm 100", ot: ["Track 1","Track 2","Ezekiel 34:11-16, 20-24","Ezekiel 34:11-16, 20-24","Psalm 95:1-7a"] },
  "2026-11-29": { gospel: "Mark 13:24-37", nt: ["1 Corinthians 1:3-9"], psalm: "Psalm 80:1-7, 16-18", ot: ["Isaiah 64:1-9"] },
  "2026-12-06": { gospel: "Mark 1:1-8", nt: ["2 Peter 3:8-15a"], psalm: "Psalm 85:1-2, 8-13", ot: ["Isaiah 40:1-11"] },
  "2026-12-13": { gospel: "John 1:6-8,19-28", nt: ["1 Thessalonians 5:16-24"], psalm: "Psalm 126", ot: ["Isaiah 61:1-4, 8-11","Canticle 15"] },
  "2026-12-20": { gospel: "Luke 1:26-38", nt: ["Romans 16:25-27"], psalm: "Psalm 89:1-4, 19-26", ot: ["2 Samuel 7:1-11, 16","Canticle 3 or","Canticle 15"] },
  "2027-01-10": { gospel: "Mark 1:4-11", nt: ["Acts 19:1-7"], psalm: "Psalm 29", ot: ["Genesis 1:1-5"] },
  "2027-01-17": { gospel: "John 1:43-51", nt: ["1 Corinthians 6:12-20"], psalm: "Psalm 139:1-5, 12-17", ot: ["1 Samuel 3:1-10(11-20)"] },
  "2027-01-24": { gospel: "Mark 1:14-20", nt: ["1 Corinthians 7:29-31"], psalm: "Psalm 62:6-14", ot: ["Jonah 3:1-5, 10"] },
  "2027-01-31": { gospel: "Mark 1:21-28", nt: ["1 Corinthians 8:1-13"], psalm: "Psalm 111", ot: ["Deuteronomy 18:15-20"] },
  "2027-02-07": { gospel: "Mark 9:2-9", nt: ["2 Corinthians 4:3-6"], psalm: "Psalm 50:1-6", ot: ["2 Kings 2:1-12"] },
  "2027-02-14": { gospel: "Mark 1:9-15", nt: ["1 Peter 3:18-22"], psalm: "Psalm 25:1-9", ot: ["Genesis 9:8-17"] },
  "2027-02-21": { gospel: "Mark 8:31-38", nt: ["Romans 4:13-25"], psalm: "Psalm 22:22-30", ot: ["Genesis 17:1-7, 15-16"] },
  "2027-02-28": { gospel: "John 2:13-22", nt: ["1 Corinthians 1:18-25"], psalm: "Psalm 19", ot: ["Exodus 20:1-17"] },
  "2027-03-07": { gospel: "John 3:14-21", nt: ["Ephesians 2:1-10"], psalm: "Psalm 107:1-3, 17-22", ot: ["Numbers 21:4-9"] },
  "2027-03-14": { gospel: "John 12:20-33", nt: ["Hebrews 5:5-10"], psalm: "Psalm 51:1-13", ot: ["Jeremiah 31:31-34","Psalm 119:9-16"] },
  "2027-03-21": { gospel: "Mark 11:1-11", nt: ["Philippians 2:5-11"], psalm: "Psalm 118:1-2, 19-29", ot: ["John 12:12-16","Isaiah 50:4-9a","Mark 14:1-15:47","Mark 15:1-39, [40-47]","Psalm 31:9-16"] },
  "2027-03-28": { gospel: "John 20:1-18", nt: ["Acts 10:34-43","1 Corinthians 15:1-11","Acts 10:34-43"], psalm: "Psalm 118:1-2, 14-24", ot: ["Isaiah 25:6-9","Mark 16:1-8"] },
  "2027-04-04": { gospel: "John 20:19-31", nt: ["Acts 4:32-35"], psalm: "Psalm 133", ot: ["1 John 1:1-2:2"] },
  "2027-04-11": { gospel: "Luke 24:36b-48", nt: ["Acts 3:12-19"], psalm: "Psalm 4", ot: ["1 John 3:1-7"] },
  "2027-04-18": { gospel: "John 10:11-18", nt: ["Acts 4:5-12"], psalm: "Psalm 23", ot: ["1 John 3:16-24"] },
  "2027-04-25": { gospel: "John 15:1-8", nt: ["Acts 8:26-40"], psalm: "Psalm 22:24-30", ot: ["1 John 4:7-21"] },
  "2027-05-02": { gospel: "John 15:9-17", nt: ["Acts 10:44-48"], psalm: "Psalm 98", ot: ["1 John 5:1-6"] },
  "2027-05-09": { gospel: "John 17:6-19", nt: ["Acts 1:15-17, 21-26"], psalm: "Psalm 1", ot: ["1 John 5:9-13"] },
  "2027-05-16": { gospel: null, nt: ["Acts 2:1-21","Romans 8:22-27","Acts 2:1-21"], psalm: "Psalm 104:25-35, 37", ot: ["Ezekiel 37:1-14"] },
  "2027-05-23": { gospel: "John 3:1-17", nt: ["Romans 8:12-17"], psalm: "Psalm 29", ot: ["Isaiah 6:1-8","Canticle 13"] },
  "2027-05-30": { gospel: "Mark 2:23-3:6", nt: ["2 Corinthians 4:5-12","2 Corinthians 4:5-12"], psalm: "Psalm 139:1-5, 12-17", ot: ["Track 1","Track 2","1 Samuel 3:1-10(11-20)","Deuteronomy 5:12-15","Psalm 81:1-10"] },
  "2027-06-06": { gospel: "Mark 3:20-35", nt: ["2 Corinthians 4:13-5:1","2 Corinthians 4:13-5:1"], psalm: "Psalm 138", ot: ["Track 1","Track 2","1 Samuel 8:4-11, (12-15), 16-20, (11:14-15)","Genesis 3:8-15","Psalm 130"] },
  "2027-06-13": { gospel: "Mark 4:26-34", nt: ["2 Corinthians 5:6-10,[11-13],14-17","2 Corinthians 5:6-10,[11-13],14-17"], psalm: "Psalm 20", ot: ["Track 1","Track 2","1 Samuel 15:34-16:13","Ezekiel 17:22-24","Psalm 92:1-4,11-14"] },
  "2027-06-20": { gospel: "Mark 4:35-41", nt: ["2 Corinthians 6:1-13","2 Corinthians 6:1-13"], psalm: "Psalm 9:9-20", ot: ["Track 1","Track 2","1 Samuel 17: (1a, 4-11, 19-23), 32-49","1 Samuel 17:57-18:5, 10-16","Psalm 133","Job 38:1-11","Psalm 107:1-3, 23-32"] },
  "2027-06-27": { gospel: "Mark 5:21-43", nt: ["2 Corinthians 8:7-15","2 Corinthians 8:7-15"], psalm: "Psalm 130", ot: ["Track 1","Track 2","2 Samuel 1:1, 17-27","Lamentations 3:21-33","Psalm 30"] },
  "2027-07-04": { gospel: "Mark 6:1-13", nt: ["2 Corinthians 12:2-10","2 Corinthians 12:2-10"], psalm: "Psalm 48", ot: ["Track 1","Track 2","2 Samuel 5:1-5, 9-10","Ezekiel 2:1-5","Psalm 123"] },
  "2027-07-11": { gospel: "Mark 6:14-29", nt: ["Ephesians 1:3-14","Ephesians 1:3-14"], psalm: "Psalm 24", ot: ["Track 1","Track 2","2 Samuel 6:1-5, 12b-19","Amos 7:7-15","Psalm 85:8-13"] },
  "2027-07-18": { gospel: "Mark 6:30-34, 53-56", nt: ["Ephesians 2:11-22","Ephesians 2:11-22"], psalm: "Psalm 89:20-37", ot: ["Track 1","Track 2","2 Samuel 7:1-14a","Jeremiah 23:1-6","Psalm 23"] },
  "2027-07-25": { gospel: "John 6:1-21", nt: ["Ephesians 3:14-21","Ephesians 3:14-21"], psalm: "Psalm 14", ot: ["Track 1","Track 2","2 Samuel 11:1-15","2 Kings 4:42-44","Psalm 145:10-19"] },
  "2027-08-01": { gospel: "John 6:24-35", nt: ["Ephesians 4:1-16","Ephesians 4:1-16"], psalm: "Psalm 51:1-13", ot: ["Track 1","Track 2","2 Samuel 11:26-12:13a","Exodus 16:2-4,9-15","Psalm 78:23-29"] },
  "2027-08-08": { gospel: "John 6:35, 41-51", nt: ["Ephesians 4:25-5:2","Ephesians 4:25-5:2"], psalm: "Psalm 130", ot: ["Track 1","Track 2","2 Samuel 18:5-9, 15, 31-33","1 Kings 19:4-8","Psalm 34:1-8"] },
  "2027-08-15": { gospel: "John 6:51-58", nt: ["Ephesians 5:15-20","Ephesians 5:15-20"], psalm: "Psalm 111", ot: ["Track 1","Track 2","Proverbs 9:1-6","Psalm 34:9-14"] },
  "2027-08-22": { gospel: "John 6:56-69", nt: ["Ephesians 6:10-20","Ephesians 6:10-20"], psalm: "Psalm 84", ot: ["Track 1","Track 2","1 Kings 8:[1, 6, 10-11], 22-30, 41-43","Joshua 24:1-2a,14-18","Psalm 34:15-22"] },
  "2027-08-29": { gospel: "Mark 7:1-8, 14-15, 21-23", nt: ["James 1:17-27","James 1:17-27"], psalm: "Psalm 45:1-2, 7-10", ot: ["Track 1","Track 2","Deuteronomy 4:1-2, 6-9","Psalm 15"] },
  "2027-09-05": { gospel: "Mark 7:24-37", nt: ["James 2:1-10, [11-13], 14-17","James 2:1-10, [11-13], 14-17"], psalm: "Psalm 125", ot: ["Track 1","Track 2","Proverbs 22:1-2, 8-9, 22-23","Isaiah 35:4-7a","Psalm 146"] },
  "2027-09-12": { gospel: "Mark 8:27-38", nt: ["James 3:1-12","James 3:1-12"], psalm: "Psalm 19", ot: ["Track 1","Track 2","Proverbs 1:20-33","Isaiah 50:4-9a","Psalm 116:1-8"] },
  "2027-09-19": { gospel: "Mark 9:30-37", nt: ["James 3:13-4:3, 7-8a","James 3:13-4:3, 7-8a"], psalm: "Psalm 1", ot: ["Track 1","Track 2","Proverbs 31:10-31","Jeremiah 11:18-20","Psalm 54"] },
  "2027-09-26": { gospel: "Mark 9:38-50", nt: ["James 5:13-20","James 5:13-20"], psalm: "Psalm 124", ot: ["Track 1","Track 2","Numbers 11:4-6,10-16,24-29","Psalm 19:7-14"] },
  "2027-10-03": { gospel: "Mark 10:2-16", nt: [], psalm: "Psalm 26", ot: ["Track 1","Track 2","Genesis 2:18-24","Psalm 8"] },
  "2027-10-10": { gospel: "Mark 10:17-31", nt: ["Hebrews 4:12-16","Hebrews 4:12-16"], psalm: "Psalm 22:1-15", ot: ["Track 1","Track 2","Job 23:1-9, 16-17","Amos 5:6-7,10-15","Psalm 90:12-17"] },
  "2027-10-17": { gospel: "Mark 10:35-45", nt: ["Hebrews 5:1-10","Hebrews 5:1-10"], psalm: "Psalm 104:1-9, 25, 37b", ot: ["Track 1","Track 2","Job 38:1-7, (34-41)","Isaiah 53:4-12","Psalm 91:9-16"] },
  "2027-10-24": { gospel: "Mark 10:46-52", nt: ["Hebrews 7:23-28","Hebrews 7:23-28"], psalm: "Psalm 34:1-8, (19-22)", ot: ["Track 1","Track 2","Job 42:1-6, 10-17","Jeremiah 31:7-9","Psalm 126"] },
  "2027-10-31": { gospel: "Mark 12:28-34", nt: ["Hebrews 9:11-14","Hebrews 9:11-14"], psalm: "Psalm 146", ot: ["Track 1","Track 2","Ruth 1:1-18","Deuteronomy 6:1-9","Psalm 119:1-8"] },
  "2027-11-07": { gospel: "Mark 12:38-44", nt: ["Hebrews 9:24-28","Hebrews 9:24-28"], psalm: "Psalm 127", ot: ["Track 1","Track 2","1 Kings 17:8-16","Psalm 146"] },
  "2027-11-14": { gospel: "Mark 13:1-8", nt: ["Hebrews 10:11-14 (15-18) 19-25","Hebrews 10:11-14 (15-18) 19-25"], psalm: "Psalm 16", ot: ["Track 1","Track 2","1 Samuel 1:4-20","1 Samuel 2:1-10","Daniel 12:1-3"] },
  "2027-11-21": { gospel: "John 18:33-37", nt: ["Revelation 1:4b-8","Revelation 1:4b-8"], psalm: "Psalm 132:1-13 (14-19)", ot: ["Track 1","Track 2","2 Samuel 23:1-7","Daniel 7:9-10, 13-14","Psalm 93"] },
  "2027-11-28": { gospel: "Luke 21:25-36", nt: ["1 Thessalonians 3:9-13"], psalm: "Psalm 25:1-9", ot: ["Jeremiah 33:14-16"] },
  "2027-12-05": { gospel: "Luke 3:1-6", nt: ["Philippians 1:3-11"], psalm: null, ot: ["Baruch 5:1-9","Malachi 3:1-4","Canticle 4 or 16"] },
  "2027-12-12": { gospel: "Luke 3:7-18", nt: ["Philippians 4:4-7"], psalm: null, ot: ["Zephaniah 3:14-20","Canticle 9"] },
  "2027-12-19": { gospel: "Luke 1:39-45, (46-55)", nt: ["Hebrews 10:5-10"], psalm: "Psalm 80:1-7", ot: ["Micah 5:2-5a","Canticle 15 (or 3)"] },
};
