/**
 * Forward Movement's Lesser Feasts & Fasts calendar, by date.
 *
 * Owner: "what if each time there is a hagiography, when there is the feast
 * listing under the date, if you click that line, it brings up the whole page,
 * and you have the reader over it like you have over Day by Day."
 *
 * WHY A LINK AND NOT THE TEXT. Forward Movement's own footer says it: the
 * collects and the lives are taken from Lesser Feasts and Fasts 2024,
 * copyright the Domestic and Foreign Missionary Society, used by permission.
 * That permission is Forward Movement's, not ours. So Phoebe opens THEIR page
 * — as published, with their notice intact — in the same in-app reader that
 * already opens Forward Day by Day. Nothing is copied, and the attribution
 * travels with the words. It is the rule this app already follows for oremus
 * and the newsletters, applied to one more publisher.
 *
 * KEYED BY DATE, NOT BY NAME, on purpose. Their titles and ours often differ
 * for the same day — 9 September is "Constance, Thecla, Ruth, Frances, Charles
 * Parsons, and Louis Schuyler, Martyrs" in lesser-feasts.ts and "The Martyrs of
 * Memphis" to them — so any name match would silently miss exactly the entries
 * a reader most wants. Month-day cannot drift.
 *
 * Read from their calendar index (277 dated entries, all twelve months).
 * If they re-slug a page the link 404s in the reader rather than breaking the
 * home, and the fix is one line here.
 */
const FM_CALENDAR: Record<string, string> = {
  "1-1": "holy-name",
  "1-4": "elizabeth-ann-seton",
  "1-5": "january-5",
  "1-6": "epiphany",
  "1-8": "harriet-bedell",
  "1-9": "julia-chester-emery",
  "1-10": "william-laud",
  "1-12": "aelred-of-rievaulx",
  "1-13": "hilary-of-poitiers",
  "1-14": "richard-meux-benson",
  "1-17": "antony-of-egypt",
  "1-18": "confession-of-st-peter",
  "1-19": "wulfstan-of-worcester",
  "1-20": "fabian",
  "1-21": "agnes-and-cecilia-of-rome",
  "1-22": "vincent-of-saragossa",
  "1-23": "phillips-brooks",
  "1-24": "florence-li-timoi",
  "1-25": "conversion-of-st-paul",
  "1-26": "titus-and-timothy",
  "1-27": "john-chrysostom",
  "1-28": "thomas-aquinas",
  "1-29": "liliuokalani",
  "1-31": "marcella-of-rome",
  "2-1": "brigid-of-kildare",
  "2-2": "the-presentation",
  "2-3": "anskar",
  "2-4": "manche-masemola",
  "2-5": "agatha-of-sicily",
  "2-6": "the-martyrs-of-japan",
  "2-8": "bakhita-josephine-margaret-bakhita",
  "2-10": "scholastica-of-nursia",
  "2-11": "barbara-harris",
  "2-12": "theodora",
  "2-13": "absalom-jones",
  "2-14": "cyril-and-methodius",
  "2-15": "thomas-bray",
  "2-17": "janani-luwum",
  "2-18": "martin-luther",
  "2-19": "agnes-tsao-kou-ying",
  "2-20": "frederick-douglass",
  "2-22": "margaret-of-cortona",
  "2-23": "polycarp-of-smyrna",
  "2-24": "st-matthias",
  "2-25": "emily-malbone-morgan",
  "2-26": "photini",
  "2-27": "george-herbert",
  "2-28": "anna-julia-haywood-cooper",
  "3-1": "david-of-wales",
  "3-2": "chad-of-lichfield",
  "3-3": "john-and-charles-wesley",
  "3-7": "perpetua-and-felicity",
  "3-9": "gregory-of-nyssa",
  "3-10": "harriet-ross-tubman",
  "3-12": "gregory-the-great",
  "3-13": "james-theodore-holly",
  "3-15": "vincent-de-paul",
  "3-17": "patrick-of-ireland",
  "3-18": "cyril-of-jerusalem",
  "3-19": "st-joseph",
  "3-20": "cuthbert",
  "3-21": "thomas-ken",
  "3-22": "james-de-koven",
  "3-23": "gregory-the-illuminator",
  "3-24": "oscar-romero",
  "3-25": "annunciation",
  "3-26": "harriet-monsell",
  "3-27": "charles-henry-brent",
  "3-28": "james-solomon-russell",
  "3-29": "john-keble",
  "3-30": "mary-of-egypt",
  "3-31": "john-donne",
  "4-1": "frederick-denison-maurice",
  "4-2": "james-lloyd-breck",
  "4-3": "richard-of-chichester",
  "4-4": "martin-luther-king",
  "4-5": "harriet-starr-cannon",
  "4-7": "tikhon",
  "4-8": "william-augustus-muhlenberg",
  "4-9": "dietrich-bonhoeffer",
  "4-10": "william-law",
  "4-11": "george-augustus-selwyn",
  "4-14": "zenaida",
  "4-15": "damien",
  "4-16": "peter-williams-cassey",
  "4-17": "kateri-tekakwitha",
  "4-18": "juana-ines-de-la-cruz",
  "4-19": "alphege",
  "4-21": "anselm-of-canterbury",
  "4-22": "hadewijch-of-brabant",
  "4-23": "toyohiko-kagawa",
  "4-25": "st-mark",
  "4-27": "zita-of-tuscany",
  "4-29": "catherine-of-siena",
  "5-1": "ss-philip-and-james",
  "5-2": "athanasius-of-alexandria",
  "5-3": "elisabeth-cruciger",
  "5-4": "monica",
  "5-5": "martyrs-of-the-reformation-era",
  "5-6": "george-of-lydda",
  "5-8": "julian-of-norwich",
  "5-9": "gregory-of-nazianzus",
  "5-11": "johann-arndt-and-jacob-boehme",
  "5-13": "frances-perkins",
  "5-15": "pachomius-of-tabenissi",
  "5-17": "thurgood-marshall",
  "5-19": "dunstan",
  "5-20": "alcuin-of-york",
  "5-21": "lydia-of-thyatira",
  "5-22": "helena-of-constantinople",
  "5-24": "jackson-kemper",
  "5-25": "bede",
  "5-26": "augustine",
  "5-28": "mechthild-of-magdeburg",
  "5-31": "the-visitation",
  "6-1": "justin",
  "6-2": "blandina-and-her-companions",
  "6-3": "the-martyrs-of-uganda",
  "6-4": "john-xxiii-angelo-giuseppe-roncalli",
  "6-5": "boniface",
  "6-8": "melania-the-elder",
  "6-9": "columba-of-iona",
  "6-10": "ephrem-of-nisibis",
  "6-11": "st-barnabas",
  "6-12": "enmegahbowh",
  "6-13": "first-bcp",
  "6-14": "basil-of-caesarea",
  "6-15": "evelyn-underhill",
  "6-16": "joseph-butler",
  "6-17": "marina-the-monk",
  "6-18": "bernard-mizeki",
  "6-19": "adelaide-teague-case",
  "6-22": "alban",
  "6-24": "nativity-of-st-john-the-baptist",
  "6-26": "isabel-florence-hapgood",
  "6-28": "irenaeus-of-lyons",
  "6-29": "ss-peter-and-paul",
  "7-1": "pauli-murray",
  "7-2": "moses-the-black",
  "7-4": "independence-day",
  "7-6": "eva-lee-matthews",
  "7-8": "priscilla-and-aquila",
  "7-11": "benedict-of-nursia",
  "7-14": "argula-von-grumbach",
  "7-17": "william-white",
  "7-19": "macrina-of-caesarea",
  "7-20": "elizabeth-cady-stanton",
  "7-21": "maria-skobtsova",
  "7-22": "st-mary-magdalene",
  "7-23": "john-cassian",
  "7-24": "thomas-a-kempis",
  "7-25": "st-james",
  "7-26": "the-parents-of-the-blessed-virgin-mary",
  "7-27": "william-reed-huntington",
  "7-28": "johann-sebasatian-bach",
  "7-29": "mary-and-martha-of-bethany",
  "7-30": "william-wilberforce",
  "7-31": "ignatius-of-loyola",
  "8-1": "joseph-of-arimathea",
  "8-3": "joanna",
  "8-6": "the-transfiguration",
  "8-7": "john-mason-neale",
  "8-8": "dominic",
  "8-9": "edith-stein-teresa-benedicta-of-the-cross",
  "8-10": "laurence-of-rome",
  "8-11": "clare-of-assisi",
  "8-12": "florence-nightingale",
  "8-13": "jeremy-taylor",
  "8-14": "jonathan-myrick-daniels",
  "8-15": "st-mary-the-virgin",
  "8-20": "bernard-of-clairvaux",
  "8-24": "st-bartholomew",
  "8-25": "louis",
  "8-26": "simeon-bachos",
  "8-27": "thomas-gallaudet-and-henry-winter-syle",
  "8-28": "augustine-of-hippo",
  "8-29": "the-beheading-of-saint-john-the-baptist",
  "8-30": "margaret-ward",
  "8-31": "aidan-of-lindisfarne",
  "9-1": "david-pendleton-oakerhater",
  "9-2": "the-martyrs-of-new-guinea",
  "9-3": "phoebe",
  "9-4": "paul-jones",
  "9-5": "katharina-zell",
  "9-6": "hannah-more",
  "9-7": "kassiani",
  "9-8": "the-nativity-of-the-blessed-virgin-mary",
  "9-9": "the-martyrs-of-memphis",
  "9-10": "alexander-crummell",
  "9-12": "john-henry-hobart",
  "9-13": "cyprian-of-carthage",
  "9-14": "holy-cross",
  "9-15": "catherine-of-genoa",
  "9-16": "ninian",
  "9-17": "hildegard-of-bingen",
  "9-18": "edward-bouverie-pusey",
  "9-19": "theodore-of-tarsus",
  "9-20": "john-coleridge-patteson",
  "9-21": "st-matthew",
  "9-22": "philander-chase",
  "9-23": "thecla-of-iconium",
  "9-24": "anna-ellison-butler-alexander",
  "9-25": "sergius-of-radonezh",
  "9-26": "lancelot-andrewes",
  "9-27": "euphrosynesmaragdus-of-alexandria",
  "9-28": "paula-and-eustochium-of-rome",
  "9-29": "st-michael",
  "9-30": "jerome",
  "10-1": "therese-of-lisieux",
  "10-2": "remigius-of-rheims",
  "10-3": "john-raleigh-mott",
  "10-4": "francis-of-assisi",
  "10-6": "william-tyndale",
  "10-7": "birgitta-of-sweden",
  "10-9": "robert-grosseteste",
  "10-10": "vida-dutton-scudder",
  "10-11": "philip",
  "10-12": "edith-cavell",
  "10-14": "samuel-isaac-joseph-scherechewsky",
  "10-15": "teresa-of-avila",
  "10-16": "hugh-latimer-and-nicholas-ridley",
  "10-17": "ignatius-of-antioch",
  "10-18": "st-luke",
  "10-19": "henry-martyn",
  "10-20": "cornelius-the-centurion",
  "10-23": "st-james-of-jerusalem",
  "10-25": "tabitha-dorcas-of-joppa",
  "10-26": "alfred",
  "10-28": "ss-simon-and-jude",
  "10-29": "james-hannington",
  "10-30": "maryam-of-qidun",
  "11-1": "all-saints-day",
  "11-2": "all-souls-day",
  "11-3": "richard-hooker",
  "11-4": "adeline-tyler",
  "11-6": "william-temple",
  "11-7": "willibrord",
  "11-8": "ammonius",
  "11-9": "richard-rolle-",
  "11-10": "leo-of-rome",
  "11-11": "martin-of-tours",
  "11-12": "charles-simeon",
  "11-14": "samuel-seabury",
  "11-15": "herman-of-alaska",
  "11-16": "margaret-of-scotland",
  "11-17": "hugh-of-lincoln",
  "11-18": "hilda-of-whitby",
  "11-19": "elizabeth-of-hungary",
  "11-20": "edmund",
  "11-21": "mechthilde-of-hackeborn-and-gertrude-the-great",
  "11-22": "clive-staples-lewis",
  "11-23": "clement-of-rome",
  "11-24": "catherine-of-alexandria",
  "11-25": "james-otis-sargent-huntington",
  "11-28": "kamehameha-and-emma",
  "11-30": "st-andrew",
  "12-1": "charles-de-foucauld",
  "12-2": "channing-moore-williams",
  "12-3": "francis-xavier",
  "12-4": "john-of-damascus",
  "12-5": "clement-of-alexandria",
  "12-6": "nicholas-of-myra",
  "12-7": "ambrose-of-milan",
  "12-8": "nicholas-ferrar",
  "12-11": "frederick-howden",
  "12-12": "francis-de-sales",
  "12-13": "lucy-of-syracuse",
  "12-14": "john-of-the-cross",
  "12-15": "nino-of-georgia",
  "12-17": "dorothy-l-sayers",
  "12-20": "katharina-von-bora",
  "12-21": "st-thomas",
  "12-25": "christmas-day",
  "12-26": "st-stephen",
  "12-27": "st-john",
  "12-28": "holy-innocents",
  "12-29": "thomas-becket",
};

/** Forward Movement's page for this date's commemoration, or null. */
export function forwardMovementFeastUrl(date: Date = new Date()): string | null {
  const slug = FM_CALENDAR[`${date.getMonth() + 1}-${date.getDate()}`];
  return slug ? `https://prayer.forwardmovement.org/calendar/${slug}` : null;
}
