// Lesser Feasts and Fasts (LFF 2022) — optional commemorations.
//
// Compact entries: { month, day, name, color, life? }
//   - Martyrs / Martyr → red
//   - Everyone else → white
// Life dates are the year of death unless the tradition is older
// (then an era string like "fourth century").
//
// This file registers itself with the liturgical calendar on import.
// calendar.ts then surfaces these as `commemoration` on the ferial
// header line — the date stays primary, the saint sits beneath.

import type { FixedFeastEntry } from "./types";
import { registerLesserFeasts } from "./calendar";

const ENTRIES: FixedFeastEntry[] = [
  // ── January ───────────────────────────────────────────────
  { month: 1, day: 4,  rank: "lesser_feast", name: "Elizabeth Seton, Vowed Religious and Educator",         color: "white", life: "1821" },
  { month: 1, day: 5,  rank: "lesser_feast", name: "Sarah, Theodora, and Syncletica of Egypt, Desert Mothers", color: "white", life: "fourth–fifth century" },
  { month: 1, day: 8,  rank: "lesser_feast", name: "Harriet Bedell, Deaconess and Missionary",              color: "white", life: "1969" },
  { month: 1, day: 9,  rank: "lesser_feast", name: "Julia Chester Emery, Lay Leader and Missionary",         color: "white", life: "1922" },
  { month: 1, day: 10, rank: "lesser_feast", name: "William Laud, Archbishop of Canterbury",                color: "white", life: "1645" },
  { month: 1, day: 12, rank: "lesser_feast", name: "Aelred of Rievaulx, Monastic and Theologian",           color: "white", life: "1167" },
  { month: 1, day: 13, rank: "lesser_feast", name: "Hilary of Poitiers, Bishop",                            color: "white", life: "367" },
  { month: 1, day: 14, rank: "lesser_feast", name: "Richard Meux Benson, Priest, and Charles Gore, Bishop", color: "white", life: "1915 and 1932" },
  { month: 1, day: 17, rank: "lesser_feast", name: "Antony of Egypt, Monastic",                             color: "white" },
  { month: 1, day: 19, rank: "lesser_feast", name: "Wulfstan of Worcester, Bishop",                         color: "white", life: "1095" },
  { month: 1, day: 20, rank: "lesser_feast", name: "Fabian, Bishop and Martyr",                             color: "red",   life: "250" },
  { month: 1, day: 21, rank: "lesser_feast", name: "Agnes and Cecilia of Rome, Martyrs",                    color: "red",   life: "304 and c. 230" },
  { month: 1, day: 22, rank: "lesser_feast", name: "Vincent of Saragossa, Deacon and Martyr",               color: "red",   life: "304" },
  { month: 1, day: 23, rank: "lesser_feast", name: "Phillips Brooks, Bishop",                               color: "white", life: "1893" },
  { month: 1, day: 24, rank: "lesser_feast", name: "Florence Li Tim-Oi, Priest",                            color: "white", life: "1992" },
  { month: 1, day: 26, rank: "lesser_feast", name: "Timothy and Titus, Companions of Saint Paul",           color: "white" },
  { month: 1, day: 27, rank: "lesser_feast", name: "John Chrysostom, Bishop and Theologian",                color: "white", life: "407" },
  { month: 1, day: 28, rank: "lesser_feast", name: "Thomas Aquinas, Friar and Theologian",                  color: "white", life: "1274" },
  { month: 1, day: 29, rank: "lesser_feast", name: "Liliʻuokalani of Hawai'i",                              color: "white" },
  { month: 1, day: 31, rank: "lesser_feast", name: "Marcella of Rome, Monastic and Scholar",                color: "white", life: "410" },

  // ── February ──────────────────────────────────────────────
  { month: 2, day: 1,  rank: "lesser_feast", name: "Brigid of Kildare, Monastic",                           color: "white", life: "c. 523" },
  { month: 2, day: 3,  rank: "lesser_feast", name: "Anskar, Bishop and Missionary",                         color: "white", life: "865" },
  { month: 2, day: 4,  rank: "lesser_feast", name: "Manche Masemola, Martyr",                               color: "red",   life: "1928" },
  { month: 2, day: 5,  rank: "lesser_feast", name: "Agatha of Sicily, Martyr",                              color: "red",   life: "c. 251" },
  { month: 2, day: 6,  rank: "lesser_feast", name: "The Martyrs of Japan",                                  color: "red",   life: "1597" },
  { month: 2, day: 8,  rank: "lesser_feast", name: "Bakhita (Josephine Margaret Bakhita), Monastic",        color: "white", life: "1947" },
  { month: 2, day: 10, rank: "lesser_feast", name: "Scholastica, Monastic",                                 color: "white", life: "543" },
  { month: 2, day: 11, rank: "lesser_feast", name: "The Consecration of Barbara Clementine Harris, First Woman Bishop in the Anglican Communion", color: "white", life: "1989" },
  { month: 2, day: 12, rank: "lesser_feast", name: "Theodora, Empress",                                     color: "white", life: "c. 867" },
  { month: 2, day: 13, rank: "lesser_feast", name: "Absalom Jones, Priest",                                 color: "white", life: "1818" },
  { month: 2, day: 14, rank: "lesser_feast", name: "Cyril and Methodius, Missionaries",                     color: "white", life: "869 and 885" },
  { month: 2, day: 15, rank: "lesser_feast", name: "Thomas Bray, Priest and Missionary",                    color: "white", life: "1730" },
  { month: 2, day: 17, rank: "lesser_feast", name: "Janani Luwum, Archbishop and Martyr",                   color: "red",   life: "1977" },
  { month: 2, day: 18, rank: "lesser_feast", name: "Martin Luther, Pastor and Reformer",                    color: "white", life: "1546" },
  { month: 2, day: 19, rank: "lesser_feast", name: "Agnes Tsao Kou Ying, Agatha Lin Zhao, and Lucy Yi Zhenmei, Catechists and Martyrs", color: "red", life: "1856, 1858, and 1862" },
  { month: 2, day: 20, rank: "lesser_feast", name: "Frederick Douglass, Social Reformer",                   color: "white", life: "1895" },
  { month: 2, day: 22, rank: "lesser_feast", name: "Margaret of Cortona, Monastic",                         color: "white", life: "1297" },
  { month: 2, day: 23, rank: "lesser_feast", name: "Polycarp, Bishop and Martyr of Smyrna",                 color: "red",   life: "156" },
  { month: 2, day: 25, rank: "lesser_feast", name: "Emily Malbone Morgan, Lay Leader and Contemplative",    color: "white", life: "1937" },
  { month: 2, day: 26, rank: "lesser_feast", name: "Photini, The Samaritan Woman",                          color: "white", life: "c. 67" },
  { month: 2, day: 27, rank: "lesser_feast", name: "George Herbert, Priest and Poet",                       color: "white", life: "1633" },
  { month: 2, day: 28, rank: "lesser_feast", name: "Anna Julia Haywood Cooper, Educator",                   color: "white", life: "1964" },

  // ── March ─────────────────────────────────────────────────
  { month: 3, day: 1,  rank: "lesser_feast", name: "David of Wales, Bishop",                                color: "white", life: "c. 544" },
  { month: 3, day: 2,  rank: "lesser_feast", name: "Chad of Lichfield, Bishop",                             color: "white", life: "672" },
  { month: 3, day: 3,  rank: "lesser_feast", name: "John and Charles Wesley, Priests",                      color: "white", life: "1791, 1788" },
  { month: 3, day: 7,  rank: "lesser_feast", name: "Perpetua and Felicity, Martyrs",                        color: "red",   life: "202" },
  { month: 3, day: 9,  rank: "lesser_feast", name: "Gregory of Nyssa, Bishop and Theologian",               color: "white", life: "c. 394" },
  { month: 3, day: 10, rank: "lesser_feast", name: "Harriet Ross Tubman, Social Reformer",                  color: "white", life: "1923" },
  { month: 3, day: 12, rank: "lesser_feast", name: "Gregory the Great, Bishop and Theologian",              color: "white", life: "604" },
  { month: 3, day: 13, rank: "lesser_feast", name: "James Theodore Holly, Bishop",                          color: "white", life: "1911" },
  { month: 3, day: 15, rank: "lesser_feast", name: "Vincent de Paul, Priest, and Louise de Marillac, Vowed Religious, Workers of Charity", color: "white", life: "1660" },
  { month: 3, day: 17, rank: "lesser_feast", name: "Patrick of Ireland, Bishop and Missionary",             color: "white", life: "461" },
  { month: 3, day: 18, rank: "lesser_feast", name: "Cyril of Jerusalem, Bishop and Theologian",             color: "white", life: "386" },
  { month: 3, day: 20, rank: "lesser_feast", name: "Cuthbert, Bishop",                                      color: "white", life: "687" },
  { month: 3, day: 21, rank: "lesser_feast", name: "Thomas Ken, Bishop of Bath and Wells",                  color: "white", life: "1711" },
  { month: 3, day: 22, rank: "lesser_feast", name: "James De Koven, Priest",                                color: "white", life: "1879" },
  { month: 3, day: 23, rank: "lesser_feast", name: "Gregory the Illuminator, Bishop and Missionary",        color: "white", life: "c. 332" },
  { month: 3, day: 24, rank: "lesser_feast", name: "Óscar Romero, Archbishop and Martyr, and the Martyrs of El Salvador", color: "red", life: "1980" },
  { month: 3, day: 26, rank: "lesser_feast", name: "Harriet Monsell, Monastic",                             color: "white", life: "1883" },
  { month: 3, day: 27, rank: "lesser_feast", name: "Charles Henry Brent, Bishop",                           color: "white", life: "1929" },
  { month: 3, day: 28, rank: "lesser_feast", name: "James Solomon Russell, Priest",                         color: "white", life: "1935" },
  { month: 3, day: 29, rank: "lesser_feast", name: "John Keble, Priest and Poet",                           color: "white", life: "1866" },
  { month: 3, day: 30, rank: "lesser_feast", name: "Mary of Egypt, Monastic",                               color: "white", life: "c. 421" },
  { month: 3, day: 31, rank: "lesser_feast", name: "John Donne, Priest and Poet",                           color: "white", life: "1631" },

  // ── April ─────────────────────────────────────────────────
  { month: 4, day: 1,  rank: "lesser_feast", name: "Frederick Denison Maurice, Priest",                     color: "white", life: "1872" },
  { month: 4, day: 2,  rank: "lesser_feast", name: "James Lloyd Breck, Priest",                             color: "white", life: "1876" },
  { month: 4, day: 3,  rank: "lesser_feast", name: "Richard of Chichester, Bishop",                         color: "white", life: "1253" },
  { month: 4, day: 4,  rank: "lesser_feast", name: "Martin Luther King, Jr., Pastor and Martyr",            color: "red",   life: "1968" },
  { month: 4, day: 5,  rank: "lesser_feast", name: "Harriet Starr Cannon, Monastic",                        color: "white", life: "1896" },
  { month: 4, day: 7,  rank: "lesser_feast", name: "Tikhon, Bishop and Ecumenist",                          color: "white", life: "1925" },
  { month: 4, day: 8,  rank: "lesser_feast", name: "William Augustus Muhlenberg, Priest",                   color: "white", life: "1877" },
  { month: 4, day: 9,  rank: "lesser_feast", name: "Dietrich Bonhoeffer, Pastor and Theologian",            color: "white", life: "1945" },
  { month: 4, day: 10, rank: "lesser_feast", name: "William Law, Priest",                                   color: "white", life: "1761" },
  { month: 4, day: 11, rank: "lesser_feast", name: "George Augustus Selwyn, Bishop",                        color: "white", life: "1878" },
  { month: 4, day: 14, rank: "lesser_feast", name: "Zenaida, Philonella, and Hermione, Unmercenary Physicians", color: "white", life: "c. 100, c. 117" },
  { month: 4, day: 15, rank: "lesser_feast", name: "Damien, Priest, and Marianne Cope, Monastic, of Hawai'i", color: "white", life: "1889 and 1918" },
  { month: 4, day: 16, rank: "lesser_feast", name: "Peter Williams Cassey, Deacon, and Annie Besant Cassey", color: "white", life: "1917 and 1875" },
  { month: 4, day: 17, rank: "lesser_feast", name: "Kateri Tekakwitha, Lay Contemplative",                  color: "white", life: "1680" },
  { month: 4, day: 18, rank: "lesser_feast", name: "Juana Inés de la Cruz, Monastic and Theologian",        color: "white", life: "1695" },
  { month: 4, day: 19, rank: "lesser_feast", name: "Alphege, Archbishop of Canterbury, and Martyr",         color: "red",   life: "1012" },
  { month: 4, day: 21, rank: "lesser_feast", name: "Anselm, Archbishop of Canterbury",                      color: "white", life: "1109" },
  { month: 4, day: 22, rank: "lesser_feast", name: "Hadewijch of Brabant, Poet and Mystic",                 color: "white", life: "thirteenth century" },
  { month: 4, day: 23, rank: "lesser_feast", name: "Toyohiko Kagawa, Social Reformer",                      color: "white", life: "1960" },
  { month: 4, day: 27, rank: "lesser_feast", name: "Zita of Tuscany, Worker of Charity",                    color: "white", life: "1271" },
  { month: 4, day: 29, rank: "lesser_feast", name: "Catherine of Siena, Mystic and Prophetic Witness",      color: "white", life: "1380" },

  // ── May ───────────────────────────────────────────────────
  { month: 5, day: 2,  rank: "lesser_feast", name: "Athanasius of Alexandria, Bishop and Theologian",       color: "white", life: "373" },
  { month: 5, day: 3,  rank: "lesser_feast", name: "Elisabeth Cruciger, Poet and Hymnographer",             color: "white", life: "1535" },
  { month: 5, day: 4,  rank: "lesser_feast", name: "Monica, Mother of Augustine of Hippo",                  color: "white", life: "387" },
  { month: 5, day: 5,  rank: "lesser_feast", name: "Martyrs of the Reformation Era",                        color: "red" },
  { month: 5, day: 6,  rank: "lesser_feast", name: "George of Lydda, Martyr",                               color: "red",   life: "c. 304" },
  { month: 5, day: 8,  rank: "lesser_feast", name: "Julian of Norwich, Mystic and Theologian",              color: "white", life: "c. 1417" },
  { month: 5, day: 9,  rank: "lesser_feast", name: "Gregory of Nazianzus, Bishop and Theologian",           color: "white", life: "389" },
  { month: 5, day: 11, rank: "lesser_feast", name: "Johann Arndt and Jacob Boehme, Mystics",                color: "white", life: "1621 and 1624" },
  { month: 5, day: 13, rank: "lesser_feast", name: "Frances Perkins, Social Reformer",                      color: "white", life: "1965" },
  { month: 5, day: 15, rank: "lesser_feast", name: "Pachomius of Tabennisi, Monastic",                      color: "white", life: "348" },
  { month: 5, day: 17, rank: "lesser_feast", name: "Thurgood Marshall, Public Servant",                     color: "white", life: "1993" },
  { month: 5, day: 19, rank: "lesser_feast", name: "Dunstan, Archbishop of Canterbury",                     color: "white", life: "988" },
  { month: 5, day: 20, rank: "lesser_feast", name: "Alcuin, Deacon, and Abbot of Tours",                    color: "white", life: "804" },
  { month: 5, day: 21, rank: "lesser_feast", name: "Lydia of Thyatira, Coworker of the Apostle Paul",       color: "white" },
  { month: 5, day: 22, rank: "lesser_feast", name: "Helena of Constantinople, Protector of the Holy Places", color: "white", life: "330" },
  { month: 5, day: 24, rank: "lesser_feast", name: "Jackson Kemper, Bishop and Missionary",                 color: "white", life: "1870" },
  { month: 5, day: 25, rank: "lesser_feast", name: "Bede the Venerable, Priest and Historian",              color: "white", life: "735" },
  { month: 5, day: 26, rank: "lesser_feast", name: "Augustine, First Archbishop of Canterbury",             color: "white", life: "605" },
  { month: 5, day: 28, rank: "lesser_feast", name: "Mechthild of Magdeburg, Mystic",                        color: "white", life: "c. 1282" },

  // ── June ──────────────────────────────────────────────────
  { month: 6, day: 1,  rank: "lesser_feast", name: "Justin, Martyr",                                        color: "red",   life: "c. 167" },
  { month: 6, day: 2,  rank: "lesser_feast", name: "Blandina and Her Companions, The Martyrs of Lyons",     color: "red",   life: "177" },
  { month: 6, day: 3,  rank: "lesser_feast", name: "The Martyrs of Uganda",                                 color: "red",   life: "1886" },
  { month: 6, day: 4,  rank: "lesser_feast", name: "John XXIII (Angelo Giuseppe Roncalli), Bishop",         color: "white", life: "1963" },
  { month: 6, day: 5,  rank: "lesser_feast", name: "Boniface, Bishop and Missionary",                       color: "white", life: "754" },
  { month: 6, day: 8,  rank: "lesser_feast", name: "Melania the Elder, Monastic",                           color: "white", life: "410" },
  { month: 6, day: 9,  rank: "lesser_feast", name: "Columba of Iona, Monastic",                             color: "white", life: "597" },
  { month: 6, day: 10, rank: "lesser_feast", name: "Ephrem of Nisibis, Deacon and Poet",                    color: "white", life: "373" },
  { month: 6, day: 12, rank: "lesser_feast", name: "Enmegahbowh, Priest and Missionary",                    color: "white", life: "1902" },
  { month: 6, day: 13, rank: "lesser_feast", name: "The First Book of Common Prayer",                       color: "white", life: "1549" },
  { month: 6, day: 14, rank: "lesser_feast", name: "Basil of Caesarea, Bishop and Theologian",              color: "white", life: "379" },
  { month: 6, day: 15, rank: "lesser_feast", name: "Evelyn Underhill, Mystic and Writer",                   color: "white", life: "1941" },
  { month: 6, day: 16, rank: "lesser_feast", name: "Joseph Butler, Bishop and Theologian",                  color: "white", life: "1752" },
  { month: 6, day: 17, rank: "lesser_feast", name: "Marina the Monk, Monastic",                             color: "white", life: "fifth century" },
  { month: 6, day: 18, rank: "lesser_feast", name: "Bernard Mizeki, Martyr",                                color: "red",   life: "1896" },
  { month: 6, day: 19, rank: "lesser_feast", name: "Adelaide Teague Case, Educator",                        color: "white", life: "1948" },
  { month: 6, day: 22, rank: "lesser_feast", name: "Alban, Martyr",                                         color: "red",   life: "c. 304" },
  { month: 6, day: 26, rank: "lesser_feast", name: "Isabel Florence Hapgood, Ecumenist",                    color: "white", life: "1928" },
  { month: 6, day: 28, rank: "lesser_feast", name: "Irenaeus of Lyons, Bishop and Theologian",              color: "white", life: "c. 202" },

  // ── July ──────────────────────────────────────────────────
  { month: 7, day: 1,  rank: "lesser_feast", name: "Pauli Murray, Priest",                                  color: "white", life: "1985" },
  { month: 7, day: 2,  rank: "lesser_feast", name: "Moses the Black, Monastic and Martyr",                  color: "red",   life: "c. 400" },
  { month: 7, day: 6,  rank: "lesser_feast", name: "Eva Lee Matthews, Monastic",                            color: "white", life: "1928" },
  { month: 7, day: 8,  rank: "lesser_feast", name: "Priscilla and Aquila, Coworkers of the Apostle Paul",   color: "white" },
  { month: 7, day: 11, rank: "lesser_feast", name: "Benedict of Nursia, Monastic",                          color: "white", life: "c. 543" },
  { month: 7, day: 14, rank: "lesser_feast", name: "Argula von Grumbach, Scholar and Church Reformer",      color: "white", life: "c. 1554" },
  { month: 7, day: 17, rank: "lesser_feast", name: "William White, Bishop",                                 color: "white", life: "1836" },
  { month: 7, day: 19, rank: "lesser_feast", name: "Macrina of Caesarea, Monastic and Teacher",             color: "white", life: "379" },
  { month: 7, day: 20, rank: "lesser_feast", name: "Elizabeth Cady Stanton, Amelia Bloomer, and Sojourner Truth, Social Reformers", color: "white" },
  { month: 7, day: 21, rank: "lesser_feast", name: "Maria Skobtsova, Monastic and Martyr",                  color: "red",   life: "1945" },
  { month: 7, day: 23, rank: "lesser_feast", name: "John Cassian, Monastic and Theologian",                 color: "white", life: "435" },
  { month: 7, day: 24, rank: "lesser_feast", name: "Thomas à Kempis, Priest and Mystic",                    color: "white", life: "1471" },
  { month: 7, day: 26, rank: "lesser_feast", name: "The Parents of the Blessed Virgin Mary",                color: "white" },
  { month: 7, day: 27, rank: "lesser_feast", name: "William Reed Huntington, Priest",                       color: "white", life: "1909" },
  { month: 7, day: 28, rank: "lesser_feast", name: "Johann Sebastian Bach, Composer",                       color: "white", life: "1750" },
  { month: 7, day: 29, rank: "lesser_feast", name: "Mary and Martha of Bethany, or The Philadelphia Eleven", color: "white" },
  { month: 7, day: 30, rank: "lesser_feast", name: "William Wilberforce, Social Reformer",                  color: "white", life: "1833" },
  { month: 7, day: 31, rank: "lesser_feast", name: "Ignatius of Loyola, Priest and Spiritual Writer",       color: "white", life: "1556" },

  // ── August ────────────────────────────────────────────────
  { month: 8, day: 1,  rank: "lesser_feast", name: "Joseph of Arimathaea",                                  color: "white" },
  { month: 8, day: 3,  rank: "lesser_feast", name: "Joanna, Mary, and Salome, Myrrh-Bearing Women",         color: "white" },
  { month: 8, day: 7,  rank: "lesser_feast", name: "John Mason Neale, Priest and Hymnographer",             color: "white", life: "1866" },
  { month: 8, day: 8,  rank: "lesser_feast", name: "Dominic, Priest and Friar",                             color: "white", life: "1221" },
  { month: 8, day: 9,  rank: "lesser_feast", name: "Edith Stein (Teresa Benedicta of the Cross), Philosopher, Monastic, and Martyr", color: "red", life: "1942" },
  { month: 8, day: 10, rank: "lesser_feast", name: "Laurence of Rome, Deacon and Martyr",                   color: "red",   life: "258" },
  { month: 8, day: 11, rank: "lesser_feast", name: "Clare of Assisi, Monastic",                             color: "white", life: "1253" },
  { month: 8, day: 12, rank: "lesser_feast", name: "Florence Nightingale, Nurse",                           color: "white", life: "1910" },
  { month: 8, day: 13, rank: "lesser_feast", name: "Jeremy Taylor, Bishop and Theologian",                  color: "white", life: "1667" },
  { month: 8, day: 14, rank: "lesser_feast", name: "Jonathan Myrick Daniels, Martyr",                       color: "red",   life: "1965" },
  { month: 8, day: 20, rank: "lesser_feast", name: "Bernard of Clairvaux, Monastic and Theologian",         color: "white", life: "1153" },
  { month: 8, day: 25, rank: "lesser_feast", name: "Louis, King",                                           color: "white", life: "1270" },
  { month: 8, day: 27, rank: "lesser_feast", name: "Thomas Gallaudet and Henry Winter Syle, Priests",       color: "white", life: "1902 and 1890" },
  { month: 8, day: 28, rank: "lesser_feast", name: "Augustine of Hippo, Bishop and Theologian",             color: "white", life: "430" },
  { month: 8, day: 29, rank: "lesser_feast", name: "The Beheading of Saint John the Baptist",               color: "red" },
  { month: 8, day: 30, rank: "lesser_feast", name: "Margaret Ward, Margaret Clitherow, and Anne Line, Martyrs", color: "red", life: "1588, 1586, and 1601" },
  { month: 8, day: 31, rank: "lesser_feast", name: "Aidan of Lindisfarne, Bishop",                          color: "white", life: "651" },

  // ── September ─────────────────────────────────────────────
  { month: 9, day: 1,  rank: "lesser_feast", name: "David Pendleton Oakerhater, Deacon",                    color: "white", life: "1931" },
  { month: 9, day: 2,  rank: "lesser_feast", name: "The Martyrs of New Guinea",                             color: "red",   life: "1942" },
  { month: 9, day: 3,  rank: "lesser_feast", name: "Phoebe, Deacon",                                        color: "white" },
  { month: 9, day: 4,  rank: "lesser_feast", name: "Paul Jones, Bishop",                                    color: "white", life: "1941" },
  { month: 9, day: 5,  rank: "lesser_feast", name: "Katharina Zell, Church Reformer and Writer",            color: "white", life: "1562" },
  { month: 9, day: 6,  rank: "lesser_feast", name: "Hannah More, Religious Writer and Philanthropist",      color: "white", life: "1833" },
  { month: 9, day: 7,  rank: "lesser_feast", name: "Kassiani, Poet and Hymnographer, or Elie Naud, Huguenot Witness to the Faith", color: "white", life: "865 / 1722" },
  { month: 9, day: 8,  rank: "lesser_feast", name: "The Nativity of the Blessed Virgin Mary",               color: "white" },
  { month: 9, day: 9,  rank: "lesser_feast", name: "Constance, Thecla, Ruth, Frances, Charles Parsons, and Louis Schuyler, Martyrs", color: "red", life: "1878" },
  { month: 9, day: 10, rank: "lesser_feast", name: "Alexander Crummell, Priest",                            color: "white", life: "1898" },
  { month: 9, day: 12, rank: "lesser_feast", name: "John Henry Hobart, Bishop of New York",                 color: "white", life: "1830" },
  { month: 9, day: 13, rank: "lesser_feast", name: "Cyprian of Carthage, Bishop and Martyr",                color: "red",   life: "258" },
  { month: 9, day: 15, rank: "lesser_feast", name: "Catherine of Genoa, Mystic and Nurse",                  color: "white", life: "1510" },
  { month: 9, day: 16, rank: "lesser_feast", name: "Ninian, Bishop",                                        color: "white", life: "c. 430" },
  { month: 9, day: 17, rank: "lesser_feast", name: "Hildegard of Bingen, Mystic and Scholar",               color: "white", life: "1179" },
  { month: 9, day: 18, rank: "lesser_feast", name: "Edward Bouverie Pusey, Priest",                         color: "white", life: "1882" },
  { month: 9, day: 19, rank: "lesser_feast", name: "Theodore of Tarsus, Archbishop of Canterbury",          color: "white", life: "690" },
  { month: 9, day: 20, rank: "lesser_feast", name: "John Coleridge Patteson, Bishop, and his Companions, Martyrs", color: "red", life: "1871" },
  { month: 9, day: 22, rank: "lesser_feast", name: "Philander Chase, Bishop",                               color: "white", life: "1852" },
  { month: 9, day: 23, rank: "lesser_feast", name: "Thecla of Iconium, Proto-Martyr Among Women",           color: "red",   life: "c. 70" },
  { month: 9, day: 24, rank: "lesser_feast", name: "Anna Ellison Butler Alexander, Deaconess and Teacher",  color: "white", life: "1947" },
  { month: 9, day: 25, rank: "lesser_feast", name: "Sergius of Radonezh, Monastic of Moscow",               color: "white", life: "1392" },
  { month: 9, day: 26, rank: "lesser_feast", name: "Lancelot Andrewes, Bishop",                             color: "white", life: "1626" },
  { month: 9, day: 27, rank: "lesser_feast", name: "Euphrosyne/Smaragdus of Alexandria, Monastic",          color: "white", life: "fifth century" },
  { month: 9, day: 28, rank: "lesser_feast", name: "Paula and Eustochium of Rome, Monastics and Scholars",  color: "white", life: "404 and c. 419" },
  { month: 9, day: 30, rank: "lesser_feast", name: "Jerome, Priest and Scholar",                            color: "white", life: "420" },

  // ── October ───────────────────────────────────────────────
  { month: 10, day: 1,  rank: "lesser_feast", name: "Thérèse of Lisieux, Monastic",                         color: "white", life: "1897" },
  { month: 10, day: 2,  rank: "lesser_feast", name: "Remigius of Rheims, Bishop",                           color: "white", life: "c. 530" },
  { month: 10, day: 3,  rank: "lesser_feast", name: "John Raleigh Mott, Ecumenist and Missionary",          color: "white", life: "1955" },
  { month: 10, day: 4,  rank: "lesser_feast", name: "Francis of Assisi, Friar",                             color: "white", life: "1226" },
  { month: 10, day: 6,  rank: "lesser_feast", name: "William Tyndale, Priest",                              color: "white", life: "1536" },
  { month: 10, day: 7,  rank: "lesser_feast", name: "Birgitta of Sweden, Mystic",                           color: "white", life: "1373" },
  { month: 10, day: 9,  rank: "lesser_feast", name: "Robert Grosseteste, Bishop",                           color: "white", life: "1253" },
  { month: 10, day: 10, rank: "lesser_feast", name: "Vida Dutton Scudder, Educator",                        color: "white", life: "1954" },
  { month: 10, day: 11, rank: "lesser_feast", name: "Philip, Deacon and Evangelist",                        color: "white" },
  { month: 10, day: 12, rank: "lesser_feast", name: "Edith Cavell, Nurse",                                  color: "white", life: "1915" },
  { month: 10, day: 14, rank: "lesser_feast", name: "Samuel Isaac Joseph Schereschewsky, Bishop and Missionary", color: "white", life: "1906" },
  { month: 10, day: 15, rank: "lesser_feast", name: "Teresa of Avila, Mystic and Monastic Reformer",        color: "white", life: "1582" },
  { month: 10, day: 16, rank: "lesser_feast", name: "Hugh Latimer, Nicholas Ridley, and Thomas Cranmer",    color: "red",   life: "1555, 1556" },
  { month: 10, day: 17, rank: "lesser_feast", name: "Ignatius of Antioch, Bishop and Martyr",               color: "red",   life: "c. 115" },
  { month: 10, day: 19, rank: "lesser_feast", name: "Henry Martyn, Priest and Missionary",                  color: "white", life: "1812" },
  { month: 10, day: 20, rank: "lesser_feast", name: "Cornelius the Centurion",                              color: "white" },
  { month: 10, day: 25, rank: "lesser_feast", name: "Tabitha (Dorcas) of Joppa",                            color: "white" },
  { month: 10, day: 26, rank: "lesser_feast", name: "Alfred, King",                                         color: "white", life: "899" },
  { month: 10, day: 29, rank: "lesser_feast", name: "James Hannington, Bishop, and his Companions, Martyrs", color: "red",  life: "1885" },
  { month: 10, day: 30, rank: "lesser_feast", name: "Maryam of Qidun, Monastic",                            color: "white", life: "fourth century" },

  // ── November ──────────────────────────────────────────────
  { month: 11, day: 2,  rank: "lesser_feast", name: "All Faithful Departed (All Souls' Day)",               color: "white" },
  { month: 11, day: 3,  rank: "lesser_feast", name: "Richard Hooker, Priest and Theologian",                color: "white", life: "1600" },
  { month: 11, day: 4,  rank: "lesser_feast", name: "Adeline Blanchard Tyler and her Companions",           color: "white" },
  { month: 11, day: 6,  rank: "lesser_feast", name: "William Temple, Archbishop of Canterbury",             color: "white", life: "1944" },
  { month: 11, day: 7,  rank: "lesser_feast", name: "Willibrord, Bishop and Missionary",                    color: "white", life: "739" },
  { month: 11, day: 8,  rank: "lesser_feast", name: "Ammonius, Hermit",                                     color: "white", life: "c. 403" },
  { month: 11, day: 9,  rank: "lesser_feast", name: "Richard Rolle, Walter Hilton, and Margery Kempe, Mystics", color: "white", life: "1349, 1396, and c. 1440" },
  { month: 11, day: 10, rank: "lesser_feast", name: "Leo of Rome, Bishop",                                  color: "white", life: "461" },
  { month: 11, day: 11, rank: "lesser_feast", name: "Martin of Tours, Bishop",                              color: "white", life: "397" },
  { month: 11, day: 12, rank: "lesser_feast", name: "Charles Simeon, Priest",                               color: "white", life: "1836" },
  { month: 11, day: 14, rank: "lesser_feast", name: "Consecration of Samuel Seabury, First American Bishop", color: "white", life: "1784" },
  { month: 11, day: 15, rank: "lesser_feast", name: "Herman of Alaska, Missionary",                         color: "white", life: "1837" },
  { month: 11, day: 16, rank: "lesser_feast", name: "Margaret of Scotland, Queen",                          color: "white", life: "1093" },
  { month: 11, day: 17, rank: "lesser_feast", name: "Hugh of Lincoln, Bishop",                              color: "white", life: "1200" },
  { month: 11, day: 18, rank: "lesser_feast", name: "Hilda of Whitby, Abbess",                              color: "white", life: "680" },
  { month: 11, day: 19, rank: "lesser_feast", name: "Elizabeth of Hungary, Princess",                       color: "white", life: "1231" },
  { month: 11, day: 20, rank: "lesser_feast", name: "Edmund, King",                                         color: "white", life: "870" },
  { month: 11, day: 21, rank: "lesser_feast", name: "Mechthilde of Hackeborn and Gertrude the Great, Mystics and Theologians", color: "white", life: "1298 and 1302" },
  { month: 11, day: 22, rank: "lesser_feast", name: "Clive Staples Lewis, Apologist and Spiritual Writer",  color: "white", life: "1963" },
  { month: 11, day: 23, rank: "lesser_feast", name: "Clement of Rome, Bishop",                              color: "white", life: "c. 100" },
  { month: 11, day: 24, rank: "lesser_feast", name: "Catherine of Alexandria, Barbara of Nicomedia, and Margaret of Antioch, Martyrs", color: "red", life: "c. 305" },
  { month: 11, day: 25, rank: "lesser_feast", name: "James Otis Sargent Huntington, Monastic and Priest",   color: "white", life: "1935" },
  { month: 11, day: 28, rank: "lesser_feast", name: "Kamehameha and Emma of Hawai'i, King and Queen",       color: "white", life: "1863 and 1885" },

  // ── December ──────────────────────────────────────────────
  { month: 12, day: 1,  rank: "lesser_feast", name: "Charles de Foucauld, Monastic and Martyr",             color: "red",   life: "1916" },
  { month: 12, day: 2,  rank: "lesser_feast", name: "Channing Moore Williams, Bishop and Missionary",       color: "white", life: "1910" },
  { month: 12, day: 3,  rank: "lesser_feast", name: "Francis Xavier, Priest and Missionary",                color: "white", life: "1552" },
  { month: 12, day: 4,  rank: "lesser_feast", name: "John of Damascus, Priest and Theologian",              color: "white", life: "c. 760" },
  { month: 12, day: 5,  rank: "lesser_feast", name: "Clement of Alexandria, Priest and Theologian",         color: "white", life: "c. 210" },
  { month: 12, day: 6,  rank: "lesser_feast", name: "Nicholas of Myra, Bishop",                             color: "white", life: "c. 342" },
  { month: 12, day: 7,  rank: "lesser_feast", name: "Ambrose of Milan, Bishop and Theologian",              color: "white", life: "397" },
  { month: 12, day: 8,  rank: "lesser_feast", name: "Nicholas Ferrar, Deacon",                              color: "white", life: "1637" },
  { month: 12, day: 12, rank: "lesser_feast", name: "Francis de Sales, Bishop, and Jane de Chantal, Vowed Religious", color: "white", life: "1622 and 1641" },
  { month: 12, day: 13, rank: "lesser_feast", name: "Lucy of Syracuse, Martyr",                             color: "red",   life: "304" },
  { month: 12, day: 14, rank: "lesser_feast", name: "John of the Cross, Mystic and Monastic Reformer",      color: "white", life: "1591" },
  { month: 12, day: 15, rank: "lesser_feast", name: "Nino of Georgia, Missionary",                          color: "white", life: "c. 332" },
  { month: 12, day: 17, rank: "lesser_feast", name: "Dorothy L. Sayers, Apologist and Spiritual Writer",    color: "white", life: "1957" },
  { month: 12, day: 20, rank: "lesser_feast", name: "Katharina von Bora, Church Reformer",                  color: "white", life: "1552" },
  { month: 12, day: 29, rank: "lesser_feast", name: "Thomas Becket, Archbishop of Canterbury and Martyr",   color: "red",   life: "1170" },
  { month: 12, day: 31, rank: "lesser_feast", name: "Frances Joseph Gaudet, Educator and Social Reformer",  color: "white", life: "1934" },
];

registerLesserFeasts(ENTRIES);
