import { useEffect, useState } from "react";
import { useLocation, useSearch } from "wouter";
import { YouTubePlayer } from "@/components/YouTubePlayer";
import { isInReaderWatch, YOUTUBE_ID } from "@/lib/videoEmbed";
import { logListenNow } from "@/lib/logListenNow";
import { hymnTextFor } from "@/lib/hymnTexts";

// ── /video — one YouTube video, inside Phoebe ───────────────────────────────
//
// Owner, 2026-09-18: "Can it open the YouTube links for hymns and such in app
// like we were building for other things?" · then, on the first version:
// "Work on this ui" · "Edit the top title and such" · "it can just log it it
// doesn't need to go to the log page".
//
// The generic sibling of /ncmp/watch and /devotion/watch. Callers build the
// link with lib/videoEmbed's videoPath() and never link here by hand, because
// YouTube only starts on a page with a real http(s) ORIGIN:
//   - the web and the Android shell (https://localhost) embed right here;
//   - the iOS shell (capacitor://) gets Error 153, so the caller opens THIS
//     page at withphoebe.app in the in-app reader instead (openVideoInReader),
//     marked ?inapp=1, where the reader's own Done replaces our Back.
// See memory reference_video_embedding for the whole table.
//
// THE TITLE BLOCK reads like a record sleeve, not a sentence: the hymn number
// small above, the hymn's NAME as the title, who sings it small below. The
// first version set the whole log string ("Hymn 6, 7 · Christ whose glory
// fills the skies — Thomas Armstrong, The Choir of …") in large serif, which
// is what the owner was looking at when they said "work on this ui".
//
// BACK on the left, DONE on the right (owner, 2026-09-19). Done logs the
// listening — silently, since the "Logged to your listening" line under the
// video is gone at the owner's word — and carries on into Audio Divina's deck
// at its CLOSING PROMPT, the lift beat ("Take a moment to lift to God…"), via
// /listening?lift=1. Logging is idempotent (lib/logListenNow writes once per
// title per day), so Done after an automatic log adds nothing.
//
// IN THE iOS READER neither control can do its job: the reader is a separate
// web view, with its own storage, no sign-in and no way to move the app behind
// it. So this page renders no chrome there — the reader supplies its own Done
// — and the app lands on the lift beat when the reader CLOSES, through the
// note the caller left in lib/afterReader. The log there happens in the app
// before the reader opens (`logged=1`).
//
// THE WORDS, beneath the video, only for a hymn whose text is verifiably
// public domain (lib/hymnTexts, generated by scripts/fetch-hymn-texts.py with
// the rule in its header). Owner: "have the lyrics" · "in space grotesk". A
// hymn whose words are under copyright, or merely might be, shows none.
//
// `v` must be a bare YouTube id (11 characters of [A-Za-z0-9_-]), so this page
// can never be handed an arbitrary embed; `from` accepts in-app paths only.

const FONT = "'Space Grotesk', system-ui, sans-serif";
const WARM = "#F0EDE6";
const SAGE = "#8FAF96";
const FAINT = "rgba(143,175,150,0.6)";

export default function VideoWatchPage() {
  const [, setLocation] = useLocation();
  const params = new URLSearchParams(useSearch());
  const raw = params.get("v") ?? "";
  const id = YOUTUBE_ID.test(raw) ? raw : null;
  const title = params.get("title");
  const eyebrow = params.get("eyebrow");
  const sub = params.get("sub");
  const logAs = params.get("logAs");
  const fromRaw = params.get("from");
  const from = fromRaw && fromRaw.startsWith("/") && !fromRaw.startsWith("//") ? fromRaw : "/listening";
  const inReader = isInReaderWatch();
  const words = hymnTextFor(params.get("hymn"));
  /**
   * THE READER'S OWN TITLE BAR reads document.title (owner, 2026-09-19: "The
   * top of that reader shouldn't say Phoebe it should be related to the
   * content"), and on iOS this page IS what the reader is showing. So it
   * names the track while it is open and hands the old title back on the way
   * out, for the app's other pages.
   */
  useEffect(() => {
    const name = [eyebrow, title].filter(Boolean).join(" · ");
    if (!name) return;
    const prior = document.title;
    document.title = name;
    return () => { document.title = prior; };
  }, [eyebrow, title]);

  const [leaving, setLeaving] = useState(false);
  /** Done: log it (once), then the deck's closing prompt. */
  const done = () => {
    if (leaving) return;
    setLeaving(true);
    if (logAs) logListenNow(logAs);
    setLocation("/listening?lift=1");
  };

  return (
    <div
      style={{
        minHeight: "var(--app-dvh)",
        background: "#091A10",
        color: WARM,
        fontFamily: FONT,
        display: "flex",
        flexDirection: "column",
      }}
    >
      <header
        style={{
          paddingTop: "max(1.25rem, calc(var(--safe-top) + 0.5rem))",
          paddingLeft: 20,
          paddingRight: 20,
          paddingBottom: 6,
          minHeight: 20,
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          gap: 12,
        }}
      >
        {inReader ? null : (
          <>
            <button
              type="button"
              onClick={() => setLocation(from)}
              style={{ background: "none", border: "none", color: SAGE, fontFamily: FONT, fontSize: 13, cursor: "pointer", padding: 0 }}
            >
              ← Back
            </button>
            <button
              type="button"
              onClick={done}
              style={{
                background: "rgba(46,107,64,0.42)", border: "1px solid rgba(143,175,150,0.45)",
                color: WARM, fontFamily: FONT, fontSize: 13, fontWeight: 600,
                borderRadius: 999, padding: "8px 18px", cursor: "pointer",
              }}
            >
              Done
            </button>
          </>
        )}
      </header>

      <main style={{ flex: 1, padding: "10px 16px 32px", display: "flex", flexDirection: "column", gap: 18 }}>
        {(title || eyebrow || sub) && (
          <div style={{ width: "100%", maxWidth: 560, alignSelf: "center", padding: "0 4px", display: "flex", flexDirection: "column", gap: 5 }}>
            {eyebrow && (
              <span style={{ color: FAINT, fontSize: 11, fontWeight: 600, letterSpacing: "0.16em", textTransform: "uppercase" }}>
                {eyebrow}
              </span>
            )}
            {title && (
              <h1 style={{ margin: 0, color: WARM, fontFamily: FONT, fontSize: 24, fontWeight: 600, lineHeight: 1.22, letterSpacing: "-0.01em" }}>
                {title}
              </h1>
            )}
            {sub && (
              <span style={{ color: FAINT, fontSize: 12.5, lineHeight: 1.45 }}>
                {sub}
              </span>
            )}
          </div>
        )}

        {/* Edge to edge (owner: "have the video be full width"): the course
            page's own .video-bleed, which steps a child out of the column's
            padding using var(--app-vw) — not 100vw, which Android's web zoom
            makes a different number (d2322451) — plus the player's frameless
            "bleed" so no border or corner fights it. */}
        {id ? (
          <div className="video-bleed">
            <YouTubePlayer videoId={id} autoplay frame="bleed" onEnded={() => {}} />
          </div>
        ) : (
          <p style={{ color: FAINT, fontSize: 14, textAlign: "center", marginTop: 40 }}>
            This video could not be found.
          </p>
        )}

        {words && (
          <section
            aria-label="Words"
            style={{
              width: "100%", maxWidth: 560, alignSelf: "center", boxSizing: "border-box",
              marginTop: 10, padding: "22px 20px 18px", borderRadius: 16,
              background: "rgba(240,237,230,0.04)", border: "1px solid rgba(46,107,64,0.35)",
            }}
          >
            <p style={{ margin: "0 0 16px", color: FAINT, fontSize: 11, fontWeight: 600, letterSpacing: "0.16em", textTransform: "uppercase" }}>
              Words
            </p>
            {/* The refrain once, after the first stanza, where a hymnal
                prints it; later stanzas are sung into it. */}
            {words.stanzas.map((st, i) => (
              <div key={i}>
                <div style={{ display: "flex", gap: 12, marginBottom: 18 }}>
                  <span aria-hidden style={{ flex: "0 0 auto", width: 14, color: FAINT, fontSize: 12, lineHeight: "24px", textAlign: "right", fontVariantNumeric: "tabular-nums" }}>
                    {i + 1}
                  </span>
                  <p style={{ margin: 0, color: WARM, fontFamily: FONT, fontSize: 15.5, lineHeight: "24px", whiteSpace: "pre-line" }}>
                    {st}
                  </p>
                </div>
                {i === 0 && words.refrain && (
                  <div style={{ display: "flex", gap: 12, marginBottom: 18 }}>
                    <span aria-hidden style={{ flex: "0 0 auto", width: 14 }} />
                    <div>
                      <p style={{ margin: "0 0 4px", color: FAINT, fontSize: 10.5, fontWeight: 600, letterSpacing: "0.14em", textTransform: "uppercase" }}>
                        Refrain
                      </p>
                      <p style={{ margin: 0, color: SAGE, fontFamily: FONT, fontSize: 15.5, lineHeight: "24px", whiteSpace: "pre-line" }}>
                        {words.refrain}
                      </p>
                    </div>
                  </div>
                )}
              </div>
            ))}
            <p style={{ margin: "6px 0 0", color: FAINT, fontSize: 11.5, lineHeight: 1.5 }}>
              {words.credit.replace(/^Author: /, "Words: ")} · Public domain
            </p>
          </section>
        )}
      </main>
    </div>
  );
}
