export type BcpPrayer = {
  category: string;
  title: string;
  text: string;
  // Spanish (Libro de Oración Común). Optional so the file stays
  // valid while we incrementally add translations; `localizeBcpPrayer`
  // falls back to English when these are missing. Eventually every
  // prayer should ship with an ES translation.
  titleEs?: string;
  textEs?: string;
};

// English category → Spanish category. Categories are used as the
// grouping key in `bcp-intercessions.tsx`, so we keep the English
// string as the key and look up the display label here.
export const BCP_CATEGORY_ES: Record<string, string> = {
  "For the Church": "Por la Iglesia",
  "For the Mission of the Church": "Por la Misión de la Iglesia",
  "For the Nation": "Por la Nación",
  "For the World": "Por el Mundo",
  "For the Natural Order": "Por el Orden Natural",
  "For Cities and Towns": "Por las Ciudades y Pueblos",
  "For Vocation and Work": "Por la Vocación y el Trabajo",
  "For the Poor and Neglected": "Por los Pobres y los Olvidados",
  "For the Sick": "Por los Enfermos",
  "For the Sorrowing": "Por los Afligidos",
  "For Those in Need": "Por los Necesitados",
  "For Social Justice": "Por la Justicia Social",
  "For the Environment": "Por el Medio Ambiente",
  "Personal Prayers": "Oraciones Personales",
  "For Families": "Por las Familias",
  "Thanksgivings": "Acciones de Gracias",
};

export const BCP_PRAYERS: BcpPrayer[] = [
  // FOR THE CHURCH
  { category: "For the Church", title: "For the Universal Church",
    text: "O God of unchangeable power and eternal light: Look favorably on your whole Church, that wonderful and sacred mystery; by the effectual working of your providence, carry out in tranquillity the plan of salvation; let the whole world see and know that things which were cast down are being raised up, and things which had grown old are being made new, and that all things are being brought to their perfection by him through whom all things were made, your Son Jesus Christ our Lord. Amen.",
    titleEs: "Por la Iglesia Universal",
    textEs: "Oh Dios de poder inmutable y luz eterna: Mira con favor a toda tu Iglesia, ese maravilloso y sagrado misterio; por la obra eficaz de tu providencia, lleva a cabo con tranquilidad el plan de la salvación; haz que el mundo entero vea y conozca que las cosas que habían sido derribadas están siendo levantadas, y las que habían envejecido están siendo hechas nuevas, y que todas las cosas están siendo conducidas a su perfección por aquel mediante quien todas fueron hechas, tu Hijo Jesucristo nuestro Señor. Amén." },
  { category: "For the Church", title: "For a Church Convention or Meeting",
    text: "Almighty and everlasting God, who by the Holy Spirit presided over the council of the blessed Apostles, and has promised, through your Son Jesus Christ, to be present wherever two or three are gathered together in his Name: Grant that as we meet together in your Name, so we may be bound together by your Spirit, and find our decisions to be the expression of your will; through Jesus Christ our Lord. Amen.",
    titleEs: "Por una Convención o Reunión de la Iglesia",
    textEs: "Dios omnipotente y eterno, que por el Espíritu Santo presidiste el concilio de los bienaventurados Apóstoles, y has prometido, por medio de tu Hijo Jesucristo, estar presente dondequiera que dos o tres se reúnan en su Nombre: Concede que, al reunirnos en tu Nombre, seamos unidos por tu Espíritu, y que nuestras decisiones sean expresión de tu voluntad; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Church", title: "For the Unity of the Church",
    text: "O God the Father of our Lord Jesus Christ, our only Savior, the Prince of Peace: Give us grace seriously to lay to heart the great dangers we are in by our unhappy divisions; take away all hatred and prejudice, and whatever else may hinder us from godly union and concord; that, as there is but one Body and one Spirit, one hope of our calling, one Lord, one Faith, one Baptism, one God and Father of us all, so we may be all of one heart and of one soul, united in one holy bond of truth and peace, of faith and charity, and may with one mind and one mouth glorify thee; through Jesus Christ our Lord. Amen.",
    titleEs: "Por la Unidad de la Iglesia",
    textEs: "Oh Dios Padre de nuestro Señor Jesucristo, nuestro único Salvador, Príncipe de Paz: Danos gracia para tomar seriamente a pecho los grandes peligros en que estamos por nuestras infelices divisiones; aparta de nosotros todo odio y prejuicio, y todo lo demás que pueda impedirnos la unión y la concordia santas; que, así como no hay sino un solo Cuerpo y un solo Espíritu, una sola esperanza de nuestra vocación, un solo Señor, una sola Fe, un solo Bautismo, un solo Dios y Padre de todos nosotros, así seamos todos de un solo corazón y de una sola alma, unidos en un santo lazo de verdad y paz, de fe y caridad, y podamos glorificarte con una sola mente y una sola voz; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Church", title: "For the Church's Ministry",
    text: "O God, you led your holy apostles to ordain ministers in every place: Grant that your Church, under the guidance of the Holy Spirit, may choose suitable persons for the ministry of Word and Sacrament, and may uphold them in their work for the extension of your kingdom; through him who is the Shepherd and Bishop of our souls, Jesus Christ our Lord, who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.",
    titleEs: "Por el Ministerio de la Iglesia",
    textEs: "Oh Dios, tú guiaste a tus santos apóstoles a ordenar ministros en cada lugar: Concede que tu Iglesia, bajo la guía del Espíritu Santo, escoja personas idóneas para el ministerio de la Palabra y los Sacramentos, y las sostenga en su labor para la extensión de tu reino; por aquel que es el Pastor y Obispo de nuestras almas, Jesucristo nuestro Señor, que vive y reina contigo y el Espíritu Santo, un solo Dios, por los siglos de los siglos. Amén." },
  { category: "For the Church", title: "For the Election of a Bishop or other Minister",
    text: "Almighty God, giver of every good gift: Look graciously on your Church, and so guide the minds of those who shall choose a bishop for this diocese (or, a rector for this parish), that we may receive a faithful pastor, who will care for your people and equip us for our ministries; through Jesus Christ our Lord. Amen.",
    titleEs: "Por la Elección de un Obispo u otro Ministro",
    textEs: "Dios omnipotente, dador de todo don perfecto: Mira con benevolencia a tu Iglesia, y guía las mentes de quienes han de elegir un obispo para esta diócesis (o, un rector para esta parroquia), para que recibamos un pastor fiel, que cuide de tu pueblo y nos capacite para nuestros ministerios; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Church", title: "For the Consecration of a Church",
    text: "O Eternal God, mighty in power and of incomprehensible majesty, whom the heaven of heavens cannot contain, much less the walls of temples made with hands; graciously accept the dedication of this place to your honor and glory, through Jesus Christ our Lord. Amen.",
    titleEs: "Por la Consagración de una Iglesia",
    textEs: "Oh Dios eterno, poderoso en fuerza y de incomprensible majestad, a quien el cielo de los cielos no puede contener, mucho menos los muros de templos hechos por manos humanas: Acepta con bondad la dedicación de este lugar a tu honor y gloria, por Jesucristo nuestro Señor. Amén." },
  { category: "For the Church", title: "For a Church or Mission",
    text: "Everliving God, whose will it is that all should come to you through your Son Jesus Christ: Inspire our witness to him, that all may know the power of his forgiveness and the hope of his resurrection; who lives and reigns with you and the Holy Spirit, one God, now and for ever. Amen.",
    titleEs: "Por una Iglesia o Misión",
    textEs: "Dios viviente, cuya voluntad es que todos vengan a ti por tu Hijo Jesucristo: Inspira nuestro testimonio de él, para que todos conozcan el poder de su perdón y la esperanza de su resurrección; que vive y reina contigo y el Espíritu Santo, un solo Dios, ahora y por siempre. Amén." },
  { category: "For the Church", title: "For a Vestry or other Governing Body",
    text: "O Eternal God, the fountain of all wisdom: Enlighten with your grace the vestry of this parish, and all who bear authority in your Church, that they may seek above all things your honor and glory; strengthen them to bear their burdens well; and grant that with willing hearts they may devote their powers to your service, and to the welfare of your people; through Jesus Christ our Lord. Amen.",
    titleEs: "Por una Junta Parroquial u Otro Cuerpo Directivo",
    textEs: "Oh Dios eterno, fuente de toda sabiduría: Ilumina con tu gracia a la junta parroquial de esta parroquia, y a todos los que ejercen autoridad en tu Iglesia, para que busquen ante todo tu honor y gloria; fortalécelos para llevar bien sus cargas; y concede que con corazón dispuesto consagren sus facultades a tu servicio y al bienestar de tu pueblo; por Jesucristo nuestro Señor. Amén." },

  // FOR THE MISSION OF THE CHURCH
  { category: "For the Mission of the Church", title: "For the Spread of the Gospel",
    text: "O God of all nations of the earth: Remember the multitudes who have been created in your image but have not known the redeeming work of our Savior Jesus Christ; and grant that, by the prayers and labors of your holy Church, they may be brought to know and worship you as you have been revealed in your Son; who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.",
    titleEs: "Por la Difusión del Evangelio",
    textEs: "Oh Dios de todas las naciones de la tierra: Recuerda a las multitudes que han sido creadas a tu imagen pero no han conocido la obra redentora de nuestro Salvador Jesucristo; y concede que, por las oraciones y labores de tu santa Iglesia, lleguen a conocerte y adorarte tal como te has revelado en tu Hijo; que vive y reina contigo y el Espíritu Santo, un solo Dios, por los siglos de los siglos. Amén." },
  { category: "For the Mission of the Church", title: "For the Mission of the Church",
    text: "Everliving God, whose will it is that all people should come to you through your Son Jesus Christ: Inspire our witness to him, that all may know the power of his forgiveness and the hope of his resurrection; who lives and reigns with you and the Holy Spirit, one God, now and for ever. Amen.",
    titleEs: "Por la Misión de la Iglesia",
    textEs: "Dios viviente, cuya voluntad es que todas las personas vengan a ti por tu Hijo Jesucristo: Inspira nuestro testimonio de él, para que todos conozcan el poder de su perdón y la esperanza de su resurrección; que vive y reina contigo y el Espíritu Santo, un solo Dios, ahora y por siempre. Amén." },
  { category: "For the Mission of the Church", title: "For Missionaries",
    text: "Almighty and everlasting God, who alone works great marvels: Send down upon all missionaries and the congregations committed to their care the healthful Spirit of your grace; and, that they may truly please you, pour upon them the continual dew of your blessing. Grant this, O Lord, for the honor of our Advocate and Mediator, Jesus Christ. Amen.",
    titleEs: "Por los Misioneros",
    textEs: "Dios omnipotente y eterno, único que obras grandes maravillas: Envía sobre todos los misioneros y las congregaciones encomendadas a su cuidado el saludable Espíritu de tu gracia; y, para que verdaderamente te agraden, derrama sobre ellos el continuo rocío de tu bendición. Concédelo, Señor, por el honor de nuestro Abogado y Mediador, Jesucristo. Amén." },
  { category: "For the Mission of the Church", title: "For our Enemies",
    text: "O God, the Father of all, whose Son commanded us to love our enemies: Lead them and us from prejudice to truth; deliver them and us from hatred, cruelty, and revenge; and in your good time enable us all to stand reconciled before you; through Jesus Christ our Lord. Amen.",
    titleEs: "Por Nuestros Enemigos",
    textEs: "Oh Dios, Padre de todos, cuyo Hijo nos mandó amar a nuestros enemigos: Guíalos a ellos y a nosotros del prejuicio a la verdad; líbralos y líbranos del odio, la crueldad y la venganza; y en tu buen tiempo capacítanos a todos para presentarnos reconciliados ante ti; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Mission of the Church", title: "For Those Who Suffer for the Faith",
    text: "O God of all the prophets, you have always sent messengers who were rejected and persecuted: Grant to all who suffer for the sake of the gospel the grace to persevere, endurance for the trial, and hope in the resurrection; through Jesus Christ our Lord, who suffered and was glorified. Amen.",
    titleEs: "Por los que Sufren por la Fe",
    textEs: "Oh Dios de todos los profetas, que siempre has enviado mensajeros que fueron rechazados y perseguidos: Concede a todos los que sufren a causa del evangelio la gracia para perseverar, la fortaleza en la prueba y la esperanza en la resurrección; por Jesucristo nuestro Señor, que padeció y fue glorificado. Amén." },

  // FOR THE NATION
  { category: "For the Nation", title: "For Our Country",
    text: "Almighty God, who has given us this good land as our heritage: We humbly ask that we may always prove ourselves a people mindful of your favor and glad to do your will. Bless our land with honorable industry, sound learning, and pure manners. Save us from violence, discord, and confusion; from pride and arrogance, and from every evil way. In the time of prosperity, fill our hearts with thankfulness, and in the day of trouble, suffer not our trust in you to fail. Amen.",
    titleEs: "Por Nuestra Patria",
    textEs: "Dios omnipotente, que nos has dado esta buena tierra por herencia: Humildemente te pedimos que siempre nos mostremos como un pueblo consciente de tu favor y dispuesto a hacer tu voluntad. Bendice nuestra tierra con industria honrada, sólida instrucción y costumbres puras. Líbranos de la violencia, la discordia y la confusión; del orgullo y la arrogancia, y de todo mal camino. En tiempo de prosperidad, llena nuestros corazones de gratitud; y en tiempo de adversidad, no permitas que falle nuestra confianza en ti. Amén." },
  { category: "For the Nation", title: "For the President and all in Civil Authority",
    text: "O Lord our Governor, whose glory is in all the world: We commend this nation to your merciful care, that, being guided by your Providence, we may dwell secure in your peace. Grant to the President of the United States, the Governor of this State, and to all in authority, wisdom and strength to know and to do your will. Fill them with the love of truth and righteousness, and make them ever mindful of their calling to serve this people in your fear; through Jesus Christ our Lord, who lives and reigns with you and the Holy Spirit, one God, world without end. Amen.",
    titleEs: "Por el Presidente y todas las Autoridades Civiles",
    textEs: "Oh Señor nuestro Gobernador, cuya gloria está en todo el mundo: Encomendamos esta nación a tu misericordioso cuidado, para que, guiados por tu Providencia, habitemos seguros en tu paz. Concede al Presidente de los Estados Unidos, al Gobernador de este Estado, y a todos los que ejercen autoridad, sabiduría y fortaleza para conocer y hacer tu voluntad. Llénalos del amor a la verdad y a la justicia, y hazlos siempre conscientes de su vocación de servir a este pueblo en tu temor; por Jesucristo nuestro Señor, que vive y reina contigo y el Espíritu Santo, un solo Dios, por los siglos de los siglos. Amén." },
  { category: "For the Nation", title: "For Congress or a State Legislature",
    text: "O God, the fountain of wisdom, whose will is good and gracious, and whose law is truth: We beseech you so to guide and bless our Legislature (or the Congress of the United States), that it may ordain for our governance only such things as please you, to the glory of your Name and the welfare of this people; through Jesus Christ our Lord. Amen.",
    titleEs: "Por el Congreso o una Legislatura Estatal",
    textEs: "Oh Dios, fuente de sabiduría, cuya voluntad es buena y benigna, y cuya ley es verdad: Te suplicamos que de tal manera guíes y bendigas a nuestra Legislatura (o al Congreso de los Estados Unidos), que ordene para nuestro gobierno solamente lo que te agrade, para la gloria de tu Nombre y el bienestar de este pueblo; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Nation", title: "For Courts of Justice",
    text: "Almighty God, who sittest in the throne judging right: We humbly beseech you to bless the courts of justice and the magistrates in all this land; and give unto them the spirit of wisdom and understanding, that they may discern the truth, and impartially administer the law in the fear of you alone; through him who shall come to be our Judge, your Son our Savior Jesus Christ. Amen.",
    titleEs: "Por los Tribunales de Justicia",
    textEs: "Dios omnipotente, que te sientas en el trono juzgando con rectitud: Humildemente te suplicamos que bendigas los tribunales de justicia y a los magistrados en toda esta tierra; y dales el espíritu de sabiduría y entendimiento, para que puedan discernir la verdad y administrar imparcialmente la ley en el temor de ti solo; por aquel que ha de venir a ser nuestro Juez, tu Hijo nuestro Salvador Jesucristo. Amén." },
  { category: "For the Nation", title: "For Sound Government",
    text: "O Lord our Governor, bless the leaders of our land, that we may be a people at peace among ourselves and a blessing to other nations of the earth. Lord, keep this nation under your care. To all who have executive authority and to all who have administrative authority, grant wisdom and grace in the exercise of their duties. Give grace to your servants to put away all envy, hatred, and malice; and grant that they lead us in ways of justice, peace, and love; through Jesus Christ our Lord. Amen.",
    titleEs: "Por un Buen Gobierno",
    textEs: "Oh Señor nuestro Gobernador, bendice a los líderes de nuestra tierra, para que seamos un pueblo en paz entre nosotros mismos y una bendición para las demás naciones de la tierra. Señor, mantén esta nación bajo tu cuidado. A todos los que tienen autoridad ejecutiva y a todos los que tienen autoridad administrativa, concédeles sabiduría y gracia en el ejercicio de sus deberes. Da gracia a tus siervos para apartar toda envidia, odio y malicia; y concede que nos guíen por caminos de justicia, paz y amor; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Nation", title: "For an Election",
    text: "Almighty God, to whom we must account for all our powers and privileges: Guide the people of the United States in the election of officials and representatives; that, by faithful administration and wise laws, the rights of all may be protected and our nation be enabled to fulfill your purposes; through Jesus Christ our Lord. Amen.",
    titleEs: "Por una Elección",
    textEs: "Dios omnipotente, a quien debemos rendir cuenta de todos nuestros poderes y privilegios: Guía al pueblo de los Estados Unidos en la elección de funcionarios y representantes; para que, mediante una administración fiel y leyes sabias, sean protegidos los derechos de todos y nuestra nación pueda cumplir tus propósitos; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Nation", title: "For those in the Armed Forces",
    text: "Almighty God, we commend to your gracious care and keeping all the men and women of our armed forces at home and abroad. Defend them day by day with your heavenly grace; strengthen them in their trials and temptations; give them courage to face the perils which beset them; and grant them a sense of your abiding presence wherever they may be; through Jesus Christ our Lord. Amen.",
    titleEs: "Por los Miembros de las Fuerzas Armadas",
    textEs: "Dios omnipotente, encomendamos a tu bondadoso cuidado y protección a todos los hombres y mujeres de nuestras fuerzas armadas, en la patria y en el extranjero. Defiéndelos día tras día con tu gracia celestial; fortalécelos en sus pruebas y tentaciones; dales valor para afrontar los peligros que los acechan; y concédeles un sentido de tu presencia permanente dondequiera que se encuentren; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Nation", title: "For Veterans",
    text: "Lord God of hosts, we give you thanks for the courage and sacrifice of all who have served this nation in time of need. We remember before you those who bear the wounds of war, seen and unseen; grant them healing, wholeness, and peace. Strengthen those who care for them, and give wisdom to all who shape the ways we honor and support those who have served; through Jesus Christ our Lord. Amen.",
    titleEs: "Por los Veteranos",
    textEs: "Señor Dios de los ejércitos, te damos gracias por el valor y el sacrificio de todos los que han servido a esta nación en tiempos de necesidad. Recordamos delante de ti a quienes llevan las heridas de la guerra, visibles e invisibles; concédeles sanación, plenitud y paz. Fortalece a quienes los cuidan, y da sabiduría a todos los que dan forma a las maneras en que honramos y apoyamos a los que han servido; por Jesucristo nuestro Señor. Amén." },

  // FOR THE WORLD
  { category: "For the World", title: "For Peace Among Nations",
    text: "Almighty God, our heavenly Father, guide the nations of the world into the way of justice and truth, and establish among them that peace which is the fruit of righteousness, that they may become the kingdom of our Lord and Savior Jesus Christ. Amen.",
    titleEs: "Por la Paz entre las Naciones",
    textEs: "Dios omnipotente, Padre celestial nuestro, guía a las naciones del mundo por el camino de la justicia y la verdad, y establece entre ellas esa paz que es fruto de la justicia, para que lleguen a ser el reino de nuestro Señor y Salvador Jesucristo. Amén." },
  { category: "For the World", title: "For Peace",
    text: "Eternal God, in whose perfect kingdom no sword is drawn but the sword of righteousness, no strength known but the strength of love: So mightily spread abroad your Spirit, that all peoples may be gathered under the banner of the Prince of Peace, as children of one Father; to whom be dominion and glory, now and for ever. Amen.",
    titleEs: "Por la Paz",
    textEs: "Dios eterno, en cuyo reino perfecto no se desenvaina otra espada sino la de la justicia, ni se conoce otra fuerza sino la fuerza del amor: Extiende con tal poder tu Espíritu, para que todos los pueblos sean reunidos bajo el estandarte del Príncipe de Paz, como hijos de un solo Padre; a quien sea el dominio y la gloria, ahora y por siempre. Amén." },
  { category: "For the World", title: "For the Human Family",
    text: "O God, you made us in your own image and redeemed us through Jesus your Son: Look with compassion on the whole human family; take away the arrogance and hatred which infect our hearts; break down the walls that separate us; unite us in bonds of love; and work through our struggle and confusion to accomplish your purposes on earth; that, in your good time, all nations and races may serve you in harmony around your heavenly throne; through Jesus Christ our Lord. Amen.",
    titleEs: "Por la Familia Humana",
    textEs: "Oh Dios, tú nos hiciste a tu propia imagen y nos redimiste por medio de Jesús tu Hijo: Mira con compasión a toda la familia humana; aparta la arrogancia y el odio que infectan nuestros corazones; derriba los muros que nos separan; únenos en lazos de amor; y obra a través de nuestra lucha y confusión para cumplir tus propósitos en la tierra; para que, en tu buen tiempo, todas las naciones y razas te sirvan en armonía alrededor de tu trono celestial; por Jesucristo nuestro Señor. Amén." },
  { category: "For the World", title: "In Times of Conflict",
    text: "O God, you have bound us together in a common life. Help us, in the midst of our struggles for justice and truth, to confront one another without hatred or bitterness, and to work together with mutual forbearance and respect; through Jesus Christ our Lord. Amen.",
    titleEs: "En Tiempos de Conflicto",
    textEs: "Oh Dios, tú nos has unido en una vida común. Ayúdanos, en medio de nuestras luchas por la justicia y la verdad, a enfrentarnos los unos a los otros sin odio ni amargura, y a trabajar juntos con mutua tolerancia y respeto; por Jesucristo nuestro Señor. Amén." },

  // FOR THE NATURAL ORDER
  { category: "For the Natural Order", title: "For the Conservation of Natural Resources",
    text: "Almighty God, in giving us dominion over things on earth, you made us fellow workers in your creation: Give us wisdom and reverence so to use the resources of nature, that no one may suffer from our abuse of them, and that generations yet to come may continue to praise you for your bounty; through Jesus Christ our Lord. Amen.",
    titleEs: "Por la Conservación de los Recursos Naturales",
    textEs: "Dios omnipotente, al darnos dominio sobre las cosas de la tierra, nos hiciste colaboradores en tu creación: Danos sabiduría y reverencia para usar los recursos de la naturaleza, de modo que nadie sufra por nuestro abuso de ellos, y que las generaciones venideras continúen alabándote por tu generosidad; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Natural Order", title: "For the Harvest of Lands and Waters",
    text: "O gracious Father, who opens your hand and fills all living things: Bless the lands and waters, and multiply the harvests of the world; let your Spirit go forth, that it may renew the face of the earth; show your loving-kindness, that our land may give her increase; and save us from selfish use of what you give, that men and women everywhere may give you thanks; through Christ our Lord. Amen.",
    titleEs: "Por la Cosecha de las Tierras y las Aguas",
    textEs: "Oh Padre bondadoso, que abres tu mano y llenas todo ser viviente: Bendice las tierras y las aguas, y multiplica las cosechas del mundo; envía tu Espíritu, para que renueve la faz de la tierra; muestra tu amorosa bondad, para que nuestra tierra dé su fruto; y líbranos del uso egoísta de lo que nos das, para que hombres y mujeres en todas partes te den gracias; por Cristo nuestro Señor. Amén." },
  { category: "For the Natural Order", title: "For the Future of the Human Race",
    text: "O God our heavenly Father, you have blessed us and given us dominion over all the earth: Increase our reverence before the mystery of life; and give us new insight into your purposes for the human race, and for the world you have made, that we may preserve what you have entrusted to us; through Jesus Christ our Lord. Amen.",
    titleEs: "Por el Futuro de la Raza Humana",
    textEs: "Oh Dios Padre celestial nuestro, tú nos has bendecido y dado dominio sobre toda la tierra: Aumenta nuestra reverencia ante el misterio de la vida; y danos nueva comprensión de tus propósitos para la raza humana y para el mundo que has hecho, para que podamos conservar lo que nos has confiado; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Natural Order", title: "For Fruitful Seasons",
    text: "Almighty God, Lord of heaven and earth: We humbly pray that your gracious providence may give and preserve to our use the harvests of the land and of the seas, and may prosper all who labor to gather them, that we, who are constantly receiving good things from your hand, may always give you thanks; through Jesus Christ our Lord, who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.",
    titleEs: "Por Estaciones Fructíferas",
    textEs: "Dios omnipotente, Señor del cielo y de la tierra: Humildemente te rogamos que tu bondadosa providencia nos dé y preserve para nuestro uso las cosechas de la tierra y de los mares, y prospere a todos los que trabajan para recogerlas, para que nosotros, que constantemente recibimos bienes de tu mano, te demos siempre gracias; por Jesucristo nuestro Señor, que vive y reina contigo y el Espíritu Santo, un solo Dios, por los siglos de los siglos. Amén." },
  { category: "For the Natural Order", title: "For Rain",
    text: "O God, heavenly Father, who by your Son Jesus Christ has promised to all who seek your kingdom and its righteousness all things necessary to sustain their life: Send us, we entreat you, in this time of need, such moderate rain and showers, that we may receive the fruits of the earth to our comfort and to your honor; through Jesus Christ our Lord. Amen.",
    titleEs: "Por la Lluvia",
    textEs: "Oh Dios, Padre celestial, que por medio de tu Hijo Jesucristo has prometido a todos los que buscan tu reino y su justicia todas las cosas necesarias para sostener su vida: Envíanos, te suplicamos, en este tiempo de necesidad, una lluvia y aguaceros moderados, para que recibamos los frutos de la tierra para nuestro consuelo y para tu honor; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Natural Order", title: "In Times of Drought",
    text: "O Almighty God, who of your great mercy have promised, through your Son, to give all necessary things to those who seek your kingdom: Grant that the dry and thirsty land may again receive your blessing in plentiful rain; through Jesus Christ our Lord. Amen.",
    titleEs: "En Tiempos de Sequía",
    textEs: "Oh Dios omnipotente, que por tu gran misericordia has prometido, por medio de tu Hijo, dar todas las cosas necesarias a quienes buscan tu reino: Concede que la tierra seca y sedienta reciba nuevamente tu bendición en abundante lluvia; por Jesucristo nuestro Señor. Amén." },

  // FOR CITIES AND TOWNS
  { category: "For Cities and Towns", title: "For Cities",
    text: "Heavenly Father, in your Word you have given us a vision of that holy City to which the nations of the world bring their glory: Behold and visit, we pray, the cities of the earth. Renew the ties of mutual regard which form our civic life. Send us honest and able leaders. Enable us to eliminate poverty, prejudice, and oppression, that peace may prevail with righteousness, and justice with order, and that men and women from different cultures and with differing talents may find with one another the fulfillment of their humanity; through Jesus Christ our Lord. Amen.",
    titleEs: "Por las Ciudades",
    textEs: "Padre celestial, en tu Palabra nos has dado una visión de aquella santa Ciudad a la que las naciones del mundo traen su gloria: Mira y visita, te rogamos, las ciudades de la tierra. Renueva los lazos de mutuo aprecio que conforman nuestra vida cívica. Envíanos líderes honestos y capaces. Capacítanos para eliminar la pobreza, el prejuicio y la opresión, para que prevalezca la paz con la justicia, y el orden con la equidad, y para que hombres y mujeres de diversas culturas y con diferentes talentos hallen entre sí la plenitud de su humanidad; por Jesucristo nuestro Señor. Amén." },
  { category: "For Cities and Towns", title: "For Towns and Rural Areas",
    text: "Lord Christ, when you came among us, you proclaimed the kingdom of God in villages, towns, and lonely places: Grant that your presence and power may be known throughout this land. Have mercy upon all of us who live and work in rural areas; and grant that all the people of our nation may give thanks to you for food and drink and all other bodily necessities of life, respect those who labor to produce them, and honor the land and the water from which these good things come. All this we ask in your holy Name. Amen.",
    titleEs: "Por los Pueblos y las Zonas Rurales",
    textEs: "Señor Cristo, cuando viniste entre nosotros, proclamaste el reino de Dios en aldeas, pueblos y lugares apartados: Concede que tu presencia y tu poder sean conocidos en toda esta tierra. Ten misericordia de todos los que vivimos y trabajamos en zonas rurales; y concede que todo el pueblo de nuestra nación pueda darte gracias por el alimento, la bebida y todas las demás necesidades corporales de la vida, respete a quienes trabajan para producirlos, y honre la tierra y el agua de donde proceden estos bienes. Todo esto te lo pedimos en tu santo Nombre. Amén." },
  { category: "For Cities and Towns", title: "For the Right Use of God's Gifts",
    text: "Almighty God, whose loving hand has given us all that we possess: Grant us grace that we may honor you with our substance, and, remembering the account which we must one day give, may be faithful stewards of your bounty; through Jesus Christ our Lord. Amen.",
    titleEs: "Por el Buen Uso de los Dones de Dios",
    textEs: "Dios omnipotente, cuya mano amorosa nos ha dado todo lo que poseemos: Concédenos gracia para que te honremos con nuestros bienes, y, recordando la cuenta que un día hemos de dar, seamos fieles administradores de tu generosidad; por Jesucristo nuestro Señor. Amén." },

  // FOR VOCATION AND WORK
  { category: "For Vocation and Work", title: "For Those Who Work",
    text: "Almighty God, you have made us and all things to serve you: Bless all whose lives are spent in honest labor, and grant that, doing what we do in your Name, we may find joy in work done faithfully; through Jesus Christ our Lord. Amen.",
    titleEs: "Por los que Trabajan",
    textEs: "Dios omnipotente, tú nos has creado a nosotros y a todas las cosas para servirte: Bendice a todos los que pasan su vida en trabajo honrado, y concede que, haciendo lo que hacemos en tu Nombre, hallemos gozo en el trabajo hecho con fidelidad; por Jesucristo nuestro Señor. Amén." },
  { category: "For Vocation and Work", title: "For Commerce and Industry",
    text: "Almighty God, whose Son Jesus Christ in his earthly life shared our toil and hallowed our labor: Be present with your people where they work; make those who carry on the industries and commerce of this land responsive to your will; and give to us all a pride in what we do, and a just return for our labor; through Jesus Christ our Lord, who lives and reigns with you, in the unity of the Holy Spirit, one God, now and for ever. Amen.",
    titleEs: "Por el Comercio y la Industria",
    textEs: "Dios omnipotente, cuyo Hijo Jesucristo en su vida terrena compartió nuestra fatiga y santificó nuestro trabajo: Está presente con tu pueblo en su lugar de trabajo; haz que quienes dirigen las industrias y el comercio de esta tierra respondan a tu voluntad; y danos a todos orgullo en lo que hacemos, y una justa retribución por nuestro trabajo; por Jesucristo nuestro Señor, que vive y reina contigo, en la unidad del Espíritu Santo, un solo Dios, ahora y por siempre. Amén." },

  // FOR THE POOR AND NEGLECTED
  { category: "For the Poor and Neglected", title: "For the Poor and Neglected",
    text: "Almighty and most merciful God, we remember before you all poor and neglected persons whom it would be easy for us to forget: the homeless and the destitute, the old and the sick, and all who have none to care for them. Help us to heal those who are broken in body or spirit, and to turn their sorrow into joy. Grant this, Father, for the love of your Son, who for our sake became poor, Jesus Christ our Lord. Amen.",
    titleEs: "Por los Pobres y los Olvidados",
    textEs: "Dios omnipotente y misericordiosísimo, recordamos delante de ti a todas las personas pobres y olvidadas a quienes fácilmente podríamos pasar por alto: los desamparados y los indigentes, los ancianos y los enfermos, y todos los que no tienen quien los cuide. Ayúdanos a sanar a los que están quebrantados en cuerpo o espíritu, y a convertir su tristeza en gozo. Concédelo, Padre, por el amor de tu Hijo, que por nuestro bien se hizo pobre, Jesucristo nuestro Señor. Amén." },
  { category: "For the Poor and Neglected", title: "For the Unemployed",
    text: "Heavenly Father, we remember before you those who suffer want and anxiety from lack of work. Guide the people of this land so to use our public and private wealth that all may find suitable and fulfilling employment, and receive just payment for their labor; through Jesus Christ our Lord. Amen.",
    titleEs: "Por los Desempleados",
    textEs: "Padre celestial, recordamos delante de ti a quienes sufren necesidad y ansiedad por falta de trabajo. Guía al pueblo de esta tierra a usar nuestra riqueza pública y privada de tal manera que todos puedan encontrar un empleo adecuado y satisfactorio, y recibir una justa retribución por su trabajo; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Poor and Neglected", title: "For Schools and Colleges",
    text: "O Eternal God: Bless all schools, colleges, and universities, that they may be lively centers for sound learning, new discovery, and the pursuit of wisdom; and grant that those who teach and those who learn may find you to be the source of all truth; through Jesus Christ our Lord. Amen.",
    titleEs: "Por las Escuelas y Universidades",
    textEs: "Oh Dios eterno: Bendice todas las escuelas, institutos y universidades, para que sean centros vivos de sólida instrucción, nuevos descubrimientos y búsqueda de la sabiduría; y concede que quienes enseñan y quienes aprenden te encuentren como la fuente de toda verdad; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Poor and Neglected", title: "For those who Influence Public Opinion",
    text: "Almighty God, you proclaim your truth in every age by many voices: Direct, in our time, we pray, those who speak where many listen and write what many read; that they may do their part in making the heart of this people wise, its mind sound, and its will righteous; to the honor of Jesus Christ our Lord. Amen.",
    titleEs: "Por los que Influyen en la Opinión Pública",
    textEs: "Dios omnipotente, tú proclamas tu verdad en cada época por medio de muchas voces: Dirige, en nuestro tiempo, te rogamos, a quienes hablan donde muchos escuchan y escriben lo que muchos leen; para que cumplan su parte en hacer sabio el corazón de este pueblo, sana su mente y justa su voluntad; para honor de Jesucristo nuestro Señor. Amén." },

  // FOR THE SICK
  { category: "For the Sick", title: "For the Sick (general)",
    text: "Heavenly Father, giver of life and health: Comfort and relieve your sick servants, and give your power of healing to those who minister to their needs, that those for whom our prayers are offered may be strengthened in their weakness and have confidence in your loving care; through Jesus Christ our Lord, who lives and reigns with you and the Holy Spirit, one God, now and for ever. Amen.",
    titleEs: "Por los Enfermos (general)",
    textEs: "Padre celestial, dador de vida y de salud: Consuela y alivia a tus siervos enfermos, y da tu poder de sanación a los que atienden sus necesidades, para que aquellos por quienes ofrecemos nuestras oraciones sean fortalecidos en su debilidad y tengan confianza en tu cuidado amoroso; por Jesucristo nuestro Señor, que vive y reina contigo y el Espíritu Santo, un solo Dios, ahora y por siempre. Amén." },
  { category: "For the Sick", title: "For a Sick Person",
    text: "O Father of mercies and God of all comfort, our only help in time of need: We humbly beseech you to behold, visit, and relieve your sick servant for whom our prayers are desired. Look upon them with the eyes of your mercy; comfort them with a sense of your goodness; preserve them from the temptations of the enemy; and give them patience under their affliction. In your good time, restore them to health, and enable them to lead the residue of their life in your fear, and to your glory; and grant that finally they may dwell with you in life everlasting; through Jesus Christ our Lord. Amen.",
    titleEs: "Por una Persona Enferma",
    textEs: "Oh Padre de misericordias y Dios de todo consuelo, nuestro único auxilio en tiempo de necesidad: Humildemente te suplicamos que mires, visites y alivies a tu siervo enfermo por quien se desean nuestras oraciones. Míralo con los ojos de tu misericordia; consuélalo con un sentido de tu bondad; presérvalo de las tentaciones del enemigo; y dale paciencia en su aflicción. En tu buen tiempo, restáuralo a la salud, y capacítalo para vivir el resto de sus días en tu temor y para tu gloria; y concede que finalmente habite contigo en la vida eterna; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Sick", title: "For Recovery from Sickness",
    text: "O God, the strength of the weak and the comfort of sufferers: Mercifully accept our prayers, and grant to your servant the help of your power, that their sickness may be turned into health, and our sorrow into joy; through Jesus Christ our Lord. Amen.",
    titleEs: "Por la Recuperación de una Enfermedad",
    textEs: "Oh Dios, fuerza de los débiles y consuelo de los que sufren: Acepta misericordiosamente nuestras oraciones, y concede a tu siervo el auxilio de tu poder, para que su enfermedad se torne en salud, y nuestra tristeza en gozo; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Sick", title: "For Health of Body and Soul",
    text: "May God the Father bless you, God the Son heal you, God the Holy Spirit give you strength. May God the holy and undivided Trinity guard your body, save your soul, and bring you safely to his heavenly country; where he lives and reigns for ever and ever. Amen.",
    titleEs: "Por la Salud del Cuerpo y del Alma",
    textEs: "Que Dios Padre te bendiga, Dios Hijo te sane, Dios Espíritu Santo te dé fortaleza. Que Dios, la santa e indivisa Trinidad, guarde tu cuerpo, salve tu alma y te lleve salvo a su patria celestial; donde vive y reina por los siglos de los siglos. Amén." },
  { category: "For the Sick", title: "For Strength and Confidence",
    text: "Heavenly Father, giver of life and health: Grant to all the sick and suffering such a sense of your presence, that their minds may be made easy, and their hearts at rest; through Jesus Christ our Lord. Amen.",
    titleEs: "Por Fortaleza y Confianza",
    textEs: "Padre celestial, dador de vida y de salud: Concede a todos los enfermos y a los que sufren tal sentido de tu presencia, que sus mentes sean serenadas y sus corazones queden en reposo; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Sick", title: "For the Dying",
    text: "Almighty God, look on this your servant, lying in great weakness, and comfort him with the promise of life everlasting, given in the resurrection of your Son Jesus Christ our Lord. Amen.",
    titleEs: "Por los Moribundos",
    textEs: "Dios omnipotente, mira a este siervo tuyo, postrado en gran debilidad, y consuélalo con la promesa de vida eterna, dada en la resurrección de tu Hijo Jesucristo nuestro Señor. Amén." },

  // FOR THE SORROWING
  { category: "For the Sorrowing", title: "Comfort and Relief",
    text: "O merciful Father, who has taught us in your holy Word that you do not willingly afflict or grieve the children of men: Look with pity upon the sorrows of your servants for whom our prayers are offered. Remember them, O Lord, in mercy; nourish their souls with patience; comfort them with a sense of your goodness; lift up your countenance upon them; and give them peace; through Jesus Christ our Lord. Amen.",
    titleEs: "Consuelo y Alivio",
    textEs: "Oh Padre misericordioso, que nos has enseñado en tu santa Palabra que no afliges ni entristeces de buena gana a los hijos de los hombres: Mira con compasión las penas de tus siervos por quienes se ofrecen nuestras oraciones. Acuérdate de ellos, Señor, en tu misericordia; nutre sus almas con paciencia; consuélalos con un sentido de tu bondad; alza tu rostro sobre ellos; y dales paz; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Sorrowing", title: "For the Bereaved",
    text: "Almighty God, Father of mercies and giver of comfort: Deal graciously, we pray, with all who mourn; that, casting every care on you, they may know the consolation of your love; through Jesus Christ our Lord. Amen.",
    titleEs: "Por los que están de Duelo",
    textEs: "Dios omnipotente, Padre de misericordias y dador de consuelo: Trata con benevolencia, te rogamos, a todos los que lloran; para que, echando toda preocupación sobre ti, conozcan el consuelo de tu amor; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Sorrowing", title: "For the Victims of Addiction",
    text: "O blessed Lord, you ministered to all who came to you: Look with compassion upon all who through addiction have lost their health and freedom. Restore to them the assurance of your unfailing mercy; remove from them the fears that beset them; strengthen them in the work of their recovery; and to those who care for them, give patient understanding and persevering love; through Jesus Christ our Lord. Amen.",
    titleEs: "Por las Víctimas de la Adicción",
    textEs: "Oh bendito Señor, tú ministraste a todos los que venían a ti: Mira con compasión a todos los que por causa de la adicción han perdido la salud y la libertad. Restáurales la certeza de tu inagotable misericordia; quita de ellos los temores que los acosan; fortalécelos en su labor de recuperación; y a los que los cuidan, dales paciente comprensión y amor perseverante; por Jesucristo nuestro Señor. Amén." },
  { category: "For the Sorrowing", title: "For those who Mourn",
    text: "O Lord, you are the comforter of those who weep: Be close to all whose hearts are heavy with grief. Grant that, finding in you a present help in trouble, they may have strength for this day, hope for tomorrow, and peace within; through Jesus Christ our Lord. Amen.",
    titleEs: "Por los que Lloran",
    textEs: "Oh Señor, tú eres el consolador de los que lloran: Acércate a todos cuyos corazones están agobiados por el duelo. Concede que, hallando en ti un auxilio siempre presente en la tribulación, tengan fuerza para este día, esperanza para el mañana y paz interior; por Jesucristo nuestro Señor. Amén." },

  // FOR THOSE IN NEED
  { category: "For Those in Need", title: "For an Anxious Person",
    text: "O God of peace, who has taught us that in returning and rest we shall be saved, in quietness and in confidence shall be our strength: By the might of your Spirit lift us, we pray, to your presence, where we may be still and know that you are God; through Jesus Christ our Lord. Amen.",
    titleEs: "Por una Persona Angustiada",
    textEs: "Oh Dios de paz, que nos has enseñado que en quietud y en confianza está nuestra fortaleza, y que volviendo y reposando seremos salvos: Por el poder de tu Espíritu, elévanos, te rogamos, a tu presencia, donde podamos estar quietos y conocer que tú eres Dios; por Jesucristo nuestro Señor. Amén." },
  { category: "For Those in Need", title: "For those who are Homeless",
    text: "Almighty and most merciful God, we remember before you all poor and neglected persons: the homeless and the destitute, the old and the sick, and all who have none to care for them. Help us to heal those who are broken in body or spirit, and to turn their sorrow into joy. Grant this, Father, for the love of your Son, who for our sake became poor, Jesus Christ our Lord. Amen.",
    titleEs: "Por los Desamparados",
    textEs: "Dios omnipotente y misericordiosísimo, recordamos delante de ti a todas las personas pobres y olvidadas: los desamparados y los indigentes, los ancianos y los enfermos, y todos los que no tienen quien los cuide. Ayúdanos a sanar a los que están quebrantados en cuerpo o espíritu, y a tornar su tristeza en gozo. Concédelo, Padre, por el amor de tu Hijo, que por nuestro bien se hizo pobre, Jesucristo nuestro Señor. Amén." },
  { category: "For Those in Need", title: "For those in Prison",
    text: "Lord Jesus, for our sake you were condemned as a criminal: Visit our jails and prisons with your pity and judgment. Remember all prisoners, and bring the guilty to repentance and amendment of life according to your will, and give them hope for their future. When any are held unjustly, bring them release; forgive us, and teach us to improve our justice. Remember those who work in these institutions; keep them humane and compassionate; and save them from becoming brutal or callous. And since what we do for those in prison, O Lord, we do for you, constrain us to improve their lot. All this we ask for your mercy's sake. Amen.",
    titleEs: "Por los que están en Prisión",
    textEs: "Señor Jesús, por nuestro bien fuiste condenado como criminal: Visita nuestras cárceles y prisiones con tu compasión y tu juicio. Acuérdate de todos los presos, y conduce a los culpables al arrepentimiento y a la enmienda de vida según tu voluntad, y dales esperanza para su futuro. Cuando alguno esté detenido injustamente, concédele libertad; perdónanos, y enséñanos a mejorar nuestra justicia. Acuérdate de quienes trabajan en estas instituciones; consérvalos humanos y compasivos, y líbralos de hacerse brutales o insensibles. Y, ya que lo que hacemos por los que están en prisión, Señor, lo hacemos por ti, oblíganos a mejorar su suerte. Todo esto te lo pedimos por tu misericordia. Amén." },
  { category: "For Those in Need", title: "For those we Love",
    text: "O gracious Father, we humbly ask for your gentle care for the person we pray for now. Keep them ever in your love; teach them to love you with all their heart, with all their soul, with all their mind, and with all their strength; and, loving you, to love also all whom you love; through Jesus Christ our Lord. Amen.",
    titleEs: "Por los que Amamos",
    textEs: "Oh Padre bondadoso, humildemente te pedimos tu tierno cuidado por la persona por quien oramos ahora. Mantenla siempre en tu amor; enséñale a amarte con todo su corazón, con toda su alma, con toda su mente y con todas sus fuerzas; y, amándote, a amar también a todos los que tú amas; por Jesucristo nuestro Señor. Amén." },
  { category: "For Those in Need", title: "For Travelers",
    text: "O God, our heavenly Father, whose glory fills the whole creation, and whose presence we find wherever we go: Preserve those who travel; surround them with your loving care; protect them from every danger; and bring them in safety to their journey's end; through Jesus Christ our Lord. Amen.",
    titleEs: "Por los Viajeros",
    textEs: "Oh Dios, Padre celestial nuestro, cuya gloria llena toda la creación, y cuya presencia hallamos dondequiera que vamos: Preserva a los que viajan; rodéalos de tu cuidado amoroso; protégelos de todo peligro; y llévalos a salvo al término de su viaje; por Jesucristo nuestro Señor. Amén." },

  // FOR SOCIAL JUSTICE
  { category: "For Social Justice", title: "For Social Justice",
    text: "Grant, O God, that your holy and life-giving Spirit may so move every human heart, and especially the hearts of the people of this land, that barriers which divide us may crumble, suspicions disappear, and hatreds cease; that our divisions being healed, we may live in justice and peace; through Jesus Christ our Lord. Amen.",
    titleEs: "Por la Justicia Social",
    textEs: "Concede, oh Dios, que tu santo y vivificador Espíritu mueva de tal manera todo corazón humano, y especialmente los corazones del pueblo de esta tierra, que se derrumben las barreras que nos dividen, desaparezcan las sospechas y cesen los odios; para que, sanadas nuestras divisiones, vivamos en justicia y paz; por Jesucristo nuestro Señor. Amén." },
  { category: "For Social Justice", title: "For the Poor and Oppressed",
    text: "O God, who created all peoples in your image, we thank you for the wonderful diversity of races and cultures in this world. Take away all things which make us afraid of one another; help us to know that we are all your children; and enable us to grow in brotherhood and sisterhood; through your Son, Jesus Christ our Lord. Amen.",
    titleEs: "Por los Pobres y Oprimidos",
    textEs: "Oh Dios, que creaste a todos los pueblos a tu imagen, te damos gracias por la maravillosa diversidad de razas y culturas en este mundo. Aparta todo aquello que nos hace temer los unos a los otros; ayúdanos a reconocer que todos somos hijos tuyos; y capacítanos para crecer en hermandad; por tu Hijo, Jesucristo nuestro Señor. Amén." },
  { category: "For Social Justice", title: "For Young Persons",
    text: "God our Father, you see your children growing up in an unsteady and confusing world: Show them that your ways give more life than the ways of the world, and that following you is better than chasing after selfish goals. Help them to take failure, not as a measure of their worth, but as a chance for a new start. Give them strength to hold their faith in you, and to keep alive their joy in your creation; through Jesus Christ our Lord. Amen.",
    titleEs: "Por los Jóvenes",
    textEs: "Dios Padre nuestro, tú ves a tus hijos crecer en un mundo inestable y confuso: Muéstrales que tus caminos dan más vida que los caminos del mundo, y que seguirte a ti es mejor que ir tras metas egoístas. Ayúdales a tomar el fracaso, no como medida de su valor, sino como ocasión para un nuevo comienzo. Dales fuerza para mantener su fe en ti, y para conservar viva su alegría en tu creación; por Jesucristo nuestro Señor. Amén." },
  { category: "For Social Justice", title: "For the Aged",
    text: "Look with mercy, O God our Father, on all whose increasing years bring them weakness, distress, or isolation. Provide for them homes of dignity and peace; give them understanding helpers, and the willingness to accept help; and, as their strength diminishes, increase their faith and their assurance of your love. This we ask in the name of Jesus Christ our Lord. Amen.",
    titleEs: "Por los Ancianos",
    textEs: "Mira con misericordia, oh Dios Padre nuestro, a todos aquellos a quienes el paso de los años les trae debilidad, angustia o soledad. Provéeles hogares de dignidad y paz; dales auxiliares comprensivos, y disposición para aceptar la ayuda; y, a medida que disminuyen sus fuerzas, aumenta su fe y la seguridad de tu amor. Esto te lo pedimos en el nombre de Jesucristo nuestro Señor. Amén." },

  // FOR THE ENVIRONMENT
  { category: "For the Environment", title: "For the Care of Creation",
    text: "We call on you, O God, for our home the earth, that we may be worthy of it. We call on you, O God, for the health of the earth so that we may live with gratitude in it. We call on you, O God, for those who share the earth, that we may live with reverence for it. We call on you, O God, for those who will inherit the earth, that we may leave it to them as a gift. Through Christ who came that we might have life. Amen.",
    titleEs: "Por el Cuidado de la Creación",
    textEs: "A ti clamamos, oh Dios, por nuestro hogar, la tierra, para que seamos dignos de ella. A ti clamamos, oh Dios, por la salud de la tierra, para que vivamos en ella con gratitud. A ti clamamos, oh Dios, por quienes comparten la tierra, para que vivamos con reverencia por ella. A ti clamamos, oh Dios, por quienes heredarán la tierra, para que se la dejemos como un don. Por Cristo, que vino para que tuviéramos vida. Amén." },
  { category: "For the Environment", title: "For Conservation of Natural Resources",
    text: "Almighty God, in giving us dominion over things on earth, you made us fellow workers in your creation: Give us wisdom and reverence so to use the resources of nature, that no one may suffer from our abuse of them, and that generations yet to come may continue to praise you for your bounty; through Jesus Christ our Lord. Amen.",
    titleEs: "Por la Conservación de los Recursos Naturales",
    textEs: "Dios omnipotente, al darnos dominio sobre las cosas de la tierra, nos hiciste colaboradores en tu creación: Danos sabiduría y reverencia para usar los recursos de la naturaleza, de modo que nadie sufra por nuestro abuso de ellos, y que las generaciones venideras continúen alabándote por tu generosidad; por Jesucristo nuestro Señor. Amén." },

  // PERSONAL PRAYERS
  { category: "Personal Prayers", title: "In the Morning",
    text: "Lord God, almighty and everlasting Father, you have brought us in safety to this new day: Preserve us with your mighty power, that we may not fall into sin, nor be overcome by adversity; and in all we do, direct us to the fulfilling of your purpose; through Jesus Christ our Lord. Amen.",
    titleEs: "Por la Mañana",
    textEs: "Señor Dios, Padre omnipotente y eterno, nos has traído a salvo a este nuevo día: Presérvanos con tu poder soberano, para que no caigamos en pecado, ni seamos vencidos por la adversidad; y en todo cuanto hagamos, dirígenos al cumplimiento de tu propósito; por Jesucristo nuestro Señor. Amén." },
  { category: "Personal Prayers", title: "In the Evening",
    text: "Lord Jesus, stay with us, for evening is at hand and the day is past; be our companion in the way, kindle our hearts, and awaken hope, that we may know you as you are revealed in Scripture and the breaking of bread. Grant this for the sake of your love. Amen.",
    titleEs: "Al Atardecer",
    textEs: "Señor Jesús, quédate con nosotros, porque cae la tarde y el día se ha pasado; sé nuestro compañero en el camino, enciende nuestros corazones y despierta nuestra esperanza, para que te conozcamos como te revelas en las Escrituras y al partir el pan. Concédelo por amor a tu amor. Amén." },
  { category: "Personal Prayers", title: "Before Sleep",
    text: "Be present, O merciful God, and protect us through the hours of this night, so that we who are wearied by the changes and chances of this life may rest in your eternal changelessness; through Jesus Christ our Lord. Amen.",
    titleEs: "Antes de Dormir",
    textEs: "Sé presente, oh Dios misericordioso, y protégenos durante las horas de esta noche, para que, fatigados por los cambios y los azares de esta vida, hallemos reposo en tu eterna inmutabilidad; por Jesucristo nuestro Señor. Amén." },
  { category: "Personal Prayers", title: "For Guidance",
    text: "Direct us, O Lord, in all our doings with your most gracious favor, and further us with your continual help; that in all our works begun, continued, and ended in you, we may glorify your holy Name, and finally, by your mercy, obtain everlasting life; through Jesus Christ our Lord. Amen.",
    titleEs: "Por Guía",
    textEs: "Dirígenos, oh Señor, en todo cuanto hacemos con tu bondadosísimo favor, y acompáñanos con tu auxilio continuo; para que en todas nuestras obras, comenzadas, continuadas y terminadas en ti, glorifiquemos tu santo Nombre, y al fin, por tu misericordia, alcancemos la vida eterna; por Jesucristo nuestro Señor. Amén." },
  { category: "Personal Prayers", title: "Grace at Meals",
    text: "Blessed are you, O Lord God, King of the Universe, for you give us food to sustain our lives and make our hearts glad; through Jesus Christ our Lord. Amen.",
    titleEs: "Acción de Gracias por los Alimentos",
    textEs: "Bendito eres, oh Señor Dios, Rey del Universo, porque nos das alimento para sostener nuestra vida y alegrar nuestros corazones; por Jesucristo nuestro Señor. Amén." },
  { category: "Personal Prayers", title: "For a Birthday",
    text: "O God, our times are in your hand: Look with favor, we pray, on your servant N. as he begins another year. Grant that he may grow in wisdom and grace, and strengthen his trust in your goodness all the days of his life; through Jesus Christ our Lord. Amen.",
    titleEs: "Por un Cumpleaños",
    textEs: "Oh Dios, nuestros tiempos están en tu mano: Mira con favor, te rogamos, a tu siervo N. al comenzar otro año. Concede que crezca en sabiduría y gracia, y fortalece su confianza en tu bondad todos los días de su vida; por Jesucristo nuestro Señor. Amén." },
  { category: "Personal Prayers", title: "On the Anniversary of a Marriage",
    text: "O God, you have so consecrated the covenant of marriage that in it is represented the spiritual unity between Christ and his Church: Send therefore your blessing upon these your servants, that they may so love, honor, and cherish each other in faithfulness and patience, in wisdom and true godliness, that their home may be a haven of blessing and peace; through Jesus Christ our Lord. Amen.",
    titleEs: "En el Aniversario de un Matrimonio",
    textEs: "Oh Dios, tú has consagrado de tal modo el pacto del matrimonio que en él se representa la unión espiritual entre Cristo y su Iglesia: Envía, pues, tu bendición sobre estos siervos tuyos, para que se amen, honren y aprecien mutuamente en fidelidad y paciencia, en sabiduría y verdadera piedad, de manera que su hogar sea refugio de bendición y paz; por Jesucristo nuestro Señor. Amén." },
  { category: "Personal Prayers", title: "Prayer of Saint Francis",
    text: "Lord, make us instruments of your peace. Where there is hatred, let us sow love; where there is injury, pardon; where there is discord, union; where there is doubt, faith; where there is despair, hope; where there is darkness, light; where there is sadness, joy. Grant that we may not so much seek to be consoled as to console; to be understood as to understand; to be loved as to love. For it is in giving that we receive; it is in pardoning that we are pardoned; and it is in dying that we are born to eternal life. Amen.",
    titleEs: "Oración de San Francisco",
    textEs: "Señor, haznos instrumentos de tu paz. Donde haya odio, sembremos amor; donde haya ofensa, perdón; donde haya discordia, unión; donde haya duda, fe; donde haya desesperación, esperanza; donde haya tinieblas, luz; donde haya tristeza, alegría. Concede que no busquemos tanto ser consolados como consolar; ser comprendidos, como comprender; ser amados, como amar. Porque es dando como recibimos; perdonando como somos perdonados; y muriendo como nacemos a la vida eterna. Amén." },

  // FOR FAMILIES
  { category: "For Families", title: "For Families",
    text: "Almighty God, our heavenly Father, who sets the solitary in families: We commend to your continual care the homes in which your people dwell. Put far from them, we beseech you, every root of bitterness, the desire of vainglory, and the pride of life. Fill them with faith, virtue, knowledge, temperance, patience, godliness. Knit together in constant affection those who, in holy wedlock, have been made one flesh. Turn the hearts of the parents to the children, and the hearts of the children to the parents; and so enkindle fervent charity among us all, that we may evermore be kindly affectioned one to another; through Jesus Christ our Lord. Amen.",
    titleEs: "Por las Familias",
    textEs: "Dios omnipotente, Padre celestial nuestro, que pones al solitario en familia: Encomendamos a tu cuidado constante los hogares en que mora tu pueblo. Aparta de ellos, te suplicamos, toda raíz de amargura, el deseo de vanagloria, y la soberbia de la vida. Llénalos de fe, virtud, conocimiento, templanza, paciencia y piedad. Une en constante afecto a los que en santo matrimonio han sido hechos una sola carne. Vuelve los corazones de los padres hacia los hijos, y los corazones de los hijos hacia los padres; y enciende tan ferviente caridad entre todos nosotros, que siempre nos amemos mutuamente con tierno afecto; por Jesucristo nuestro Señor. Amén." },
  { category: "For Families", title: "For the Care of Children",
    text: "Almighty God, heavenly Father, you have blessed us with the joy and care of children: Give us calm strength and patient wisdom as we bring them up, that we may teach them to love whatever is just and true and good, following the example of our Savior Jesus Christ. Amen.",
    titleEs: "Por el Cuidado de los Niños",
    textEs: "Dios omnipotente, Padre celestial, nos has bendecido con el gozo y el cuidado de los niños: Danos serena fortaleza y paciente sabiduría al criarlos, para que les enseñemos a amar todo lo que es justo, verdadero y bueno, siguiendo el ejemplo de nuestro Salvador Jesucristo. Amén." },
  { category: "For Families", title: "For those who are Alone",
    text: "Almighty God, whose Son had nowhere to lay his head: Grant that those who live alone may not be lonely in their solitude, but that, following in his steps, they may find fulfillment in loving you and their neighbors; through Jesus Christ our Lord. Amen.",
    titleEs: "Por los que Viven Solos",
    textEs: "Dios omnipotente, cuyo Hijo no tenía dónde reclinar la cabeza: Concede que quienes viven solos no se sientan solitarios en su soledad, sino que, siguiendo sus pasos, hallen plenitud amándote a ti y al prójimo; por Jesucristo nuestro Señor. Amén." },

  // THANKSGIVINGS — from the BCP "Prayers and Thanksgivings" section
  // (https://www.bcponline.org/Misc/Thanksgivings.html). Numbered 1–11 in
  // the prayer book, spanning General, Church, National Life, Social Order,
  // Natural Order, and Family and Personal Life.
  { category: "Thanksgivings", title: "A General Thanksgiving",
    text: "Accept, O Lord, our thanks and praise for all that you have done for us. We thank you for the splendor of the whole creation, for the beauty of this world, for the wonder of life, and for the mystery of love.\n\nWe thank you for the blessing of family and friends, and for the loving care which surrounds us on every side.\n\nWe thank you for setting us at tasks which demand our best efforts, and for leading us to accomplishments which satisfy and delight us.\n\nWe thank you also for those disappointments and failures that lead us to acknowledge our dependence on you alone.\n\nAbove all, we thank you for your Son Jesus Christ; for the truth of his Word and the example of his life; for his steadfast obedience, by which he overcame temptation; for his dying, through which he overcame death; and for his rising to life again, in which we are raised to the life of your kingdom.\n\nGrant us the gift of your Spirit, that we may know him and make him known; and through him, at all times and in all places, may give thanks to you in all things. Amen.",
    titleEs: "Acción de Gracias General",
    textEs: "Acepta, oh Señor, nuestra gratitud y alabanza por todo lo que has hecho por nosotros. Te damos gracias por el esplendor de toda la creación, por la belleza de este mundo, por el portento de la vida y por el misterio del amor.\n\nTe damos gracias por la bendición de la familia y los amigos, y por el cuidado amoroso que nos rodea por todos lados.\n\nTe damos gracias por encomendarnos tareas que exigen nuestro mejor esfuerzo, y por conducirnos a logros que nos satisfacen y deleitan.\n\nTambién te damos gracias por aquellos desengaños y fracasos que nos llevan a reconocer que dependemos de ti solamente.\n\nSobre todo, te damos gracias por tu Hijo Jesucristo; por la verdad de su Palabra y el ejemplo de su vida; por su firme obediencia, con la cual venció la tentación; por su muerte, mediante la cual venció a la muerte; y por su resurrección, en la cual somos resucitados a la vida de tu reino.\n\nConcédenos el don de tu Espíritu, para que lo conozcamos y lo demos a conocer; y por medio de él, en todo tiempo y en todo lugar, te demos gracias en todas las cosas. Amén." },
  { category: "Thanksgivings", title: "A Litany of Thanksgiving",
    text: "Let us give thanks to God our Father for all his gifts so freely bestowed upon us.\n\nFor the beauty and wonder of your creation, in earth and sky and sea,\nWe thank you, Lord.\n\nFor all that is gracious in the lives of men and women, revealing the image of Christ,\nWe thank you, Lord.\n\nFor our daily food and drink, our homes and families, and our friends,\nWe thank you, Lord.\n\nFor minds to think, and hearts to love, and hands to serve,\nWe thank you, Lord.\n\nFor health and strength to work, and leisure to rest and play,\nWe thank you, Lord.\n\nFor the brave and courageous, who are patient in suffering and faithful in adversity,\nWe thank you, Lord.\n\nFor all valiant seekers after truth, liberty, and justice,\nWe thank you, Lord.\n\nFor the communion of saints, in all times and places,\nWe thank you, Lord.\n\nAbove all, we give you thanks for the great mercies and promises given to us in Christ Jesus our Lord;\nTo him be praise and glory, with you, O Father, and the Holy Spirit, now and for ever. Amen.",
    titleEs: "Letanía de Acción de Gracias",
    textEs: "Demos gracias a Dios nuestro Padre por todos sus dones tan generosamente otorgados a nosotros.\n\nPor la belleza y portento de tu creación, en la tierra y en el cielo y en el mar,\nTe damos gracias, Señor.\n\nPor todo lo que es benigno en la vida de hombres y mujeres, que revela la imagen de Cristo,\nTe damos gracias, Señor.\n\nPor nuestro pan y bebida cotidianos, por nuestros hogares y familias, y por nuestros amigos,\nTe damos gracias, Señor.\n\nPor mentes para pensar, corazones para amar y manos para servir,\nTe damos gracias, Señor.\n\nPor la salud y la fuerza para trabajar, y por el tiempo libre para descansar y recrearnos,\nTe damos gracias, Señor.\n\nPor los valientes y esforzados, pacientes en el sufrimiento y fieles en la adversidad,\nTe damos gracias, Señor.\n\nPor todos los valientes buscadores de la verdad, la libertad y la justicia,\nTe damos gracias, Señor.\n\nPor la comunión de los santos, en todo tiempo y lugar,\nTe damos gracias, Señor.\n\nSobre todo, te damos gracias por las grandes misericordias y promesas dadas a nosotros en Cristo Jesús nuestro Señor;\nA él sea la alabanza y la gloria, contigo, oh Padre, y el Espíritu Santo, ahora y por siempre. Amén." },
  { category: "Thanksgivings", title: "For the Mission of the Church",
    text: "Almighty God, you sent your Son Jesus Christ to reconcile the world to yourself: We praise and bless you for those whom you have sent in the power of the Spirit to preach the Gospel to all nations. We thank you that in all parts of the earth a community of love has been gathered together by their prayers and labors, and that in every place your servants call upon your Name; for the kingdom and the power and the glory are yours for ever. Amen.",
    titleEs: "Por la Misión de la Iglesia",
    textEs: "Dios omnipotente, enviaste a tu Hijo Jesucristo para reconciliar al mundo contigo: Te alabamos y te bendecimos por aquellos a quienes has enviado en el poder del Espíritu para predicar el Evangelio a todas las naciones. Te damos gracias porque en todas partes de la tierra se ha congregado una comunidad de amor por sus oraciones y trabajos, y porque en todo lugar tus siervos invocan tu Nombre; porque tuyos son el reino, el poder y la gloria por los siglos. Amén." },
  { category: "Thanksgivings", title: "For the Saints and Faithful Departed",
    text: "We give thanks to you, O Lord our God, for all your servants and witnesses of time past: for Abraham, the father of believers, and Sarah his wife; for Moses, the lawgiver, and Aaron, the priest; for Miriam and Joshua, Deborah and Gideon, and Samuel with Hannah his mother; for Isaiah and all the prophets; for Mary, the mother of our Lord; for Peter and Paul and all the apostles; for Mary and Martha, and Mary Magdalene; for Stephen, the first martyr, and all the martyrs and saints in every age and in every land. In your mercy, O Lord our God, give us, as you gave to them, the hope of salvation and the promise of eternal life; through Jesus Christ our Lord, the first-born of many from the dead. Amen.",
    titleEs: "Por los Santos y Fieles Difuntos",
    textEs: "Te damos gracias, oh Señor Dios nuestro, por todos tus siervos y testigos del pasado: por Abraham, padre de los creyentes, y Sara su esposa; por Moisés, el legislador, y Aarón, el sacerdote; por Miriam y Josué, Débora y Gedeón, y Samuel con Ana su madre; por Isaías y todos los profetas; por María, la madre de nuestro Señor; por Pedro y Pablo y todos los apóstoles; por María y Marta, y María Magdalena; por Esteban, el primer mártir, y por todos los mártires y santos de todas las edades y de todas las tierras. En tu misericordia, oh Señor Dios nuestro, danos, como les diste a ellos, la esperanza de la salvación y la promesa de la vida eterna; por Jesucristo nuestro Señor, primogénito de muchos de entre los muertos. Amén." },
  { category: "Thanksgivings", title: "For the Nation",
    text: "Almighty God, giver of all good things:\nWe thank you for the natural majesty and beauty of this land. They restore us, though we often destroy them.\nHeal us.\n\nWe thank you for the great resources of this nation. They make us rich, though we often exploit them.\nForgive us.\n\nWe thank you for the men and women who have made this country strong. They are models for us, though we often fall short of them.\nInspire us.\n\nWe thank you for the torch of liberty which has been lit in this land. It has drawn people from every nation, though we have often hidden from its light.\nEnlighten us.\n\nWe thank you for the faith we have inherited in all its rich variety. It sustains our life, though we have been faithless again and again.\nRenew us.\n\nHelp us, O Lord, to finish the good work here begun. Strengthen our efforts to blot out ignorance and prejudice, and to abolish poverty and crime. And hasten the day when all our people, with many voices in one united chorus, will glorify your holy Name. Amen.",
    titleEs: "Por la Nación",
    textEs: "Dios omnipotente, dador de todo bien:\nTe damos gracias por la natural majestad y belleza de esta tierra. Nos restauran, aunque a menudo las destruimos.\nSánanos.\n\nTe damos gracias por los grandes recursos de esta nación. Nos enriquecen, aunque a menudo los explotamos.\nPerdónanos.\n\nTe damos gracias por los hombres y mujeres que han hecho fuerte a este país. Son modelos para nosotros, aunque con frecuencia no estamos a su altura.\nInspíranos.\n\nTe damos gracias por la antorcha de la libertad que ha sido encendida en esta tierra. Ha atraído a gente de todas las naciones, aunque a menudo nos hemos escondido de su luz.\nIlumínanos.\n\nTe damos gracias por la fe que hemos heredado en toda su rica variedad. Sustenta nuestra vida, aunque hemos sido infieles una y otra vez.\nRenuévanos.\n\nAyúdanos, oh Señor, a terminar la buena obra aquí comenzada. Fortalece nuestros esfuerzos para borrar la ignorancia y el prejuicio, y para abolir la pobreza y la criminalidad. Y apresura el día en que todo nuestro pueblo, con muchas voces en un solo coro unido, glorifique tu santo Nombre. Amén." },
  { category: "Thanksgivings", title: "For Heroic Service",
    text: "O Judge of the nations, we remember before you with grateful hearts the men and women of our country who in the day of decision ventured much for the liberties we now enjoy. Grant that we may not rest until all the people of this land share the benefits of true freedom and gladly accept its disciplines. This we ask in the Name of Jesus Christ our Lord. Amen.",
    titleEs: "Por el Servicio Heroico",
    textEs: "Oh Juez de las naciones, recordamos delante de ti con corazones agradecidos a los hombres y mujeres de nuestro país que en el día de la decisión arriesgaron mucho por las libertades de las que ahora gozamos. Concede que no descansemos hasta que todo el pueblo de esta tierra comparta los beneficios de la verdadera libertad y acepte de buena gana sus disciplinas. Esto te lo pedimos en el Nombre de Jesucristo nuestro Señor. Amén." },
  { category: "Thanksgivings", title: "For the Diversity of Races and Cultures",
    text: "O God, who created all peoples in your image, we thank you for the wonderful diversity of races and cultures in this world. Enrich our lives by ever-widening circles of fellowship, and show us your presence in those who differ most from us, until our knowledge of your love is made perfect in our love for all your children; through Jesus Christ our Lord. Amen.",
    titleEs: "Por la Diversidad de Razas y Culturas",
    textEs: "Oh Dios, que creaste a todos los pueblos a tu imagen, te damos gracias por la maravillosa diversidad de razas y culturas en este mundo. Enriquece nuestras vidas con círculos de comunión cada vez más amplios, y muéstranos tu presencia en quienes más difieren de nosotros, hasta que nuestro conocimiento de tu amor se perfeccione en nuestro amor por todos tus hijos; por Jesucristo nuestro Señor. Amén." },
  { category: "Thanksgivings", title: "For the Beauty of the Earth",
    text: "We give you thanks, most gracious God, for the beauty of earth and sky and sea; for the richness of mountains, plains, and rivers; for the songs of birds and the loveliness of flowers. We praise you for these good gifts, and pray that we may safeguard them for our posterity. Grant that we may continue to grow in our grateful enjoyment of your abundant creation, to the honor and glory of your Name, now and for ever. Amen.",
    titleEs: "Por la Belleza de la Tierra",
    textEs: "Te damos gracias, Dios bondadosísimo, por la belleza de la tierra, del cielo y del mar; por la riqueza de las montañas, las llanuras y los ríos; por los cantos de las aves y la hermosura de las flores. Te alabamos por estos buenos dones, y rogamos que sepamos preservarlos para la posteridad. Concede que sigamos creciendo en el agradecido disfrute de tu abundante creación, para honor y gloria de tu Nombre, ahora y por siempre. Amén." },
  { category: "Thanksgivings", title: "For the Harvest",
    text: "Most gracious God, by whose knowledge the depths are broken up and the clouds drop down the dew: We yield thee hearty thanks and praise for the return of seed time and harvest, for the increase of the ground and the gathering in of its fruits, and for all other blessings of thy merciful providence bestowed upon this nation and people. And, we beseech thee, give us a just sense of these great mercies, such as may appear in our lives by a humble, holy, and obedient walking before thee all our days; through Jesus Christ our Lord, to whom, with thee and the Holy Ghost be all glory and honor, world without end. Amen.",
    titleEs: "Por la Cosecha",
    textEs: "Bondadosísimo Dios, por cuyo conocimiento se rompen los abismos y las nubes destilan el rocío: Te damos gracias y alabanzas de corazón por el retorno del tiempo de la siembra y de la cosecha, por el crecimiento de la tierra y la recolección de sus frutos, y por todas las demás bendiciones de tu misericordiosa providencia otorgadas a esta nación y pueblo. Y te suplicamos que nos des un justo sentido de estas grandes misericordias, tal que se manifieste en nuestras vidas por un caminar humilde, santo y obediente delante de ti todos nuestros días; por Jesucristo nuestro Señor, a quien, contigo y el Espíritu Santo, sea toda la gloria y honor, por los siglos de los siglos. Amén." },
  { category: "Thanksgivings", title: "For the Gift of a Child",
    text: "Heavenly Father, you sent your own Son into this world. We thank you for the life of this child, N., entrusted to our care. Help us to remember that we are all your children, and so to love and nurture him, that he may attain to that full stature intended for him in your eternal kingdom; for the sake of your dear Son, Jesus Christ our Lord. Amen.",
    titleEs: "Por el Don de un Niño",
    textEs: "Padre celestial, enviaste a tu propio Hijo a este mundo. Te damos gracias por la vida de este niño, N., encomendado a nuestro cuidado. Ayúdanos a recordar que todos somos hijos tuyos, y a amarlo y criarlo de tal modo que alcance esa plena estatura que tienes prevista para él en tu reino eterno; por el amor de tu amado Hijo, Jesucristo nuestro Señor. Amén." },
  { category: "Thanksgivings", title: "For the Restoration of Health",
    text: "Almighty God and heavenly Father, we give thee humble thanks because thou hast been graciously pleased to deliver from his sickness thy servant N., in whose behalf we bless and praise thy Name. Grant, O gracious Father, that he, through thy help, may live in this world according to thy will, and also be partaker of everlasting glory in the life to come; through Jesus Christ our Lord. Amen.",
    titleEs: "Por la Restauración de la Salud",
    textEs: "Dios omnipotente y Padre celestial, te damos humildes gracias porque te has dignado liberar de su enfermedad a tu siervo N., en cuyo favor bendecimos y alabamos tu Nombre. Concede, oh Padre bondadoso, que él, con tu ayuda, viva en este mundo conforme a tu voluntad, y también participe de la gloria eterna en la vida venidera; por Jesucristo nuestro Señor. Amén." },
];

/** Look up a BCP prayer by title (case-insensitive, trimmed).
 * Matches against EITHER the English or Spanish title so saved prayer
 * references survive a user's locale switch.
 */
export function findBcpPrayer(topic: string): BcpPrayer | undefined {
  const needle = topic.trim().toLowerCase();
  return BCP_PRAYERS.find(
    (p) =>
      p.title.toLowerCase() === needle ||
      (p.titleEs ?? "").toLowerCase() === needle,
  );
}

/** Resolve a prayer's display fields for the active locale. Falls back
 * to the English text when the Spanish translation isn't filled in yet.
 */
export function localizeBcpPrayer(
  p: BcpPrayer,
  lang: string | undefined,
): { category: string; title: string; text: string } {
  if (lang?.startsWith("es")) {
    return {
      category: BCP_CATEGORY_ES[p.category] ?? p.category,
      title: p.titleEs || p.title,
      text: p.textEs || p.text,
    };
  }
  return { category: p.category, title: p.title, text: p.text };
}
