// ── A face for the day's commemoration ──────────────────────────────────────
//
// Owner, 2026-09-18: "look in WikiComons for pictures for everyone on the
// calender" and "if you find a picture for that person, put it on a slide
// after the heigriohpy".
//
// WHAT IS HELD HERE IS A LINK, a licence and a credit — never an image file.
// Every picture is served from Wikimedia Commons, and every one carries a
// licence that was CHECKED rather than assumed: the harvest asked Commons for
// each file's own licence metadata and kept only public-domain and Creative
// Commons files. Anything whose licence could not be read, or that turned out
// to live on Wikipedia rather than Commons (which is where non-free "fair
// use" images sit), was dropped rather than guessed at.
//
// HOW IT WAS BUILT, and why not by image search:
//   1. each commemoration was resolved to its WIKIPEDIA ARTICLE and that
//      article's own lead image — not a free-text image search. An article
//      about a saint is written about that saint; a search box is not.
//   2. every file was then checked against the Commons API for licence,
//      artist and file page.
//   3. finally the SUBJECT was checked: the article title had to share a
//      distinctive name token with the commemoration. That check earned its
//      place — "Fabian, Bishop and Martyr" had resolved to a photograph of a
//      footballer, "William White, Bishop" to a flag, and Barbara Clementine
//      Harris to Saint Peter. Six wrong subjects were dropped that way.
//      Five were kept by hand where the article is the same person under
//      another name (Antony of Egypt / Anthony the Great, Anskar / Ansgar,
//      Photini / the Samaritan woman, Simeon Bachos / the Ethiopian eunuch,
//      Kassiani / Kassia) — each noted at its row.
//
// COVERAGE IS 216 OF 277, and the gaps are honest rather than padded. Most of
// the missing are modern people whose only photographs are still in copyright,
// which is exactly the case where a wrong or unlicensed picture would be worse
// than none. A day with no picture simply shows no picture slide.
//
// THE URLS ARE THE API'S OWN, not ones we build. Wikimedia now rejects
// arbitrary thumbnail widths with a 400 ("use thumbnail sizes listed on
// w.wiki/GHai"), so a constructed /thumb/.../900px- link fails for EVERY file
// — verified, after a rewrite of mine broke all 216 and an HTTP check caught
// it before it shipped. Ask the imageinfo API for a width and use the
// `thumburl` it returns; where a file is already narrow enough the API
// returns the file itself, which is why some links are not /thumb/ ones. Those
// are small in practice (sampled: median 94 KB, largest 628 KB, none over 1 MB).
// Only the API's utm tracking parameters are stripped.
//
// Keyed "month-day", the same key the calendar and Forward Movement join on.

export type CommemorationPicture = {
  /** Commons thumbnail, ~900px wide. */
  img: string;
  /** The file's own page on Commons — where the licence and credit live. */
  page: string;
  /** The licence as Commons states it. */
  licence: string;
  /** Who made it, where Commons records one. */
  artist: string | null;
};

export const COMMEMORATION_PICTURES: Record<string, CommemorationPicture> = {
  "1-1": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dc/Madonna_Michelangelo_Bruges_-_JPG1.jpg/960px-Madonna_Michelangelo_Bruges_-_JPG1.jpg", page: "https://commons.wikimedia.org/wiki/File:Madonna_Michelangelo_Bruges_-_JPG1.jpg", licence: "CC BY 3.0", artist: "Jean-Pol GRANDMONT" },
  "1-4": { img: "https://upload.wikimedia.org/wikipedia/commons/8/83/Elizabeth_Ann_Seton_portrait_by_Amabilia_Filicchi.jpg", page: "https://commons.wikimedia.org/wiki/File:Elizabeth_Ann_Seton_portrait_by_Amabilia_Filicchi.jpg", licence: "Public domain", artist: "Amabilia Filicchi" },
  "1-5": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/70/James_Jacques_Joseph_Tissot_-_Abram%27s_Counsel_to_Sarai_-_Google_Art_Project_%28cropped%29.jpg/960px-James_Jacques_Joseph_Tissot_-_Abram%27s_Counsel_to_Sarai_-_Google_Art_Project_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:James_Jacques_Joseph_Tissot_-_Abram%27s_Counsel_to_Sarai_-_Google_Art_Project_(cropped).jpg", licence: "Public domain", artist: "James Jacques Joseph Tissot (1836 - 1902)  (French) Details on Google Art Project" },
  "1-6": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Edward_Burne-Jones_-_The_Adoration_of_the_Magi_-_Google_Art_Project.jpg/960px-Edward_Burne-Jones_-_The_Adoration_of_the_Magi_-_Google_Art_Project.jpg", page: "https://commons.wikimedia.org/wiki/File:Edward_Burne-Jones_-_The_Adoration_of_the_Magi_-_Google_Art_Project.jpg", licence: "Public domain", artist: "Edward Burne-Jones" },
  "1-8": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Deaconess_Bedell_with_medicine_man_and_Bobby_Jim_Tiger_outside_the_mission.jpg/960px-Deaconess_Bedell_with_medicine_man_and_Bobby_Jim_Tiger_outside_the_mission.jpg", page: "https://commons.wikimedia.org/wiki/File:Deaconess_Bedell_with_medicine_man_and_Bobby_Jim_Tiger_outside_the_mission.jpg", licence: "Public domain", artist: "Florida Memory" },
  "1-9": { img: "https://upload.wikimedia.org/wikipedia/commons/2/29/Julia_Chester_Emery_c._1876.png", page: "https://commons.wikimedia.org/wiki/File:Julia_Chester_Emery_c._1876.png", licence: "Public domain", artist: "Dorothy Emery Lufford" },
  "1-10": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/William_Laud.jpg/960px-William_Laud.jpg", page: "https://commons.wikimedia.org/wiki/File:William_Laud.jpg", licence: "Public domain", artist: "After Anthony van Dyck" },
  "1-12": { img: "https://upload.wikimedia.org/wikipedia/commons/c/cb/De_Speculo_Caritatis.jpeg", page: "https://commons.wikimedia.org/wiki/File:De_Speculo_Caritatis.jpeg", licence: "Public domain", artist: "Elredo de Rieval, posiblemente" },
  "1-13": { img: "https://upload.wikimedia.org/wikipedia/commons/1/18/Hilaryofpoitiers.jpg", page: "https://commons.wikimedia.org/wiki/File:Hilaryofpoitiers.jpg", licence: "Public domain", artist: "Richard de Montbaston et collaborateurs." },
  "1-14": { img: "https://upload.wikimedia.org/wikipedia/commons/1/13/Rev._Richard_Meux_Benson.jpg", page: "https://commons.wikimedia.org/wiki/File:Rev._Richard_Meux_Benson.jpg", licence: "Public domain", artist: "S. L. Ollard" },
  // Anthony the Great is Antony of Egypt
  "1-17": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Saint_Anthony_%28Damaskinos%29.png/960px-Saint_Anthony_%28Damaskinos%29.png", page: "https://commons.wikimedia.org/wiki/File:Saint_Anthony_(Damaskinos).png", licence: "Public domain", artist: "Michael Damaskinos" },
  "1-18": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/da/Baldaquin_Bernin_Saint-Pierre_Vatican.jpg/960px-Baldaquin_Bernin_Saint-Pierre_Vatican.jpg", page: "https://commons.wikimedia.org/wiki/File:Baldaquin_Bernin_Saint-Pierre_Vatican.jpg", licence: "CC0", artist: "Jebulon" },
  "1-19": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/St_John_in_Bed_stained_glass_2.jpg/960px-St_John_in_Bed_stained_glass_2.jpg", page: "https://commons.wikimedia.org/wiki/File:St_John_in_Bed_stained_glass_2.jpg", licence: "CC BY-SA 4.0", artist: "Medarduss" },
  "1-22": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/Vicente_de_Zaragoza_by_Tom%C3%A1s_Giner%2C_1462%E2%80%931466.jpg/960px-Vicente_de_Zaragoza_by_Tom%C3%A1s_Giner%2C_1462%E2%80%931466.jpg", page: "https://commons.wikimedia.org/wiki/File:Vicente_de_Zaragoza_by_Tom%C3%A1s_Giner,_1462%E2%80%931466.jpg", licence: "Public domain", artist: "Tomás Giner" },
  "1-23": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/Phillips_Brooks.jpg/960px-Phillips_Brooks.jpg", page: "https://commons.wikimedia.org/wiki/File:Phillips_Brooks.jpg", licence: "Public domain", artist: "unattributed" },
  "1-27": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Johnchrysostom.jpg/960px-Johnchrysostom.jpg", page: "https://commons.wikimedia.org/wiki/File:Johnchrysostom.jpg", licence: "Public domain", artist: null },
  "1-28": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/St-thomas-aquinasFXD.jpg/960px-St-thomas-aquinasFXD.jpg", page: "https://commons.wikimedia.org/wiki/File:St-thomas-aquinasFXD.jpg", licence: "Public domain", artist: "Carlo Crivelli" },
  "1-31": { img: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Marcella_of_Rome.jpg", page: "https://commons.wikimedia.org/wiki/File:Marcella_of_Rome.jpg", licence: "Public domain", artist: "Diodore Rahoult" },
  "2-1": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Cong_St._Mary_of_the_Rosary_Window_St._Brigid_Detail_St._Brigid_holding_her_Lamp_II_2019_09_04.jpg/960px-Cong_St._Mary_of_the_Rosary_Window_St._Brigid_Detail_St._Brigid_holding_her_Lamp_II_2019_09_04.jpg", page: "https://commons.wikimedia.org/wiki/File:Cong_St._Mary_of_the_Rosary_Window_St._Brigid_Detail_St._Brigid_holding_her_Lamp_II_2019_09_04.jpg", licence: "CC BY-SA 4.0", artist: "Andreas F. Borchert" },
  // Ansgar is Anskar
  "2-3": { img: "https://upload.wikimedia.org/wikipedia/commons/5/52/Bendixen_Ansgar.jpg", page: "https://commons.wikimedia.org/wiki/File:Bendixen_Ansgar.jpg", licence: "Public domain", artist: "Siegfried Detlev Bendixen / After Hans Bornemann" },
  "2-4": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/da/WestminsterAbbey-Martyrs.jpg/960px-WestminsterAbbey-Martyrs.jpg", page: "https://commons.wikimedia.org/wiki/File:WestminsterAbbey-Martyrs.jpg", licence: "CC BY 2.5", artist: "Jean-Christophe BENOIST" },
  "2-5": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/Sant%27agata%2C_VII-inizio_VIII_secolo_ca.%2C_forse_da_s.m._antiqua_%28roma%2C_coll._priv.%29.jpg/960px-Sant%27agata%2C_VII-inizio_VIII_secolo_ca.%2C_forse_da_s.m._antiqua_%28roma%2C_coll._priv.%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Sant%27agata,_VII-inizio_VIII_secolo_ca.,_forse_da_s.m._antiqua_(roma,_coll._priv.).jpg", licence: "CC BY 3.0", artist: "Sailko" },
  "2-10": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Kleinmariazell_-_Altar_Scholastica_2.jpg/960px-Kleinmariazell_-_Altar_Scholastica_2.jpg", page: "https://commons.wikimedia.org/wiki/File:Kleinmariazell_-_Altar_Scholastica_2.jpg", licence: "CC BY-SA 3.0", artist: "Johann Baptist Wenzel Bergl" },
  "2-12": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/Meister_von_San_Vitale_in_Ravenna_008.jpg/960px-Meister_von_San_Vitale_in_Ravenna_008.jpg", page: "https://commons.wikimedia.org/wiki/File:Meister_von_San_Vitale_in_Ravenna_008.jpg", licence: "Public domain", artist: "Meister von San Vitale in Ravenna" },
  "2-13": { img: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Absalom-Jones_Peale.jpg", page: "https://commons.wikimedia.org/wiki/File:Absalom-Jones_Peale.jpg", licence: "Public domain", artist: "Raphaelle Peale" },
  "2-14": { img: "https://upload.wikimedia.org/wikipedia/commons/7/75/Sv_Kiril_Metodij_Zahari_Zograf_Trojanski_mon_1848.jpg", page: "https://commons.wikimedia.org/wiki/File:Sv_Kiril_Metodij_Zahari_Zograf_Trojanski_mon_1848.jpg", licence: "Public domain", artist: "painted by Zahari Zograf (Захарий Христович Димитров)" },
  "2-15": { img: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Thomas_Bray_painting.jpg", page: "https://commons.wikimedia.org/wiki/File:Thomas_Bray_painting.jpg", licence: "Public domain", artist: "unknown" },
  "2-18": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/90/Lucas_Cranach_d.%C3%84._-_Martin_Luther%2C_1528_%28Veste_Coburg%29.jpg/960px-Lucas_Cranach_d.%C3%84._-_Martin_Luther%2C_1528_%28Veste_Coburg%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Lucas_Cranach_d.%C3%84._-_Martin_Luther,_1528_(Veste_Coburg).jpg", licence: "Public domain", artist: "Lucas Cranach the Elder" },
  "2-19": { img: "https://upload.wikimedia.org/wikipedia/commons/6/66/Agnes_Tsao_Kouying.jpg", page: "https://commons.wikimedia.org/wiki/File:Agnes_Tsao_Kouying.jpg", licence: "CC0", artist: "Awvazquez" },
  "2-20": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Frederick_Douglass_%28circa_1879%29_%28cropped%29.jpg/960px-Frederick_Douglass_%28circa_1879%29_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Frederick_Douglass_(circa_1879)_(cropped).jpg", licence: "Public domain", artist: "George Kendall Warren" },
  "2-22": { img: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Calvi_J._A._Estasi_di_santa_Margherita.jpg", page: "https://commons.wikimedia.org/wiki/File:Calvi_J._A._Estasi_di_santa_Margherita.jpg", licence: "Public domain", artist: "Jacopo Alessandro Calvi" },
  "2-23": { img: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Polycarp_of_Smyrna2.jpg", page: "https://commons.wikimedia.org/wiki/File:Polycarp_of_Smyrna2.jpg", licence: "CC0", artist: "PravoslavnyChristianin" },
  "2-24": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Rubens_apostle_Matthias_grt.jpg/960px-Rubens_apostle_Matthias_grt.jpg", page: "https://commons.wikimedia.org/wiki/File:Rubens_apostle_Matthias_grt.jpg", licence: "Public domain", artist: "Peter Paul Rubens" },
  // the Samaritan woman at the well is Photini
  "2-26": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Angelika_Kauffmann_-_Christus_und_die_Samariterin_am_Brunnen_-1796.jpeg/960px-Angelika_Kauffmann_-_Christus_und_die_Samariterin_am_Brunnen_-1796.jpeg", page: "https://commons.wikimedia.org/wiki/File:Angelika_Kauffmann_-_Christus_und_die_Samariterin_am_Brunnen_-1796.jpeg", licence: "Public domain", artist: "Angelica Kauffmann" },
  "2-27": { img: "https://upload.wikimedia.org/wikipedia/commons/8/80/George_Herbert.jpg", page: "https://commons.wikimedia.org/wiki/File:George_Herbert.jpg", licence: "Public domain", artist: "Robert White" },
  "2-28": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/A_J_Cooper.jpg/960px-A_J_Cooper.jpg", page: "https://commons.wikimedia.org/wiki/File:A_J_Cooper.jpg", licence: "Public domain", artist: "C. M. Bell" },
  "3-1": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2b/Castell_Coch_stained_glass_panel_2.JPG/960px-Castell_Coch_stained_glass_panel_2.JPG", page: "https://commons.wikimedia.org/wiki/File:Castell_Coch_stained_glass_panel_2.JPG", licence: "CC BY-SA 4.0", artist: "Hchc2009" },
  "3-2": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/Saint_Chad%27s_Church%2C_Wrecsam%2C_Cymru%2C_Wales_71_%28cropped%29.jpg/960px-Saint_Chad%27s_Church%2C_Wrecsam%2C_Cymru%2C_Wales_71_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Saint_Chad%27s_Church,_Wrecsam,_Cymru,_Wales_71_(cropped).jpg", licence: "CC BY-SA 4.0", artist: "Llywelyn2000" },
  "3-3": { img: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Charles_Wesley.jpg", page: "https://commons.wikimedia.org/wiki/File:Charles_Wesley.jpg", licence: "Public domain", artist: "User Magnus Manske on en.wikipedia" },
  "3-7": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/Perpetua%2C_Felicitas%2C_Revocatus%2C_Saturninus_and_Secundulus_%28Menologion_of_Basil_II%29.jpg/960px-Perpetua%2C_Felicitas%2C_Revocatus%2C_Saturninus_and_Secundulus_%28Menologion_of_Basil_II%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Perpetua,_Felicitas,_Revocatus,_Saturninus_and_Secundulus_(Menologion_of_Basil_II).jpg", licence: "Public domain", artist: "Authors of Menologion of Basil II (circa 985 AC, Constantinople), Byzantine manuscript illuminators[1]: Pantoleon with Georgios, Michael the Younger, Michael of Blachernae, Symeon, Symeon of Blachernae, Menas, and Nestor  (Online on Vatican site)" },
  "3-9": { img: "https://upload.wikimedia.org/wikipedia/commons/2/29/Gregory_of_Nyssa.jpg", page: "https://commons.wikimedia.org/wiki/File:Gregory_of_Nyssa.jpg", licence: "Public domain", artist: "AnonymousUnknown author" },
  "3-10": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Carte-de-visite_portrait_of_Harriet_Tubman_%28cropped%29.jpg/960px-Carte-de-visite_portrait_of_Harriet_Tubman_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Carte-de-visite_portrait_of_Harriet_Tubman_(cropped).jpg", licence: "Public domain", artist: "Powelson, Benjamin F. 1823 - 1885" },
  "3-12": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5e/Gregory_the_Great_with_the_Holy_Spirit.jpg/960px-Gregory_the_Great_with_the_Holy_Spirit.jpg", page: "https://commons.wikimedia.org/wiki/File:Gregory_the_Great_with_the_Holy_Spirit.jpg", licence: "CC0", artist: "British Library" },
  "3-13": { img: "https://upload.wikimedia.org/wikipedia/commons/f/fc/The_Rt._Rev._James_Theodore_Holley.jpg", page: "https://commons.wikimedia.org/wiki/File:The_Rt._Rev._James_Theodore_Holley.jpg", licence: "Public domain", artist: "Churchman Company" },
  "3-15": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Simon_Fran%C3%A7ois_de_Tours_-_Portrait_Vincent_de_Paul_%284x5_cropped%29.jpeg/960px-Simon_Fran%C3%A7ois_de_Tours_-_Portrait_Vincent_de_Paul_%284x5_cropped%29.jpeg", page: "https://commons.wikimedia.org/wiki/File:Simon_Fran%C3%A7ois_de_Tours_-_Portrait_Vincent_de_Paul_(4x5_cropped).jpeg", licence: "Public domain", artist: "Simon François de Tours (1606-1671)" },
  "3-17": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bb/Our_Lady%27s_Island_Church_of_the_Assumption_East_Aisle_Window_Saint_Patrick_2010_09_26.jpg/960px-Our_Lady%27s_Island_Church_of_the_Assumption_East_Aisle_Window_Saint_Patrick_2010_09_26.jpg", page: "https://commons.wikimedia.org/wiki/File:Our_Lady%27s_Island_Church_of_the_Assumption_East_Aisle_Window_Saint_Patrick_2010_09_26.jpg", licence: "CC BY-SA 4.0", artist: "Andreas F. Borchert" },
  "3-18": { img: "https://upload.wikimedia.org/wikipedia/commons/6/69/Saint_Cyril_of_Jerusalem.jpg", page: "https://commons.wikimedia.org/wiki/File:Saint_Cyril_of_Jerusalem.jpg", licence: "Public domain", artist: "AnonymousUnknown author" },
  "3-19": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e3/Guido_Reni_-_St_Joseph_with_the_Infant_Jesus_-_WGA19304.jpg/960px-Guido_Reni_-_St_Joseph_with_the_Infant_Jesus_-_WGA19304.jpg", page: "https://commons.wikimedia.org/wiki/File:Guido_Reni_-_St_Joseph_with_the_Infant_Jesus_-_WGA19304.jpg", licence: "Public domain", artist: "Guido Reni" },
  "3-20": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/Cuthbert_discovers_piece_of_timber_-_Life_of_St._Cuthbert_%28late_12th_C%29%2C_f.45v_-_BL_Yates_Thompson_MS_26.jpg/960px-Cuthbert_discovers_piece_of_timber_-_Life_of_St._Cuthbert_%28late_12th_C%29%2C_f.45v_-_BL_Yates_Thompson_MS_26.jpg", page: "https://commons.wikimedia.org/wiki/File:Cuthbert_discovers_piece_of_timber_-_Life_of_St._Cuthbert_(late_12th_C),_f.45v_-_BL_Yates_Thompson_MS_26.jpg", licence: "CC0", artist: "Bede" },
  "3-21": { img: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Thomas_Ken_by_F._Scheffer.jpg", page: "https://commons.wikimedia.org/wiki/File:Thomas_Ken_by_F._Scheffer.jpg", licence: "Public domain", artist: "F. Scheffer (floruit 1700-1710)" },
  "3-22": { img: "https://upload.wikimedia.org/wikipedia/commons/7/78/James_DeKoven.gif", page: "https://commons.wikimedia.org/wiki/File:James_DeKoven.gif", licence: "Public domain", artist: "William C. Pope, Life of the Reverend James de Koven, D. D., Sometime Warden of Racine College. New York: James Pott &amp; Company, 1899" },
  "3-23": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Gregory_the_Illuminator_Aghtamar_bas_relief.jpg/960px-Gregory_the_Illuminator_Aghtamar_bas_relief.jpg", page: "https://commons.wikimedia.org/wiki/File:Gregory_the_Illuminator_Aghtamar_bas_relief.jpg", licence: "CC BY-SA 4.0", artist: "User:Dosseman" },
  "3-24": { img: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Monse%C3%B1or_Romero_%28colour%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Monse%C3%B1or_Romero_(colour).jpg", licence: "Public domain", artist: "Arzobispado de San Salvador; Congregatio de Causis Sanctorum" },
  "3-25": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d6/Annunciation_from_13th_century_Armenian_Gospel.jpg/960px-Annunciation_from_13th_century_Armenian_Gospel.jpg", page: "https://commons.wikimedia.org/wiki/File:Annunciation_from_13th_century_Armenian_Gospel.jpg", licence: "Public domain", artist: "uploader Koperczak (talk) 08:52, 26 March 2009 (UTC), Toros Roslin" },
  "3-26": { img: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Hmonsell.jpg", page: "https://commons.wikimedia.org/wiki/File:Hmonsell.jpg", licence: "Public domain", artist: "Thomas Thellusson Carter" },
  "3-27": { img: "https://upload.wikimedia.org/wikipedia/commons/2/24/Picture_of_Bishop_Charles_Brent.jpg", page: "https://commons.wikimedia.org/wiki/File:Picture_of_Bishop_Charles_Brent.jpg", licence: "Public domain", artist: "Brown Bros." },
  "3-28": { img: "https://upload.wikimedia.org/wikipedia/commons/8/8f/James_S._Russell.jpg", page: "https://commons.wikimedia.org/wiki/File:James_S._Russell.jpg", licence: "Public domain", artist: "Unknown, book in which the image is published in was edited by W. N. Hartshorn and George W. Penniman." },
  "3-29": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d6/John_Keble.jpg/960px-John_Keble.jpg", page: "https://commons.wikimedia.org/wiki/File:John_Keble.jpg", licence: "Public domain", artist: "Donkin (Miss)" },
  "3-30": { img: "https://upload.wikimedia.org/wikipedia/commons/e/ec/%D0%9C%D0%B0%D1%80%D1%96%D1%8F_%D0%84%D0%B3%D0%B8%D0%BF%D0%B5%D1%82%D1%81%D1%8C%D0%BA%D0%B0_%D0%B7_%D0%B6%D0%B8%D1%82%D1%96%D1%94%D0%BC._%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%B0_%D1%96%D0%BA%D0%BE%D0%BD%D0%B0_%D0%BA%D1%96%D0%BD%D1%86%D1%8F_XVII_%D1%81%D1%82._%D0%A1%D0%B5%D0%BB%D0%BE_%D0%9B%D1%96%D1%81%D0%BA%D0%BE%D0%B2%D0%B0%D1%82%D0%B5._-_Mary_of_Egypt_with_her_Life._Ukrainian_icon%2C_late_17th_century._Liskovate_village..jpg", page: "https://commons.wikimedia.org/wiki/File:%D0%9C%D0%B0%D1%80%D1%96%D1%8F_%D0%84%D0%B3%D0%B8%D0%BF%D0%B5%D1%82%D1%81%D1%8C%D0%BA%D0%B0_%D0%B7_%D0%B6%D0%B8%D1%82%D1%96%D1%94%D0%BC._%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%B0_%D1%96%D0%BA%D0%BE%D0%BD%D0%B0_%D0%BA%D1%96%D0%BD%D1%86%D1%8F_XVII_%D1%81%D1%82._%D0%A1%D0%B5%D0%BB%D0%BE_%D0%9B%D1%96%D1%81%D0%BA%D0%BE%D0%B2%D0%B0%D1%82%D0%B5._-_Mary_of_Egypt_with_her_Life._Ukrainian_icon,_late_17th_century._Liskovate_village..jpg", licence: "CC BY-SA 4.0", artist: "Hrom.nv" },
  "3-31": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/John_Donne_by_Isaac_Oliver.jpg/960px-John_Donne_by_Isaac_Oliver.jpg", page: "https://commons.wikimedia.org/wiki/File:John_Donne_by_Isaac_Oliver.jpg", licence: "Public domain", artist: "After Isaac Oliver" },
  "4-1": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Frederick_Denison_Maurice._Portrait_c1865.jpg/960px-Frederick_Denison_Maurice._Portrait_c1865.jpg", page: "https://commons.wikimedia.org/wiki/File:Frederick_Denison_Maurice._Portrait_c1865.jpg", licence: "CC BY 3.0", artist: "Acabashi" },
  "4-2": { img: "https://upload.wikimedia.org/wikipedia/commons/2/23/JamesLloydBreck1866.jpg", page: "https://commons.wikimedia.org/wiki/File:JamesLloydBreck1866.jpg", licence: "Public domain", artist: "Denison &amp; Potter" },
  "4-3": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e4/St_Saviour%2C_Eastbourne_IMG_3419_%2828342972384%29_%28cropped%29.jpg/960px-St_Saviour%2C_Eastbourne_IMG_3419_%2828342972384%29_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:St_Saviour,_Eastbourne_IMG_3419_(28342972384)_(cropped).jpg", licence: "CC BY 2.0", artist: "Fr James Bradley from Southampton, UK" },
  "4-4": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/The_Rev._Dr._Martin_Luther_King_Jr._Color_Portrait_%28high_quality%29.jpg/960px-The_Rev._Dr._Martin_Luther_King_Jr._Color_Portrait_%28high_quality%29.jpg", page: "https://commons.wikimedia.org/wiki/File:The_Rev._Dr._Martin_Luther_King_Jr._Color_Portrait_(high_quality).jpg", licence: "Public domain", artist: "Associated Press" },
  "4-5": { img: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Harriet_Starr_Cannon.jpg", page: "https://commons.wikimedia.org/wiki/File:Harriet_Starr_Cannon.jpg", licence: "Public domain", artist: "Arthur Lowndes." },
  "4-7": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b5/Tikhon_of_Moscow.jpg/960px-Tikhon_of_Moscow.jpg", page: "https://commons.wikimedia.org/wiki/File:Tikhon_of_Moscow.jpg", licence: "Public domain", artist: "Michael Goltz" },
  "4-8": { img: "https://upload.wikimedia.org/wikipedia/commons/6/62/Muhlenberg1.jpg", page: "https://commons.wikimedia.org/wiki/File:Muhlenberg1.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "4-9": { img: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Bundesarchiv_Bild_146-1987-074-16%2C_Dietrich_Bonhoeffer.jpg", page: "https://commons.wikimedia.org/wiki/File:Bundesarchiv_Bild_146-1987-074-16,_Dietrich_Bonhoeffer.jpg", licence: "CC BY-SA 3.0 de", artist: "Unknown authorUnknown author" },
  "4-10": { img: "https://upload.wikimedia.org/wikipedia/commons/1/1f/William_Law.jpg", page: "https://commons.wikimedia.org/wiki/File:William_Law.jpg", licence: "CC BY 4.0", artist: "John Scott" },
  "4-11": { img: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Selwyn%2C_George_Augustus_%281809-1878%29%2C_by_Mason_%26_Co..jpg", page: "https://commons.wikimedia.org/wiki/File:Selwyn,_George_Augustus_(1809-1878),_by_Mason_%26_Co..jpg", licence: "Public domain", artist: "Mason &amp; Co (Robert Hindry Mason)" },
  "4-17": { img: "https://upload.wikimedia.org/wikipedia/commons/f/ff/CatherinaeTekakwithaVirginis1690.jpg", page: "https://commons.wikimedia.org/wiki/File:CatherinaeTekakwithaVirginis1690.jpg", licence: "Public domain", artist: "Father Claude Chauchetière, S.J." },
  "4-18": { img: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Sor_Juana_by_Miguel_Cabrera_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Sor_Juana_by_Miguel_Cabrera_(cropped).jpg", licence: "Public domain", artist: "Miguel Cabrera" },
  "4-22": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Hadewijch_gedicht1_HsGent_f49r.jpg/960px-Hadewijch_gedicht1_HsGent_f49r.jpg", page: "https://commons.wikimedia.org/wiki/File:Hadewijch_gedicht1_HsGent_f49r.jpg", licence: "Public domain", artist: "Hadewijch (afschrift)" },
  "4-23": { img: "https://upload.wikimedia.org/wikipedia/commons/c/c8/KAGAWA_Toyohiko_young.JPG", page: "https://commons.wikimedia.org/wiki/File:KAGAWA_Toyohiko_young.JPG", licence: "Public domain", artist: "賀川豊彦記念・松沢資料館" },
  "4-25": { img: "https://upload.wikimedia.org/wikipedia/commons/7/79/Codexaureus_21.jpg", page: "https://commons.wikimedia.org/wiki/File:Codexaureus_21.jpg", licence: "Public domain", artist: "Scriptorium of the Lorsch Abbey (Hofschule Karls des Großen), Germany" },
  "4-29": { img: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Giovanni_Battista_Tiepolo_096.jpg", page: "https://commons.wikimedia.org/wiki/File:Giovanni_Battista_Tiepolo_096.jpg", licence: "Public domain", artist: "Giovanni Battista Tiepolo" },
  "5-2": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Fethiye_Camii%2C_parekklesion%2C_diakonikon%2C_mosaics%2C_Istanbul%2C_Turkey_-_South_wall%2C_St._Athanasius%2C_detail_of_upper_half_-_MSBZ004_BF_T_F_027_B_-_Dumbarton_Oaks.jpg/960px-thumbnail.jpg", page: "https://commons.wikimedia.org/wiki/File:Fethiye_Camii,_parekklesion,_diakonikon,_mosaics,_Istanbul,_Turkey_-_South_wall,_St._Athanasius,_detail_of_upper_half_-_MSBZ004_BF_T_F_027_B_-_Dumbarton_Oaks.jpg", licence: "CC0", artist: "Byzantine Institute staff" },
  "5-3": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/94/Herr_Christ%2C_der_einig_Gotts_Sohn_%281524%29.jpg/960px-Herr_Christ%2C_der_einig_Gotts_Sohn_%281524%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Herr_Christ,_der_einig_Gotts_Sohn_(1524).jpg", licence: "Public domain", artist: "Elisabeth Cruciger" },
  "5-4": { img: "https://upload.wikimedia.org/wikipedia/commons/9/92/Monica_of_Hippo_by_Gozzoli.jpg", page: "https://commons.wikimedia.org/wiki/File:Monica_of_Hippo_by_Gozzoli.jpg", licence: "Public domain", artist: "Benozzo Gozzoli" },
  "5-8": { img: "https://upload.wikimedia.org/wikipedia/commons/1/12/Statue_of_Dame_Julian_crop.jpg", page: "https://commons.wikimedia.org/wiki/File:Statue_of_Dame_Julian_crop.jpg", licence: "CC0", artist: "User:Poliphilo" },
  "5-11": { img: "https://upload.wikimedia.org/wikipedia/commons/6/66/Johann_Arndt.jpg", page: "https://commons.wikimedia.org/wiki/File:Johann_Arndt.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "5-13": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/PERKINS%2C_FRANCES_LCCN2016862692_%28cropped%29.jpg/960px-PERKINS%2C_FRANCES_LCCN2016862692_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:PERKINS,_FRANCES_LCCN2016862692_(cropped).jpg", licence: "Public domain", artist: "Harris &amp; Ewing, photographer" },
  "5-15": { img: "https://upload.wikimedia.org/wikipedia/commons/3/39/StPakhom.jpg", page: "https://commons.wikimedia.org/wiki/File:StPakhom.jpg", licence: "Public domain", artist: null },
  "5-17": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Thurgood-marshall-2.jpg/960px-Thurgood-marshall-2.jpg", page: "https://commons.wikimedia.org/wiki/File:Thurgood-marshall-2.jpg", licence: "Public domain", artist: "Robert S. Oakes" },
  "5-19": { img: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Dunstan3.jpg", page: "https://commons.wikimedia.org/wiki/File:Dunstan3.jpg", licence: "Public domain", artist: "Dunstan" },
  "5-20": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/Raban-Maur_Alcuin_Otgar.jpg/960px-Raban-Maur_Alcuin_Otgar.jpg", page: "https://commons.wikimedia.org/wiki/File:Raban-Maur_Alcuin_Otgar.jpg", licence: "Public domain", artist: "Fulda" },
  "5-21": { img: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Lidia.jpg", page: "https://commons.wikimedia.org/wiki/File:Lidia.jpg", licence: "Public domain", artist: "Russisch Ikone in Gemeinfreiheit - public domain" },
  "5-22": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3e/Elena_Colosseo_Rome_Italy.jpg/960px-Elena_Colosseo_Rome_Italy.jpg", page: "https://commons.wikimedia.org/wiki/File:Elena_Colosseo_Rome_Italy.jpg", licence: "CC0", artist: "Jebulon" },
  "5-24": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e8/Jackson_Kemper.jpg/960px-Jackson_Kemper.jpg", page: "https://commons.wikimedia.org/wiki/File:Jackson_Kemper.jpg", licence: "Public domain", artist: "Brady-Handy Photograph Collection (Library of Congress)" },
  "5-25": { img: "https://upload.wikimedia.org/wikipedia/commons/0/0d/E-codices_bke-0047_001v_medium_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:E-codices_bke-0047_001v_medium_(cropped).jpg", licence: "Public domain", artist: "http://www.e-codices.unifr.ch/de/bke/0047/1v" },
  "5-26": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/Saint_Augustine_by_Philippe_de_Champaigne.jpg/960px-Saint_Augustine_by_Philippe_de_Champaigne.jpg", page: "https://commons.wikimedia.org/wiki/File:Saint_Augustine_by_Philippe_de_Champaigne.jpg", licence: "Public domain", artist: "Philippe de Champaigne" },
  "5-28": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d3/Merazhofen_Pfarrkirche_Chorgest%C3%BChl_links_Mechthild.jpg/960px-Merazhofen_Pfarrkirche_Chorgest%C3%BChl_links_Mechthild.jpg", page: "https://commons.wikimedia.org/wiki/File:Merazhofen_Pfarrkirche_Chorgest%C3%BChl_links_Mechthild.jpg", licence: "CC BY 3.0", artist: "Photo: Andreas Praefcke" },
  "5-31": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Pontormo-visitation-after-restorationRGB.jpg/960px-Pontormo-visitation-after-restorationRGB.jpg", page: "https://commons.wikimedia.org/wiki/File:Pontormo-visitation-after-restorationRGB.jpg", licence: "Public domain", artist: "Pontormo" },
  "6-5": { img: "https://upload.wikimedia.org/wikipedia/commons/1/16/Saint_Boniface_by_Cornelis_Bloemaert.jpg", page: "https://commons.wikimedia.org/wiki/File:Saint_Boniface_by_Cornelis_Bloemaert.jpg", licence: "Public domain", artist: "Cornelis Bloemaert" },
  "6-8": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Heilige_Melania_de_Oudere_Kluizenaars_Thebaanse_heiligen_%28serietitel%29_Melania_Senior_%28titel_op_object%29%2C_RP-P-BI-1644_%28cropped%29.jpg/960px-Heilige_Melania_de_Oudere_Kluizenaars_Thebaanse_heiligen_%28serietitel%29_Melania_Senior_%28titel_op_object%29%2C_RP-P-BI-1644_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Heilige_Melania_de_Oudere_Kluizenaars_Thebaanse_heiligen_(serietitel)_Melania_Senior_(titel_op_object),_RP-P-BI-1644_(cropped).jpg", licence: "CC0", artist: "Rijksmuseum" },
  "6-9": { img: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Columba_at_Bridei%27s_fort.jpg", page: "https://commons.wikimedia.org/wiki/File:Columba_at_Bridei%27s_fort.jpg", licence: "Public domain", artist: "J. R. Skelton (Joseph Ratcliffe Skelton; 1865–1927) (illustrator), erroneously credited as John R. Skelton" },
  "6-10": { img: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Mor_Ephrem_icon.jpg", page: "https://commons.wikimedia.org/wiki/File:Mor_Ephrem_icon.jpg", licence: "Public domain", artist: "AnonymousUnknown author" },
  "6-12": { img: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Enmegahbowh.jpg", page: "https://commons.wikimedia.org/wiki/File:Enmegahbowh.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "6-14": { img: "https://upload.wikimedia.org/wikipedia/commons/0/04/Basil_of_Caesarea.jpg", page: "https://commons.wikimedia.org/wiki/File:Basil_of_Caesarea.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "6-15": { img: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Evelyn_Underhill_1926.png", page: "https://commons.wikimedia.org/wiki/File:Evelyn_Underhill_1926.png", licence: "Public domain", artist: "Pleshey Retreat House" },
  "6-16": { img: "https://upload.wikimedia.org/wikipedia/commons/9/90/Joseph_Butler%2C_Bp_of_Bristol.jpg", page: "https://commons.wikimedia.org/wiki/File:Joseph_Butler,_Bp_of_Bristol.jpg", licence: "Public domain", artist: "John Vanderbank" },
  "6-17": { img: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Marina_the_monk.jpg", page: "https://commons.wikimedia.org/wiki/File:Marina_the_monk.jpg", licence: "Public domain", artist: "Richard de Montbaston, from Jacobus de Voragine, Legenda aurea (traduction de Jean de Vignay), France, Paris" },
  "6-22": { img: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Saint_Alban_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Saint_Alban_(cropped).jpg", licence: "Public domain", artist: "DaveWebster14" },
  "6-24": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7f/Stjohn-nativity.jpg/960px-Stjohn-nativity.jpg", page: "https://commons.wikimedia.org/wiki/File:Stjohn-nativity.jpg", licence: "Public domain", artist: "The original uploader was Jackturner3 at English Wikipedia." },
  "6-26": { img: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Isabel_Florence_Hapgood.jpg", page: "https://commons.wikimedia.org/wiki/File:Isabel_Florence_Hapgood.jpg", licence: "Public domain", artist: "Ritz Portraits in NYPL digital Collections" },
  "6-28": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Saint_irenee_saint_irenee.jpg/960px-Saint_irenee_saint_irenee.jpg", page: "https://commons.wikimedia.org/wiki/File:Saint_irenee_saint_irenee.jpg", licence: "Public domain", artist: "Lucien Bégule" },
  "6-29": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Arquip%C3%A9lago_de_S%C3%A3o_Pedro_e_S%C3%A3o_Paulo_%2852749170397%29.jpg/960px-Arquip%C3%A9lago_de_S%C3%A3o_Pedro_e_S%C3%A3o_Paulo_%2852749170397%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Arquip%C3%A9lago_de_S%C3%A3o_Pedro_e_S%C3%A3o_Paulo_(52749170397).jpg", licence: "CC BY-SA 2.0", artist: "Marinha do Brasil" },
  "7-1": { img: "https://upload.wikimedia.org/wikipedia/commons/0/08/UNCPauliMurray.png", page: "https://commons.wikimedia.org/wiki/File:UNCPauliMurray.png", licence: "CC BY-SA 3.0", artist: "Carolina Digital Library and Archives" },
  "7-2": { img: "https://upload.wikimedia.org/wikipedia/commons/b/bc/San_Moises_el_Negro.jpg", page: "https://commons.wikimedia.org/wiki/File:San_Moises_el_Negro.jpg", licence: "CC BY-SA 4.0", artist: "Fundación La Buena Noticia" },
  "7-4": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/National_Days_map.svg/960px-National_Days_map.svg.png", page: "https://commons.wikimedia.org/wiki/File:National_Days_map.svg", licence: "CC BY-SA 4.0", artist: "El-Beheri" },
  "7-6": { img: "https://upload.wikimedia.org/wikipedia/commons/0/00/Mother_Eva_Mary%2C_C.T.png", page: "https://commons.wikimedia.org/wiki/File:Mother_Eva_Mary,_C.T.png", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "7-8": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/Jan_van_de_Venne_-_Saint_Paul_with_Saints_Aquila_and_Priscilla_%28crop%29.jpg/960px-Jan_van_de_Venne_-_Saint_Paul_with_Saints_Aquila_and_Priscilla_%28crop%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Jan_van_de_Venne_-_Saint_Paul_with_Saints_Aquila_and_Priscilla_(crop).jpg", licence: "CC0", artist: "Jan van der Venne" },
  "7-11": { img: "https://upload.wikimedia.org/wikipedia/commons/1/16/Memling%2C_Trittico_di_Benedetto_Portinari%2C_San_Benedetto.jpg", page: "https://commons.wikimedia.org/wiki/File:Memling,_Trittico_di_Benedetto_Portinari,_San_Benedetto.jpg", licence: "Public domain", artist: "Hans Memling" },
  "7-14": { img: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Argula_von_Grumbach.jpg", page: "https://commons.wikimedia.org/wiki/File:Argula_von_Grumbach.jpg", licence: "Public domain", artist: "Hans Schwarz" },
  "7-19": { img: "https://upload.wikimedia.org/wikipedia/commons/2/27/Macrina_the_Younger.jpg", page: "https://commons.wikimedia.org/wiki/File:Macrina_the_Younger.jpg", licence: "Public domain", artist: "AnonymousUnknown author" },
  "7-20": { img: "https://upload.wikimedia.org/wikipedia/commons/d/da/Elizabeth_Stanton.jpg", page: "https://commons.wikimedia.org/wiki/File:Elizabeth_Stanton.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "7-21": { img: "https://upload.wikimedia.org/wikipedia/commons/e/ef/NikolayBerdyaev_with_Maria_Skobtzeva.jpg", page: "https://commons.wikimedia.org/wiki/File:NikolayBerdyaev_with_Maria_Skobtzeva.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "7-22": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/TINTORETTO_-_Magdalena_penitente_%28Musei_Capitolini%2C_Roma%2C_1598-1602%29_-_copia.jpg/960px-TINTORETTO_-_Magdalena_penitente_%28Musei_Capitolini%2C_Roma%2C_1598-1602%29_-_copia.jpg", page: "https://commons.wikimedia.org/wiki/File:TINTORETTO_-_Magdalena_penitente_(Musei_Capitolini,_Roma,_1598-1602)_-_copia.jpg", licence: "Public domain", artist: "Domenico Tintoretto" },
  "7-23": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/John_Cassian.jpeg/960px-John_Cassian.jpeg", page: "https://commons.wikimedia.org/wiki/File:John_Cassian.jpeg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "7-24": { img: "https://upload.wikimedia.org/wikipedia/commons/0/09/Thomas_von_Kempen_JS.JPG", page: "https://commons.wikimedia.org/wiki/File:Thomas_von_Kempen_JS.JPG", licence: "Public domain", artist: "zeitgenössischer Maler" },
  "7-27": { img: "https://upload.wikimedia.org/wikipedia/commons/7/7c/William_Reed_Huntington.jpg", page: "https://commons.wikimedia.org/wiki/File:William_Reed_Huntington.jpg", licence: "Public domain", artist: null },
  "7-28": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/Johann_Sebastian_Bach.jpg/960px-Johann_Sebastian_Bach.jpg", page: "https://commons.wikimedia.org/wiki/File:Johann_Sebastian_Bach.jpg", licence: "Public domain", artist: "Elias Gottlob Haussmann" },
  "7-30": { img: "https://upload.wikimedia.org/wikipedia/commons/e/eb/William_wilberforce.jpg", page: "https://commons.wikimedia.org/wiki/File:William_wilberforce.jpg", licence: "Public domain", artist: "Anton Hickel" },
  "7-31": { img: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Ignatius_Loyola.jpg", page: "https://commons.wikimedia.org/wiki/File:Ignatius_Loyola.jpg", licence: "Public domain", artist: "AnonymousUnknown author" },
  "8-1": { img: "https://upload.wikimedia.org/wikipedia/commons/6/66/Brooklyn_Museum_-_Joseph_of_Arimathaea_%28Joseph_d%27Arimathie%29_-_James_Tissot.jpg", page: "https://commons.wikimedia.org/wiki/File:Brooklyn_Museum_-_Joseph_of_Arimathaea_(Joseph_d%27Arimathie)_-_James_Tissot.jpg", licence: "Public domain", artist: "James Tissot" },
  "8-7": { img: "https://upload.wikimedia.org/wikipedia/commons/3/3c/John_Mason_Neale.jpg", page: "https://commons.wikimedia.org/wiki/File:John_Mason_Neale.jpg", licence: "Public domain", artist: null },
  "8-8": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/SaintDominic.jpg/960px-SaintDominic.jpg", page: "https://commons.wikimedia.org/wiki/File:SaintDominic.jpg", licence: "Public domain", artist: "Claudio Coello" },
  "8-11": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1f/SDamiano-Clara.jpg/960px-SDamiano-Clara.jpg", page: "https://commons.wikimedia.org/wiki/File:SDamiano-Clara.jpg", licence: "Public domain", artist: "Gunnar Bach Pedersen" },
  "8-12": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Florence_Nightingale_%28H_Hering_NPG_x82368%29.jpg/960px-Florence_Nightingale_%28H_Hering_NPG_x82368%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Florence_Nightingale_(H_Hering_NPG_x82368).jpg", licence: "Public domain", artist: "Henry Hering (1814-1893)" },
  "8-13": { img: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Jeremytaylor.jpg", page: "https://commons.wikimedia.org/wiki/File:Jeremytaylor.jpg", licence: "Public domain", artist: "Eden Upton Eddis" },
  "8-14": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/Jonathan_Myrick_Daniels_with_children.jpg/960px-Jonathan_Myrick_Daniels_with_children.jpg", page: "https://commons.wikimedia.org/wiki/File:Jonathan_Myrick_Daniels_with_children.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "8-15": { img: "https://upload.wikimedia.org/wikipedia/commons/7/70/Madonna_Advocata.png", page: "https://commons.wikimedia.org/wiki/File:Madonna_Advocata.png", licence: "CC BY-SA 4.0", artist: "Asia" },
  "8-20": { img: "https://upload.wikimedia.org/wikipedia/commons/c/cd/San_Bernardo%2C_de_Juan_Correa_de_Vivar_%28Museo_del_Prado%29.jpg", page: "https://commons.wikimedia.org/wiki/File:San_Bernardo,_de_Juan_Correa_de_Vivar_(Museo_del_Prado).jpg", licence: "Public domain", artist: null },
  "8-24": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Rubens_apostel_bartolomeus_grt.jpg/960px-Rubens_apostel_bartolomeus_grt.jpg", page: "https://commons.wikimedia.org/wiki/File:Rubens_apostel_bartolomeus_grt.jpg", licence: "Public domain", artist: "Peter Paul Rubens" },
  "8-25": { img: "https://upload.wikimedia.org/wikipedia/commons/d/de/Saintlouis_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Saintlouis_(cropped).jpg", licence: "Public domain", artist: "AnonymousUnknown author" },
  // the Ethiopian eunuch is Simeon Bachos
  "8-26": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/08/Icon_of_Djan_Darada.jpg/960px-Icon_of_Djan_Darada.jpg", page: "https://commons.wikimedia.org/wiki/File:Icon_of_Djan_Darada.jpg", licence: "CC0", artist: "T95Tank" },
  "8-27": { img: "https://upload.wikimedia.org/wikipedia/commons/d/df/Henry_Winter_Syle.png", page: "https://commons.wikimedia.org/wiki/File:Henry_Winter_Syle.png", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "8-28": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/Saint_Augustine_by_Philippe_de_Champaigne.jpg/960px-Saint_Augustine_by_Philippe_de_Champaigne.jpg", page: "https://commons.wikimedia.org/wiki/File:Saint_Augustine_by_Philippe_de_Champaigne.jpg", licence: "Public domain", artist: "Philippe de Champaigne" },
  "8-29": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Salome_with_the_Head_of_John_the_Baptist-Caravaggio_%281610%29.jpg/960px-Salome_with_the_Head_of_John_the_Baptist-Caravaggio_%281610%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Salome_with_the_Head_of_John_the_Baptist-Caravaggio_(1610).jpg", licence: "Public domain", artist: "Caravaggio" },
  "8-30": { img: "https://upload.wikimedia.org/wikipedia/commons/b/b4/St_Etheldreda%2C_Ely_Place%2C_London_EC1_-_Nave_statue_-_geograph.org.uk_-_1613381.jpg", page: "https://commons.wikimedia.org/wiki/File:St_Etheldreda,_Ely_Place,_London_EC1_-_Nave_statue_-_geograph.org.uk_-_1613381.jpg", licence: "CC BY-SA 2.0", artist: "John Salmon" },
  "8-31": { img: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Saint_Aidan.jpg", page: "https://commons.wikimedia.org/wiki/File:Saint_Aidan.jpg", licence: "CC BY 2.0", artist: "Randy OHC" },
  "9-1": { img: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Oakerhater_1881.jpg", page: "https://commons.wikimedia.org/wiki/File:Oakerhater_1881.jpg", licence: "Public domain", artist: "A.B. Gardner, Utica, NY" },
  "9-2": { img: "https://upload.wikimedia.org/wikipedia/commons/5/5e/London_UK_Sculptures-at-Westminster-Abbey-Westgate-01_%28Tapiedi%29.jpg", page: "https://commons.wikimedia.org/wiki/File:London_UK_Sculptures-at-Westminster-Abbey-Westgate-01_(Tapiedi).jpg", licence: "CC BY-SA 3.0", artist: "CEphoto, Uwe Aranas" },
  "9-4": { img: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Cpt_John_Paul_Jones.jpg", page: "https://commons.wikimedia.org/wiki/File:Cpt_John_Paul_Jones.jpg", licence: "Public domain", artist: "After Charles Willson Peale" },
  "9-6": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/Henry_William_Pickersgill_%281782-1875%29_-_Hannah_More_%281745%E2%80%931833%29_-_922269_-_National_Trust.jpg/960px-Henry_William_Pickersgill_%281782-1875%29_-_Hannah_More_%281745%E2%80%931833%29_-_922269_-_National_Trust.jpg", page: "https://commons.wikimedia.org/wiki/File:Henry_William_Pickersgill_(1782-1875)_-_Hannah_More_(1745%E2%80%931833)_-_922269_-_National_Trust.jpg", licence: "Public domain", artist: "Henry William Pickersgill" },
  // Kassia is Kassiani
  "9-7": { img: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Kassia.jpg", page: "https://commons.wikimedia.org/wiki/File:Kassia.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "9-8": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Adoration_of_the_sheperds_-_Matthias_Stomer.jpg/960px-Adoration_of_the_sheperds_-_Matthias_Stomer.jpg", page: "https://commons.wikimedia.org/wiki/File:Adoration_of_the_sheperds_-_Matthias_Stomer.jpg", licence: "Public domain", artist: "Paris Orlando" },
  "9-10": { img: "https://upload.wikimedia.org/wikipedia/commons/8/87/Alexander_Crummel_%28cropped%29.png", page: "https://commons.wikimedia.org/wiki/File:Alexander_Crummel_(cropped).png", licence: "Public domain", artist: "Internet Archive Book Images" },
  "9-12": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Reverend_john_Hobart_bishop.jpg/960px-Reverend_john_Hobart_bishop.jpg", page: "https://commons.wikimedia.org/wiki/File:Reverend_john_Hobart_bishop.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "9-13": { img: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Cyprian_von_Karthago2.jpg", page: "https://commons.wikimedia.org/wiki/File:Cyprian_von_Karthago2.jpg", licence: "Public domain", artist: "The original uploader was Bwag at German Wikipedia." },
  "9-14": { img: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Feast_of_the_Cross.jpg", page: "https://commons.wikimedia.org/wiki/File:Feast_of_the_Cross.jpg", licence: "Public domain", artist: "Gury Nikitin" },
  "9-15": { img: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Santa_Caterina_Fieschi_Adorno-dipinto_Giovanni_Agostino_Ratti.jpg", page: "https://commons.wikimedia.org/wiki/File:Santa_Caterina_Fieschi_Adorno-dipinto_Giovanni_Agostino_Ratti.jpg", licence: "Public domain", artist: "Giovanni Agostino Ratti" },
  "9-16": { img: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Ninian_of_Whithorn.jpg", page: "https://commons.wikimedia.org/wiki/File:Ninian_of_Whithorn.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "9-17": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/ba/Hildegard_von_Bingen.jpg/960px-Hildegard_von_Bingen.jpg", page: "https://commons.wikimedia.org/wiki/File:Hildegard_von_Bingen.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "9-18": { img: "https://upload.wikimedia.org/wikipedia/commons/5/55/Rosa_Corder_%281853-1893%29_-_Reverend_Edward_Bouverie_Pusey%2C_Member_of_Keble_College_Council_%281870%E2%80%931880%29_%28copy_of_an_earlier_work%29_-_PCF31_-_Keble_College.jpg", page: "https://commons.wikimedia.org/wiki/File:Rosa_Corder_(1853-1893)_-_Reverend_Edward_Bouverie_Pusey,_Member_of_Keble_College_Council_(1870%E2%80%931880)_(copy_of_an_earlier_work)_-_PCF31_-_Keble_College.jpg", licence: "Public domain", artist: "Rosa Corder" },
  "9-20": { img: "https://upload.wikimedia.org/wikipedia/commons/4/49/John_Patteson.jpg", page: "https://commons.wikimedia.org/wiki/File:John_Patteson.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "9-21": { img: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Codexaureus_17.jpg", page: "https://commons.wikimedia.org/wiki/File:Codexaureus_17.jpg", licence: "Public domain", artist: null },
  "9-22": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f4/Chase_Philander-Bishop_Episcopal_Church_USA.jpg/960px-Chase_Philander-Bishop_Episcopal_Church_USA.jpg", page: "https://commons.wikimedia.org/wiki/File:Chase_Philander-Bishop_Episcopal_Church_USA.jpg", licence: "Public domain", artist: null },
  "9-25": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/61/Sergius_of_Radonezh_vita_icon_%2817_c.%2C_Yaroslavl_museum%29_2.jpg/960px-Sergius_of_Radonezh_vita_icon_%2817_c.%2C_Yaroslavl_museum%29_2.jpg", page: "https://commons.wikimedia.org/wiki/File:Sergius_of_Radonezh_vita_icon_(17_c.,_Yaroslavl_museum)_2.jpg", licence: "Public domain", artist: "AnonymousUnknown author" },
  "9-26": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/Launcelot_Andrews_%281555-1626%29%2C_English_School_circa_1660.jpg/960px-Launcelot_Andrews_%281555-1626%29%2C_English_School_circa_1660.jpg", page: "https://commons.wikimedia.org/wiki/File:Launcelot_Andrews_(1555-1626),_English_School_circa_1660.jpg", licence: "Public domain", artist: "Unidentified painter / Joseph Buckshorn" },
  "9-30": { img: "https://upload.wikimedia.org/wikipedia/commons/5/5f/MatthiasStom-SaintJerome-Nantes.jpg", page: "https://commons.wikimedia.org/wiki/File:MatthiasStom-SaintJerome-Nantes.jpg", licence: "Public domain", artist: "Matthias Stom" },
  "10-1": { img: "https://upload.wikimedia.org/wikipedia/commons/6/69/Teresa-de-Lisieux.jpg", page: "https://commons.wikimedia.org/wiki/File:Teresa-de-Lisieux.jpg", licence: "Public domain", artist: "Céline Martin" },
  "10-3": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/aa/John_Raleigh_Mott.jpg/960px-John_Raleigh_Mott.jpg", page: "https://commons.wikimedia.org/wiki/File:John_Raleigh_Mott.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "10-4": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Philip_Fruytiers_-_St._Francis_of_Assisi.jpg/960px-Philip_Fruytiers_-_St._Francis_of_Assisi.jpg", page: "https://commons.wikimedia.org/wiki/File:Philip_Fruytiers_-_St._Francis_of_Assisi.jpg", licence: "Public domain", artist: "Philip Fruytiers" },
  "10-6": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/64/Beza%27s_Icones%2C_contemporary_portraits_of_reformers_of_religion_and_letters_-_William_Tindale_on_Page_58.jpg/960px-Beza%27s_Icones%2C_contemporary_portraits_of_reformers_of_religion_and_letters_-_William_Tindale_on_Page_58.jpg", page: "https://commons.wikimedia.org/wiki/File:Beza%27s_Icones,_contemporary_portraits_of_reformers_of_religion_and_letters_-_William_Tindale_on_Page_58.jpg", licence: "Public domain", artist: "McCrie, Charles Greig, 1836-1910 Bèze, Théodore de, 1519-1605" },
  "10-7": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2c/Heliga_Birgitta_p%C3%A5_ett_altarsk%C3%A5p_i_Salems_kyrka_retouched.png/960px-Heliga_Birgitta_p%C3%A5_ett_altarsk%C3%A5p_i_Salems_kyrka_retouched.png", page: "https://commons.wikimedia.org/wiki/File:Heliga_Birgitta_p%C3%A5_ett_altarsk%C3%A5p_i_Salems_kyrka_retouched.png", licence: "Public domain", artist: "Heliga_Birgitta_på_ett_altarskåp_i_Salems_kyrka.jpg: Hermann Rode (late 15th century) derivative work: Beao" },
  "10-9": { img: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Grosseteste_bishop.jpg", page: "https://commons.wikimedia.org/wiki/File:Grosseteste_bishop.jpg", licence: "Public domain", artist: "Unknown 14th century scribe" },
  "10-10": { img: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Vida_Dutton_Scudder_001.jpg", page: "https://commons.wikimedia.org/wiki/File:Vida_Dutton_Scudder_001.jpg", licence: "Public domain", artist: "Unknown photographer" },
  "10-11": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Phillip_II%2C_king_of_Macedonia%2C_Roman_copy_of_Greek_original%2C_Ny_Carlsberg_Glyptotek%2C_Copenhagen_%2836420294055%29.jpg/960px-Phillip_II%2C_king_of_Macedonia%2C_Roman_copy_of_Greek_original%2C_Ny_Carlsberg_Glyptotek%2C_Copenhagen_%2836420294055%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Phillip_II,_king_of_Macedonia,_Roman_copy_of_Greek_original,_Ny_Carlsberg_Glyptotek,_Copenhagen_(36420294055).jpg", licence: "CC BY 2.0", artist: "Richard Mortel from Riyadh, Saudi Arabia" },
  "10-12": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/72/Edith_Cavell.jpg/960px-Edith_Cavell.jpg", page: "https://commons.wikimedia.org/wiki/File:Edith_Cavell.jpg", licence: "Public domain", artist: "The original uploader was Vivedatica at Dutch Wikipedia." },
  "10-14": { img: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Joseph_Schereschewsky.jpg", page: "https://commons.wikimedia.org/wiki/File:Joseph_Schereschewsky.jpg", licence: "Public domain", artist: null },
  "10-15": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/20/Santa_Teresa_de_Jes%C3%BAs_%28Museo_del_Prado%29.jpg/960px-Santa_Teresa_de_Jes%C3%BAs_%28Museo_del_Prado%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Santa_Teresa_de_Jes%C3%BAs_(Museo_del_Prado).jpg", licence: "Public domain", artist: "Eduardo Balaca" },
  "10-16": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Hugh_Latimer_from_NPG.jpg/960px-Hugh_Latimer_from_NPG.jpg", page: "https://commons.wikimedia.org/wiki/File:Hugh_Latimer_from_NPG.jpg", licence: "Public domain", artist: "Unidentified painter" },
  "10-17": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/Hosios_Loukas_%28south_west_chapel%2C_south_side%29_-_Ignatios.jpg/960px-Hosios_Loukas_%28south_west_chapel%2C_south_side%29_-_Ignatios.jpg", page: "https://commons.wikimedia.org/wiki/File:Hosios_Loukas_(south_west_chapel,_south_side)_-_Ignatios.jpg", licence: "Public domain", artist: "AnonymousUnknown author" },
  "10-18": { img: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Codexaureus_23.jpg", page: "https://commons.wikimedia.org/wiki/File:Codexaureus_23.jpg", licence: "Public domain", artist: null },
  "10-19": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/35/Henry_Martyn_%28missionary%29.jpg/960px-Henry_Martyn_%28missionary%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Henry_Martyn_(missionary).jpg", licence: "Public domain", artist: "Unknown, Cambridge University" },
  "10-20": { img: "https://upload.wikimedia.org/wikipedia/commons/4/4e/%27Vision_of_the_Centurion_Cornelius%27_by_Zanobi_Rosi_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:%27Vision_of_the_Centurion_Cornelius%27_by_Zanobi_Rosi_(cropped).jpg", licence: "Public domain", artist: "Zanobi Rosi" },
  "10-23": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/Inside_Saint_James_Cathedral_in_the_Armenian_Quarter_of_Jerusalem.jpg/960px-Inside_Saint_James_Cathedral_in_the_Armenian_Quarter_of_Jerusalem.jpg", page: "https://commons.wikimedia.org/wiki/File:Inside_Saint_James_Cathedral_in_the_Armenian_Quarter_of_Jerusalem.jpg", licence: "CC BY 2.0", artist: "Claudius Prößer" },
  "10-25": { img: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Saint_Tabitha.jpg", page: "https://commons.wikimedia.org/wiki/File:Saint_Tabitha.jpg", licence: "CC BY-SA 4.0", artist: "Wolfymoza" },
  "10-28": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Anthonis_van_Dyck%2C_Kunsthistorisches_Museum_Wien%2C_Gem%C3%A4ldegalerie_-_Apostel_Judas_Thadd%C3%A4us_-_GG_6809_-_Kunsthistorisches_Museum.jpg/960px-Anthonis_van_Dyck%2C_Kunsthistorisches_Museum_Wien%2C_Gem%C3%A4ldegalerie_-_Apostel_Judas_Thadd%C3%A4us_-_GG_6809_-_Kunsthistorisches_Museum.jpg", page: "https://commons.wikimedia.org/wiki/File:Anthonis_van_Dyck,_Kunsthistorisches_Museum_Wien,_Gem%C3%A4ldegalerie_-_Apostel_Judas_Thadd%C3%A4us_-_GG_6809_-_Kunsthistorisches_Museum.jpg", licence: "Public domain", artist: "Anthony van Dyck" },
  "10-29": { img: "https://upload.wikimedia.org/wikipedia/commons/3/33/Bishop_Hannington.jpg", page: "https://commons.wikimedia.org/wiki/File:Bishop_Hannington.jpg", licence: "Public domain", artist: "Michael, Charles D" },
  "11-1": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/Celebraci%C3%B3n_de_Todos_los_Santos%2C_cementerio_de_la_Santa_Cruz%2C_Gniezno%2C_Polonia%2C_2017-11-01%2C_DD_07-09_HDR.jpg/960px-Celebraci%C3%B3n_de_Todos_los_Santos%2C_cementerio_de_la_Santa_Cruz%2C_Gniezno%2C_Polonia%2C_2017-11-01%2C_DD_07-09_HDR.jpg", page: "https://commons.wikimedia.org/wiki/File:Celebraci%C3%B3n_de_Todos_los_Santos,_cementerio_de_la_Santa_Cruz,_Gniezno,_Polonia,_2017-11-01,_DD_07-09_HDR.jpg", licence: "CC BY-SA 4.0", artist: "Diego Delso" },
  "11-3": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7c/Wenceslas_Hollar_-_Richard_Hooker_%28State_1%29.jpg/960px-Wenceslas_Hollar_-_Richard_Hooker_%28State_1%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Wenceslas_Hollar_-_Richard_Hooker_(State_1).jpg", licence: "Public domain", artist: "Wenceslaus Hollar" },
  "11-7": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Georg_Sturm%2C_Willibrordus_predikt_het_Christendom_aan_de_Friezen.jpg/960px-Georg_Sturm%2C_Willibrordus_predikt_het_Christendom_aan_de_Friezen.jpg", page: "https://commons.wikimedia.org/wiki/File:Georg_Sturm,_Willibrordus_predikt_het_Christendom_aan_de_Friezen.jpg", licence: "Public domain", artist: null },
  "11-11": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/Simone_Martini_040.jpg/960px-Simone_Martini_040.jpg", page: "https://commons.wikimedia.org/wiki/File:Simone_Martini_040.jpg", licence: "Public domain", artist: "Simone Martini" },
  "11-12": { img: "https://upload.wikimedia.org/wikipedia/commons/8/82/CharlesSimeon.jpg", page: "https://commons.wikimedia.org/wiki/File:CharlesSimeon.jpg", licence: "Public domain", artist: "Contemporary portrait" },
  "11-15": { img: "https://upload.wikimedia.org/wikipedia/commons/2/20/Glorification_of_Venerable_Herman_of_Alaska%2C_Wonderworker_of_All_America_wg.jpg", page: "https://commons.wikimedia.org/wiki/File:Glorification_of_Venerable_Herman_of_Alaska,_Wonderworker_of_All_America_wg.jpg", licence: "CC BY-SA 4.0", artist: "Unknown authorUnknown author" },
  "11-17": { img: "https://upload.wikimedia.org/wikipedia/commons/1/19/Hug-lin-pi.jpg", page: "https://commons.wikimedia.org/wiki/File:Hug-lin-pi.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "11-18": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/St_Hilda_%28Stained_glass%2C_Chester_Cathedral%29_%28cropped%29.JPG/330px-St_Hilda_%28Stained_glass%2C_Chester_Cathedral%29_%28cropped%29.JPG", page: "https://commons.wikimedia.org/wiki/File:St_Hilda_(Stained_glass,_Chester_Cathedral)_(cropped).JPG", licence: "CC BY-SA 4.0", artist: "Mum's taxi" },
  "11-19": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Simone_Martini_046.jpg/960px-Simone_Martini_046.jpg", page: "https://commons.wikimedia.org/wiki/File:Simone_Martini_046.jpg", licence: "Public domain", artist: "Simone Martini" },
  "11-20": { img: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Edmund_I_of_England.png", page: "https://commons.wikimedia.org/wiki/File:Edmund_I_of_England.png", licence: "Public domain", artist: "See description" },
  "11-22": { img: "https://upload.wikimedia.org/wikipedia/commons/2/27/CS_Lewis_photo_on_dust_jacket.jpg", page: "https://commons.wikimedia.org/wiki/File:CS_Lewis_photo_on_dust_jacket.jpg", licence: "Public domain", artist: "John S. Murray" },
  "11-23": { img: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Clemens_Romanus.jpg", page: "https://commons.wikimedia.org/wiki/File:Clemens_Romanus.jpg", licence: "Public domain", artist: "Unknown" },
  "11-24": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/da/Saint_Catherine_of_Alexandria_%28Caravaggio%29.jpg/960px-Saint_Catherine_of_Alexandria_%28Caravaggio%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Saint_Catherine_of_Alexandria_(Caravaggio).jpg", licence: "Public domain", artist: "Caravaggio" },
  "11-25": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d2/James_Otis_Sargent_Huntington_OHC.jpg/960px-James_Otis_Sargent_Huntington_OHC.jpg", page: "https://commons.wikimedia.org/wiki/File:James_Otis_Sargent_Huntington_OHC.jpg", licence: "CC BY 2.0", artist: "The original uploader was Taymoss at English Wikipedia." },
  "11-28": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/Queen_Emma_of_Hawaii_%E2%80%93_Brady-Handy.jpg/960px-Queen_Emma_of_Hawaii_%E2%80%93_Brady-Handy.jpg", page: "https://commons.wikimedia.org/wiki/File:Queen_Emma_of_Hawaii_%E2%80%93_Brady-Handy.jpg", licence: "Public domain", artist: "Mathew Benjamin Brady" },
  "11-30": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/Rubens_apostel_andreas_grt.jpg/960px-Rubens_apostel_andreas_grt.jpg", page: "https://commons.wikimedia.org/wiki/File:Rubens_apostel_andreas_grt.jpg", licence: "Public domain", artist: "Peter Paul Rubens" },
  "12-1": { img: "https://upload.wikimedia.org/wikipedia/commons/6/60/Charles_de_Foucauld.jpg", page: "https://commons.wikimedia.org/wiki/File:Charles_de_Foucauld.jpg", licence: "Public domain", artist: "Edsdet" },
  "12-2": { img: "https://upload.wikimedia.org/wikipedia/commons/3/36/Channing_Moore_Williams_01.jpg", page: "https://commons.wikimedia.org/wiki/File:Channing_Moore_Williams_01.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "12-3": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/Franciscus_de_Xabier.jpg/960px-Franciscus_de_Xabier.jpg", page: "https://commons.wikimedia.org/wiki/File:Franciscus_de_Xabier.jpg", licence: "Public domain", artist: null },
  "12-4": { img: "https://upload.wikimedia.org/wikipedia/commons/4/42/Athonite_Fresco_Icon_of_Saint_John_of_Damascus.jpg", page: "https://commons.wikimedia.org/wiki/File:Athonite_Fresco_Icon_of_Saint_John_of_Damascus.jpg", licence: "Public domain", artist: "Unknown authorUnknown author" },
  "12-5": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/Clement_alexandrin.jpg/960px-Clement_alexandrin.jpg", page: "https://commons.wikimedia.org/wiki/File:Clement_alexandrin.jpg", licence: "Public domain", artist: "André Thévet" },
  "12-6": { img: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Jaroslav_%C4%8Cerm%C3%A1k_%281831_-_1878%29_-_Sv._Mikul%C3%A1%C5%A1_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Jaroslav_%C4%8Cerm%C3%A1k_(1831_-_1878)_-_Sv._Mikul%C3%A1%C5%A1_(cropped).jpg", licence: "Public domain", artist: "Jaroslav Čermák" },
  "12-7": { img: "https://upload.wikimedia.org/wikipedia/commons/7/74/AmbroseOfMilan_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:AmbroseOfMilan_(cropped).jpg", licence: "Public domain", artist: null },
  "12-8": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/aa/Nicholas_Ferrar_%281592-1637%29.jpeg/960px-Nicholas_Ferrar_%281592-1637%29.jpeg", page: "https://commons.wikimedia.org/wiki/File:Nicholas_Ferrar_(1592-1637).jpeg", licence: "Public domain", artist: "Cornelis Janssens van Ceulen (1593-1661)" },
  "12-12": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/Ch%C3%A2teau_de_Bussy-Rabutin_-_Saint_Fran%C3%A7ois_de_Sales%2C_%C3%A9v%C3%AAque_de_Gen%C3%A8ve_%28bgw19_0375%29_%28cropped%29.jpg/960px-Ch%C3%A2teau_de_Bussy-Rabutin_-_Saint_Fran%C3%A7ois_de_Sales%2C_%C3%A9v%C3%AAque_de_Gen%C3%A8ve_%28bgw19_0375%29_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Ch%C3%A2teau_de_Bussy-Rabutin_-_Saint_Fran%C3%A7ois_de_Sales,_%C3%A9v%C3%AAque_de_Gen%C3%A8ve_(bgw19_0375)_(cropped).jpg", licence: "Public domain", artist: "Benjamin Gavaudo" },
  "12-13": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/be/Niccol%C3%B2_di_Segna_-_Saint_Lucy_-_Walters_37756.jpg/960px-Niccol%C3%B2_di_Segna_-_Saint_Lucy_-_Walters_37756.jpg", page: "https://commons.wikimedia.org/wiki/File:Niccol%C3%B2_di_Segna_-_Saint_Lucy_-_Walters_37756.jpg", licence: "Public domain", artist: "Niccolò di Segna" },
  "12-14": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Bozoma_Saint_John_at_Essence_Festival_of_Culture_July_2025_%28cropped%29.jpg/960px-Bozoma_Saint_John_at_Essence_Festival_of_Culture_July_2025_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Bozoma_Saint_John_at_Essence_Festival_of_Culture_July_2025_(cropped).jpg", licence: "CC BY-SA 4.0", artist: "Danielle G. Campbell" },
  "12-15": { img: "https://upload.wikimedia.org/wikipedia/commons/7/74/St._Nino_Icon1.jpg", page: "https://commons.wikimedia.org/wiki/File:St._Nino_Icon1.jpg", licence: "Public domain", artist: "Ackerman200" },
  "12-17": { img: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Sayers-whose-body-image.png", page: "https://commons.wikimedia.org/wiki/File:Sayers-whose-body-image.png", licence: "Public domain", artist: "uncredited; published by Boni and Liveright in connexion with her 1925 release Whose Body" },
  "12-20": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Lucas_Cranach_%28I%29_-_Katharina_von_Bora_als_Brustbildbnis_nach_links_%28Veste_Coburg%29.jpg/960px-Lucas_Cranach_%28I%29_-_Katharina_von_Bora_als_Brustbildbnis_nach_links_%28Veste_Coburg%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Lucas_Cranach_(I)_-_Katharina_von_Bora_als_Brustbildbnis_nach_links_(Veste_Coburg).jpg", licence: "Public domain", artist: "Lucas Cranach the Elder" },
  "12-21": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/56/Thomas_the_Apostle._Detail_of_the_mosaic_in_the_Basilica_of_San_Vitale._Ravena%2C_Italy.jpg/960px-Thomas_the_Apostle._Detail_of_the_mosaic_in_the_Basilica_of_San_Vitale._Ravena%2C_Italy.jpg", page: "https://commons.wikimedia.org/wiki/File:Thomas_the_Apostle._Detail_of_the_mosaic_in_the_Basilica_of_San_Vitale._Ravena,_Italy.jpg", licence: "CC BY 2.0", artist: "Richard Mortel" },
  "12-25": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Adoration_of_the_sheperds_-_Matthias_Stomer.jpg/960px-Adoration_of_the_sheperds_-_Matthias_Stomer.jpg", page: "https://commons.wikimedia.org/wiki/File:Adoration_of_the_sheperds_-_Matthias_Stomer.jpg", licence: "Public domain", artist: "Paris Orlando" },
  "12-26": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/85/Saint_Stephen_%28Carlo_Crivelli%29.jpg/960px-Saint_Stephen_%28Carlo_Crivelli%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Saint_Stephen_(Carlo_Crivelli).jpg", licence: "Public domain", artist: "Carlo Crivelli" },
  "12-27": { img: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Bozoma_Saint_John_at_Essence_Festival_of_Culture_July_2025_%28cropped%29.jpg/960px-Bozoma_Saint_John_at_Essence_Festival_of_Culture_July_2025_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:Bozoma_Saint_John_at_Essence_Festival_of_Culture_July_2025_(cropped).jpg", licence: "CC BY-SA 4.0", artist: "Danielle G. Campbell" },
  "12-29": { img: "https://upload.wikimedia.org/wikipedia/commons/4/4e/London._British_Library%2C_Cotton_MS_Claudius_B_II._f.341r_%28cropped%29.jpg", page: "https://commons.wikimedia.org/wiki/File:London._British_Library,_Cotton_MS_Claudius_B_II._f.341r_(cropped).jpg", licence: "Public domain", artist: "Unknown Miniaturist, English (active 1170s in Cirenchester)" },
};

export function pictureFor(month: number, day: number): CommemorationPicture | null {
  return COMMEMORATION_PICTURES[`${month}-${day}`] ?? null;
}
