// ── The Hymnal 1982, sung ───────────────────────────────────────────────────
//
// Owner, 2026-09-18: "do a catalaouge with all these as a card and a search at
// the top, then a spotify open link with a spotify symbol on the right that
// would open and play in the spotify app? And then try to find each one for
// apple music as wll and put an apple symbol next to it. Also cross refrence
// the hymanl and put the hymn number on the leff."
//
// The recordings are Christopher Poore's public Spotify playlist "The Hymnal
// 1982, The Episcopal Church" (open.spotify.com/playlist/37L21QSJ4DEeWx40HxJZxc),
// which walks the hymnal in order from Hymn 1 to Hymn 169. Nothing of the
// hymnal is reproduced here: no texts, no tunes, no scores — only the NUMBER,
// which is a reference, and a link to a recording that is already published on
// the services. That matters, because the Hymnal 1982's texts and settings are
// under copyright (the same reason SlideDeckEditor tells editors to link to a
// song rather than paste its words).
//
// HOW THIS WAS BUILT (2026-09-18), so it can be redone when the playlist grows:
//   1. tracks   — open.spotify.com/embed/playlist/<id>, __NEXT_DATA__ JSON
//                 (trackList: title, subtitle, uri, duration). No credentials.
//   2. numbers  — hymnary.org/hymnal/EH1982, all 11 index pages, giving every
//                 number 1-720 with its first line; each track matched on a
//                 normalised title, then expanded across a tune PAIR (the
//                 hymnal often sets one text twice, e.g. 6 and 7), and eight
//                 matched by hand where the recording is named for its Latin
//                 incipit or its refrain.
//   3. apple    — itunes.apple.com/search (public, no key) per recording,
//                 scored on title + performer; appleTrackId is the Apple Music
//                 CATALOG id, which is what MusicKit needs to play a track
//                 in-app should Apple Music sign-in ever land here.
//
// ONE recording carries no number: "Verbum supernum prodiens", sung by
// Anonymous 4. The playlist puts it in Hymn 5's place, but Hymn 5 is "O
// splendor of God's glory bright" — a different Latin hymn — and the text
// belongs to 63/64. Rather than print a number that is probably wrong, it
// shows without one.

export type Hymn = {
  /** Hymnal 1982 number(s). Two when one text is set to two tunes. */
  num: number[];
  /** The recording's name, with arrangement and performer noise removed. */
  name: string;
  /** Performer(s), as the feed names them. */
  artist: string;
  /** The hymnal's own first line, when the index files it under something else. */
  firstLine: string | null;
  /** open.spotify.com track link — a universal link, so the phone hands it to
   *  the Spotify app when it is installed, and the web player otherwise. */
  spotifyUrl: string;
  /** music.apple.com track link, where a confident match was found. */
  appleUrl: string | null;
  /** Apple Music catalog track id (the `i=` on the link above). */
  appleTrackId: string | null;
  /** Length of the recording. */
  seconds: number;
};

export const HYMNS: readonly Hymn[] = [
  { num: [1, 2], name: "Father, We Praise Thee", artist: "Choir Of The Abbey School Tewkesbury", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0LZyhRImGhdSLiGdpFYael", appleUrl: "https://music.apple.com/us/album/father-we-praise-thee-arr-r-vaughan-williams/504402732?i=504402739&uo=4", appleTrackId: "504402739", seconds: 143 },
  { num: [3, 4], name: "Now That the Daylight Fills the Sky", artist: "Collegiate Church of St Mary Warwick Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0Mpn2Q71hZLHgf30uzZTOQ", appleUrl: "https://music.apple.com/us/album/melcombe-now-that-the-daylight-fills-the-sky/1561990301?i=1561990311&uo=4", appleTrackId: "1561990311", seconds: 141 },
  { num: [6, 7], name: "Christ whose glory fills the skies", artist: "Thomas Armstrong, The Choir of Canterbury Cathedral, Michael Harris", firstLine: null, spotifyUrl: "https://open.spotify.com/track/5S0bJULrfEHEShUPkZV2du", appleUrl: "https://music.apple.com/us/album/christ-whose-glory-fills-the-skies/276996953?i=276997018&uo=4", appleTrackId: "276997018", seconds: 275 },
  { num: [6, 7], name: "Christ Whose Glory Fills The Skies", artist: "The Scottish Festival Singers", firstLine: null, spotifyUrl: "https://open.spotify.com/track/1I2IZ20bbYe5GUs26VsOyF", appleUrl: "https://music.apple.com/us/album/christ-whose-glory-fills-the-skies/592888884?i=592888982&uo=4", appleTrackId: "592888982", seconds: 112 },
  { num: [8], name: "Morning Has Broken", artist: "Yusuf / Cat Stevens", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3BqqF8suAIzW8655yJfcvh", appleUrl: "https://music.apple.com/us/album/morning-has-broken/1586793228?i=1586793677&uo=4", appleTrackId: "1586793677", seconds: 200 },
  { num: [10], name: "New Every Morning Is the Love", artist: "Sheffield Cathedral Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/19gBZpBFUszWeSU9jfNVUa", appleUrl: "https://music.apple.com/us/album/new-every-morning-is-the-love/336136119?i=336136340&uo=4", appleTrackId: "336136340", seconds: 131 },
  { num: [11], name: "Awake, My Soul, And with the Sun", artist: "Norwich Cathedral Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/2eAJNjHFbU0FDdqoFMJdnd", appleUrl: "https://music.apple.com/us/album/awake-my-soul-with-the-sun/336136119?i=336136264&uo=4", appleTrackId: "336136264", seconds: 143 },
  { num: [12, 13], name: "The Golden Sun Lights Up the Sky", artist: "Anonymous, Los Angeles First Congregational Church Choir, Frederick Swann, Thomas Somerville", firstLine: null, spotifyUrl: "https://open.spotify.com/track/2ybVgh2eASUZhV4WUNhAfA", appleUrl: "https://music.apple.com/us/album/the-golden-sun-lights-up-the-sky-arr-r-vaughan-williams/504402732?i=504402740&uo=4", appleTrackId: "504402740", seconds: 127 },
  { num: [24], name: "The Day Thou Gavest", artist: "Chichester Cathedral Choir, Sarah Baldock", firstLine: null, spotifyUrl: "https://open.spotify.com/track/2g3vAHFuhF47QbGBEJ1Sjg", appleUrl: "https://music.apple.com/us/album/the-day-thou-gavest/378040838?i=378040962&uo=4", appleTrackId: "378040962", seconds: 207 },
  { num: [25, 26], name: "O Gracious Light", artist: "Schola Magdalena", firstLine: null, spotifyUrl: "https://open.spotify.com/track/2ZtDiJZi8qcAkWn5UO1pFh", appleUrl: "https://music.apple.com/us/album/o-gracious-light/316939914?i=316939985&uo=4", appleTrackId: "316939985", seconds: 80 },
  { num: [33, 34, 35], name: "Christ, Mighty Savior (Innisfree Farm)", artist: "Richard Wayne Dirksen, Scott Dettra, Choir of St. Paul's Parish, Jeffrey Smith", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3irYdgOM4zvBGnGNdJ6PG0", appleUrl: "https://music.apple.com/us/album/christ-mighty-savior-innisfree-farm-arr-for-mixed-chorus/1460046482?i=1460046499&uo=4", appleTrackId: "1460046499", seconds: 205 },
  { num: [33, 34, 35], name: "Christ, Mighty Savior", artist: "David Hurd, Beverly Hills All Saints' Church Choir, Craig Phillips, Thomas Foster", firstLine: null, spotifyUrl: "https://open.spotify.com/track/62kopHzCEwTrrE1x3CSBWX", appleUrl: "https://music.apple.com/us/album/christ-mighty-savior-arr-p-craig/385542034?i=385542152&uo=4", appleTrackId: "385542152", seconds: 184 },
  { num: [36], name: "O Gladsome Light", artist: "Louis Bourgeois, The Cambridge Singers, John Rutter", firstLine: null, spotifyUrl: "https://open.spotify.com/track/5cbMmFCclzKuT8LoFUHd2w", appleUrl: "https://music.apple.com/us/album/o-gladsome-light/445485160?i=445485299&uo=4", appleTrackId: "445485299", seconds: 119 },
  { num: [37], name: "O Brightness of the Immortal Father's Face", artist: "Gerald Near, Cathedral Choral Society, Eric Plutz, J. Reilly Lewis", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3X1r0RX0xNrRiLLEbhdExK", appleUrl: null, appleTrackId: null, seconds: 142 },
  { num: [42], name: "Now the Day Is Over", artist: "The Compline Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/2ApeFpp7oWAKbZPEaCYhIu", appleUrl: "https://music.apple.com/us/album/orison-now-the-day-is-over/744239330?i=744239475&uo=4", appleTrackId: "744239475", seconds: 113 },
  { num: [43], name: "All Praise To Thee, My God, This Night", artist: "Thomas Tallis, The Choir of Trinity College, Melbourne, Michael Leighton Jones", firstLine: null, spotifyUrl: "https://open.spotify.com/track/4iBHKSgKsE0UlTIm5P2ElC", appleUrl: "https://music.apple.com/us/album/all-praise-to-thee-my-god-this-night-arr-michael-leighton/1583521321?i=1583521888&uo=4", appleTrackId: "1583521888", seconds: 142 },
  { num: [44, 45], name: "To You Before the Close of Day", artist: "The National Lutheran Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0BogdCDdXXoDNTvwnvc5mb", appleUrl: "https://music.apple.com/us/album/to-you-before-the-close-of-day/694190965?i=694191649&uo=4", appleTrackId: "694191649", seconds: 264 },
  { num: [46], name: "The Duteous Day Now Closeth", artist: "Collegiate Church of St Mary Warwick Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/6PnfEMd6K7V0xUVvJekexz", appleUrl: "https://music.apple.com/us/album/innsbruck-the-duteous-day-now-closeth-after-h-isaacs/1561990301?i=1561990314&uo=4", appleTrackId: "1561990314", seconds: 185 },
  { num: [47], name: "On This Day, The First of Days", artist: "Choir of Keble College, Oxford", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3p7zKoLvLbAuhnLk8ZPZYD", appleUrl: "https://music.apple.com/us/album/on-this-day-the-first-of-days/336167721?i=336167972&uo=4", appleTrackId: "336167972", seconds: 103 },
  { num: [49], name: "Come, Let Us with Our Lord Arise", artist: "Gloucester Cathedral Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3y7BJtUkAQzOJ8ydVWemIx", appleUrl: "https://music.apple.com/us/album/gloucester-come-let-us-with-our-lord-arise/1561640593?i=1561640710&uo=4", appleTrackId: "1561640710", seconds: 126 },
  { num: [53], name: "Once He Came in Blessing", artist: "The Seminary Chorus", firstLine: null, spotifyUrl: "https://open.spotify.com/track/6RT7ubdtUizwMlXk34GKvD", appleUrl: "https://music.apple.com/us/album/once-he-came-in-blessing/1353695632?i=1353695666&uo=4", appleTrackId: "1353695666", seconds: 174 },
  { num: [54], name: "Savior of the Nations, Come", artist: "Laestadian Lutheran Church", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0VG0BV5QLpJkGTKFIjt7mF", appleUrl: "https://music.apple.com/us/album/savior-of-the-nations-come-shz-12/1299131060?i=1299131066&uo=4", appleTrackId: "1299131066", seconds: 200 },
  { num: [56], name: "O Come, O Come, Emmanuel! (Veni Emmanuel)", artist: "Traditional, Choir of King's College, Cambridge, Stephen Cleobury", firstLine: null, spotifyUrl: "https://open.spotify.com/track/6Lub2WGns5ZZbOe3Hbq57m", appleUrl: "https://music.apple.com/us/album/o-come-o-come-emmanuel-veni-emmanuel/1415215912?i=1415216200&uo=4", appleTrackId: "1415216200", seconds: 257 },
  { num: [57, 58], name: "Lo! He Comes With Clouds Descending", artist: "Charles Wesley, The Cambridge Singers, John Scott, City of London Sinfonia, John Rutter", firstLine: null, spotifyUrl: "https://open.spotify.com/track/5D2q1fu9xBB2E3RZ4up8bC", appleUrl: "https://music.apple.com/us/album/lo-he-comes-with-clouds-descending-arr-j-rutter-for/444874206?i=444874227&uo=4", appleTrackId: "444874227", seconds: 255 },
  { num: [59], name: "Hark! A Thrilling Voice Is Sounding", artist: "William Henry Monk, Choir of King's College, Cambridge, Simon Preston, Sir David Willcocks", firstLine: null, spotifyUrl: "https://open.spotify.com/track/1SassjGe2Fh4AB7p7XfIP1", appleUrl: "https://music.apple.com/us/album/hark-a-thrilling-voice-is-sounding-%E3%83%8F%E3%83%BC%E3%82%AF-%E3%82%A2-%E3%82%B9%E3%83%AA%E3%83%AA%E3%83%B3%E3%82%B0-%E3%83%9C%E3%82%A4%E3%82%B9-%E3%82%A4%E3%82%BA-%E3%82%B5%E3%82%A6%E3%83%B3%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0/1322240422?i=1322240706&uo=4", appleTrackId: "1322240706", seconds: 179 },
  { num: [60], name: "Creator of the Stars of Night: Advent Vesper Hymn", artist: "Gregorian Chant Schola of Saint Meinrad Archabbey", firstLine: null, spotifyUrl: "https://open.spotify.com/track/1RniGDmJzYU0vG58WWTJC7", appleUrl: "https://music.apple.com/us/album/creator-of-the-stars-of-night-advent-vesper-hymn/1056434050?i=1056435051&uo=4", appleTrackId: "1056435051", seconds: 134 },
  { num: [61, 62], name: "Sleepers, Wake", artist: "Choir Of St. Paul's Catherdral", firstLine: null, spotifyUrl: "https://open.spotify.com/track/2liHHpK9UB7kXYr5AA0PGR", appleUrl: "https://music.apple.com/us/album/sleepers-wake-zion-hears-the-watchmens-voices/1172632045?i=1172632271&uo=4", appleTrackId: "1172632271", seconds: 270 },
  { num: [63, 64], name: "O Heavenly Word, Eternal Light", artist: "The Schola Cantorum of St. Peter's in the Loop", firstLine: null, spotifyUrl: "https://open.spotify.com/track/6l22xj8mVj7oxeZqXB8Ee9", appleUrl: "https://music.apple.com/us/album/o-heavenly-word-eternal-light-o-heiland-reiss/1584708528?i=1584708532&uo=4", appleTrackId: "1584708532", seconds: 105 },
  { num: [66], name: "Come, Thou Long-Expected Jesus (Stuttgart) - 1. Come, Thou Long-Expected Jesus", artist: "Methodist Central Hall Choir, Westminster, John Chapman, Epworth Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/6HukQn1x3yLXySxkii4lVa", appleUrl: "https://music.apple.com/us/album/come-thou-long-expected-jesus-stuttgart-i-come-thou/1294667947?i=1294669298&uo=4", appleTrackId: "1294669298", seconds: 36 },
  { num: [66], name: "Come, Thou Long-Expected Jesus (Stuttgart) - 2. Israel's Strength and Consolation", artist: "Methodist Central Hall Choir, Westminster, John Chapman, Epworth Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0FSjrxy2s18eYv9IeFN6PQ", appleUrl: "https://music.apple.com/us/album/come-thou-long-expected-jesus-stuttgart-ii-israels/1294667947?i=1294669299&uo=4", appleTrackId: "1294669299", seconds: 23 },
  { num: [66], name: "Come, Thou Long-Expected Jesus (Stuttgart) - 3. Born Thy People to Deliver", artist: "Methodist Central Hall Choir, Westminster, John Chapman, Epworth Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3Gkwr0iBaPBFL2qXX1zinE", appleUrl: "https://music.apple.com/us/album/come-thou-long-expected-jesus-stuttgart-iii-born-thy/1294667947?i=1294669300&uo=4", appleTrackId: "1294669300", seconds: 21 },
  { num: [66], name: "Come, Thou Long-Expected Jesus (Stuttgart) - 4. by Thine Own Eternal Spirit", artist: "Methodist Central Hall Choir, Westminster, John Chapman, Epworth Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0W85YFBwjcMVVH6byUentX", appleUrl: "https://music.apple.com/us/album/come-thou-long-expected-jesus-stuttgart-iv-by-thine/1294667947?i=1294669162&uo=4", appleTrackId: "1294669162", seconds: 25 },
  { num: [71, 72], name: "Hark the Glad Sound!", artist: "Liverpool Metropolitan Cathedral Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/2dj67ALEtbylZk1eDdcias", appleUrl: "https://music.apple.com/us/album/hark-the-glad-sound/478106195?i=478106492&uo=4", appleTrackId: "478106492", seconds: 114 },
  { num: [75], name: "There's A Voice In The Wilderness Crying", artist: "The Schola Cantorum of St. Peter's in the Loop", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0r4T5HcZfim4bL90kQoHRA", appleUrl: "https://music.apple.com/us/album/theres-a-voice-in-the-wilderness-crying/299120175?i=299120203&uo=4", appleTrackId: "299120203", seconds: 140 },
  { num: [76], name: "On Jordan's Bank the Baptist's Cry", artist: "Newcastle Cathedral Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/5J5udyElXZZllPqwaTn7xl", appleUrl: "https://music.apple.com/us/album/on-jordans-bank-the-baptists-cry/477832142?i=477833669&uo=4", appleTrackId: "477833669", seconds: 145 },
  { num: [78, 79], name: "O Little Town Of Bethlehem", artist: "Anonymous, Choir of King's College, Cambridge, Andrew Davis, Sir David Willcocks", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0Td2YOtRWvD6m1LP8VplZG", appleUrl: "https://music.apple.com/us/album/o-little-town-of-bethlehem/1778644304?i=1778644704&uo=4", appleTrackId: "1778644704", seconds: 190 },
  { num: [80], name: "From Heaven Above to Earth I Come", artist: "The Trinity Choir of St. Paul's Chapel", firstLine: null, spotifyUrl: "https://open.spotify.com/track/6hqrXDYMEh1ySfUdCQXuys", appleUrl: "https://music.apple.com/us/album/from-heaven-above-to-earth-i-come-von-himmel-hoch/1582546376?i=1582546484&uo=4", appleTrackId: "1582546484", seconds: 219 },
  { num: [81], name: "Lo, How a Rose E'er Blooming", artist: "The Cathedral Singers, Richard Proulx", firstLine: null, spotifyUrl: "https://open.spotify.com/track/61k1WNViV1WGbZQNZsASTJ", appleUrl: null, appleTrackId: null, seconds: 176 },
  { num: [82], name: "Of the Father's Love Begotten", artist: "The West Coast Mennonite Chamber Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/4DEQ4t4d1w7BbC8nznBbBf", appleUrl: "https://music.apple.com/us/album/of-the-fathers-love-begotten/1228280848?i=1228281078&uo=4", appleTrackId: "1228281078", seconds: 186 },
  { num: [83], name: "O Come, All Ye Faithful", artist: "John Francis Wade, Choir of King's College, Cambridge, Stephen Cleobury, Douglas Tang", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3G98E0Ywi8wors3UX6NBos", appleUrl: "https://music.apple.com/us/album/o-come-all-ye-faithful/479765582?i=479765610&uo=4", appleTrackId: "479765610", seconds: 269 },
  { num: [84], name: "Love came down at Christmas", artist: "RO Morris, Stephen Cleobury, Henry Websdale, Choir of King's College, Cambridge", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0NiyNNvXwEHzEgGN3RsFaK", appleUrl: null, appleTrackId: null, seconds: 78 },
  { num: [87], name: "Hark! The Herald Angels Sing", artist: "The Oxford Trinity Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/75hZoLDeZ3OgOxxdW2RRtr", appleUrl: "https://music.apple.com/us/album/hark-the-herald-angels-sing/1650319526?i=1650319534&uo=4", appleTrackId: "1650319534", seconds: 230 },
  { num: [89, 90], name: "It Came Upon the Midnight Clear", artist: "Arthur Sullivan, English Traditional, Choir of King's College, Cambridge, Stephen Cleobury, Tom Etheridge", firstLine: null, spotifyUrl: "https://open.spotify.com/track/4IjxQRIgbJF7Yd4u9OuYj4", appleUrl: null, appleTrackId: null, seconds: 204 },
  { num: [91], name: "Break forth, O beauteous heavenly light", artist: "Johann Sebastian Bach, Stephen Cleobury, Donal McCann, Choir of King's College, Cambridge", firstLine: null, spotifyUrl: "https://open.spotify.com/track/6v4WVTdF6yEjRoJgzgypxO", appleUrl: "https://music.apple.com/us/album/break-forth-o-beauteous-heavenly-light/1439384469?i=1439384673&uo=4", appleTrackId: "1439384673", seconds: 75 },
  { num: [92], name: "On This Day Earth Shall Ring", artist: "Traditional, The Los Angeles Chorale, Neville Garvey", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0aKrllp5EMttz0O4EGXslK", appleUrl: "https://music.apple.com/us/album/on-this-day-earth-shall-ring/294711730?i=294711768&uo=4", appleTrackId: "294711768", seconds: 209 },
  { num: [93], name: "Angels from the Realms of Glory", artist: "The Bach Choir Of Bethlehem", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0m0gkXHmRG0p2tRkx7AxRr", appleUrl: null, appleTrackId: null, seconds: 135 },
  { num: [94, 95], name: "While Shepherds Watched Their Flocks", artist: "Traditional, Choir of King's College, Cambridge, John Wells, Sir David Willcocks", firstLine: null, spotifyUrl: "https://open.spotify.com/track/2UhuRBJq0AciZjXXxKYNQp", appleUrl: "https://music.apple.com/us/album/while-shepherds-watched-their-flocks-arr-willcocks/1655686915?i=1655687803&uo=4", appleTrackId: "1655687803", seconds: 171 },
  { num: [96], name: "Angels We Have Heard on High", artist: "Traditional, Westminster Choir, Daniel Beckwith, Philadelphia Concerto Soloists, Joseph Flummerfelt", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0qIBJImJ0AWN9u4Z1VJm7x", appleUrl: "https://music.apple.com/us/album/angels-we-have-heard-on-high/479765582?i=479765613&uo=4", appleTrackId: "479765613", seconds: 143 },
  { num: [97], name: "Dost Thou In A Manger Lie?", artist: "The Schola Cantorum of St. Peter's in the Loop, Deward Rahm, Organist, The Kithara Trio, J Michael Thompson", firstLine: null, spotifyUrl: "https://open.spotify.com/track/5IPsNr3PGi4OmVEZ0XBj5K", appleUrl: "https://music.apple.com/us/album/dost-thou-in-a-manger-lie-feat-deward-rahm-organist/403558865?i=403559121&uo=4", appleTrackId: "403559121", seconds: 226 },
  { num: [98], name: "Unto Us a Boy Is Born", artist: "St. Paul's Cathedral Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3GkS3cbEor2zKGBzf8BLx8", appleUrl: "https://music.apple.com/us/album/unto-us-a-boy-is-born/465617702?i=465617945&uo=4", appleTrackId: "465617945", seconds: 139 },
  { num: [99], name: "Go Tell It On the Mountain", artist: "Mahalia Jackson", firstLine: "While shepherds kept their watching", spotifyUrl: "https://open.spotify.com/track/69wtmAd9vZYkoemHJXRZtv", appleUrl: "https://music.apple.com/us/album/go-tell-it-on-the-mountain/1032609846?i=1032610125&uo=4", appleTrackId: "1032610125", seconds: 165 },
  { num: [100], name: "Joy to the World", artist: "George Frideric Handel, Westminster Choir, Daniel Beckwith, Philadelphia Concerto Soloists, Joseph Flummerfelt", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0n1SmbnGQxAaERbTF57pnh", appleUrl: null, appleTrackId: null, seconds: 88 },
  { num: [101], name: "Away in a Manger", artist: "William J. Kirkpatrick, Choir of King's College, Cambridge, Philip Ledger", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3Bb1USwadcdtE1zPxJLSBv", appleUrl: "https://music.apple.com/us/album/away-in-a-manger/1435551048?i=1435551166&uo=4", appleTrackId: "1435551166", seconds: 130 },
  { num: [102], name: "Once in royal David's city", artist: "Henry John Gauntlett, AH Mann, Stephen Cleobury, Choir of King's College, Cambridge", firstLine: null, spotifyUrl: "https://open.spotify.com/track/4lOKpQ5bMtJzyRprkZNel9", appleUrl: null, appleTrackId: null, seconds: 263 },
  { num: [104], name: "A Stable Lamp Is Lighted", artist: "David Hurd, Beverly Hills All Saints' Church Choir, William Wood, Craig Phillips, Thomas Foster", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3bRwPox7Z63MR3j7us1Ik2", appleUrl: null, appleTrackId: null, seconds: 221 },
  { num: [105], name: "God Rest You Merry, Gentlemen", artist: "Traditional, Choir of King's College, Cambridge, Benjamin Bayl, Stephen Cleobury", firstLine: null, spotifyUrl: "https://open.spotify.com/track/5boRRi7JwxW5MbwZdrDvr1", appleUrl: "https://music.apple.com/us/album/god-rest-you-merry-gentlemen/691863106?i=691864554&uo=4", appleTrackId: "691864554", seconds: 215 },
  { num: [106], name: "Christians Awake!", artist: "Choir of The King's School", firstLine: null, spotifyUrl: "https://open.spotify.com/track/6ZwTlAiZqCjOYphPjiD2k0", appleUrl: null, appleTrackId: null, seconds: 272 },
  { num: [107], name: "Good Christian Friends, Rejoice", artist: "OCP Session Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/6FTEEssPAaBG6QdaLvNnjz", appleUrl: null, appleTrackId: null, seconds: 118 },
  { num: [109], name: "The First Nowell", artist: "Traditional, Choir of King's College, Cambridge, Francis Grier, Philip Ledger", firstLine: null, spotifyUrl: "https://open.spotify.com/track/22cx3KWuWBiOw8a0NmYUh3", appleUrl: null, appleTrackId: null, seconds: 293 },
  { num: [110], name: "The Snow Lay On the Ground", artist: "Sanctuary Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/38RmsmNeYVhZcnMB9X6Lro", appleUrl: null, appleTrackId: null, seconds: 223 },
  { num: [111], name: "Silent Night, Holy Night", artist: "The Oxford Trinity Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/7Bl9TARGQiZ6lIdfLyEsF0", appleUrl: null, appleTrackId: null, seconds: 190 },
  { num: [112], name: "In the Bleak Midwinter", artist: "St Cyprian's Episcopal Singers, The Stephen F Austin A Cappella Choir, Tim King, S. Greg Simmons", firstLine: null, spotifyUrl: "https://open.spotify.com/track/4rNpt0IYya4XDImeomqn2b", appleUrl: "https://music.apple.com/us/album/in-the-bleak-midwinter/1231118143?i=1231118161&uo=4", appleTrackId: "1231118161", seconds: 204 },
  { num: [113], name: "Duermete, nino lindo", artist: "Traditional, Catherine Robinson, Jon Lee Keenan, Rosalind Simpson, Santa Fe Desert Chorale, Linda Mack", firstLine: "Duérmete, Niño lindo (Oh sleep now, holy baby)", spotifyUrl: "https://open.spotify.com/track/0hv19eNgX5RYVyK7jllYDl", appleUrl: null, appleTrackId: null, seconds: 174 },
  { num: [114], name: "Twas in the Moon of Wintertime (The Huron Carol)", artist: "Musica Sacra", firstLine: null, spotifyUrl: "https://open.spotify.com/track/6wyvD7NIITKUHBWoVvNlVm", appleUrl: "https://music.apple.com/us/album/twas-in-the-moon-of-wintertime-the-huron-carol/1065303817?i=1065303819&uo=4", appleTrackId: "1065303819", seconds: 146 },
  { num: [115], name: "What Child Is This?", artist: "The Cathedral Singers, Richard Proulx", firstLine: null, spotifyUrl: "https://open.spotify.com/track/2Zm60TUk5nElYuiLLaNih8", appleUrl: "https://music.apple.com/us/album/what-child-is-this/1540191041?i=1540191046&uo=4", appleTrackId: "1540191046", seconds: 146 },
  { num: [119], name: "As With Gladness Men of Old (Dix)", artist: "Conrad Kocher, William Henry Monk, Choir of King's College, Cambridge, Stephen Cleobury", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0FL3Il93xZqolo5xEx2G1M", appleUrl: "https://music.apple.com/us/album/as-with-gladness-men-of-old-dix/1415215912?i=1415216195&uo=4", appleTrackId: "1415216195", seconds: 191 },
  { num: [120], name: "The Sinless One to Jordan Came", artist: "Llandaff Cathedral Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/1dihS9Q9M64fGzknvpSx2a", appleUrl: "https://music.apple.com/us/album/the-sinless-one-to-jordan-came-solothurn-instrumental/636285944?i=636286585&uo=4", appleTrackId: "636286585", seconds: 195 },
  { num: [122, 123], name: "Alleluia, Song of Gladness", artist: "Anonymous, Beverly Hills All Saints' Church Choir, Thomas Foster", firstLine: null, spotifyUrl: "https://open.spotify.com/track/7rwXI9IZzIK1t6vD92LZ6p", appleUrl: null, appleTrackId: null, seconds: 147 },
  { num: [122, 123], name: "Tibi Christe, splendor Patris (Alleluia, Song of Gladness)", artist: "Anonymous, St. Mark's Cathedral Choir, Brian Fairbanks, J. Melvin Butler", firstLine: "Alleluia, song of gladness", spotifyUrl: "https://open.spotify.com/track/4yvW1M7NKWD1rl7MxtEHJq", appleUrl: null, appleTrackId: null, seconds: 155 },
  { num: [124], name: "What Star Is This With Beams So Bright", artist: "University Of Texas Chamber Singers", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3lSfXnFtwpwGFxoBLMreUm", appleUrl: "https://music.apple.com/us/album/what-star-is-this-with-beams-so-bright/1784578050?i=1784578491&uo=4", appleTrackId: "1784578491", seconds: 174 },
  { num: [125, 126], name: "the People Who in Darkness Walked", artist: "Church of the Ascension and Saint Agnes Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/6vRP6nDPJUX9QtLTdDmcaY", appleUrl: "https://music.apple.com/us/album/hymn-the-people-who-in-darkness-walked-perry/271011134?i=271011201&uo=4", appleTrackId: "271011201", seconds: 163 },
  { num: [127], name: "Earth Has Many a Noble City", artist: "Priory Singers, belfast.", firstLine: null, spotifyUrl: "https://open.spotify.com/track/67wa7X9O09LAPS0Eh63FLB", appleUrl: "https://music.apple.com/us/album/earth-has-many-a-noble-city-stuttgart-organ/1656796847?i=1656796867&uo=4", appleTrackId: "1656796867", seconds: 131 },
  { num: [128], name: "We three kings of Orient are", artist: "John Henry Hopkins, Choir of King's College, Cambridge, Henry Websdale, Stephen Cleobury", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3wThdl0vcRImzzIHWH63rq", appleUrl: "https://music.apple.com/us/album/we-three-kings-of-orient-are-arr-martin-neary/1439384469?i=1439384661&uo=4", appleTrackId: "1439384661", seconds: 187 },
  { num: [129, 130], name: "Christ Upon the Mountain Peak: Christ, upon the mountain peak", artist: "Grace Cathedral Choir, Christopher Putnam, John Fernstermaker", firstLine: null, spotifyUrl: "https://open.spotify.com/track/2LeQH7cTYRCdOXgzEW1z9A", appleUrl: null, appleTrackId: null, seconds: 153 },
  { num: [129, 130], name: "Christ, Upon the Mountain Peak", artist: "Choir Of The Abbey School Tewkesbury", firstLine: null, spotifyUrl: "https://open.spotify.com/track/4AYgHmLqGEIqZVTDacMCpP", appleUrl: null, appleTrackId: null, seconds: 170 },
  { num: [133, 134], name: "O Light of Light, Love Given Birth", artist: "Cary Ratcliff, St. Mark's Cathedral Choir, Thomas Joyce, J. Melvin Butler", firstLine: null, spotifyUrl: "https://open.spotify.com/track/3o7s1d2HBtTlmVVWWzEqwx", appleUrl: null, appleTrackId: null, seconds: 137 },
  { num: [135], name: "Songs of Thankfulness and Praise", artist: "Jakob Hintze, Christopher Woodsworth", firstLine: null, spotifyUrl: "https://open.spotify.com/track/4Zf5BsXQ5jRJH04MVMiNyt", appleUrl: null, appleTrackId: null, seconds: 157 },
  { num: [136, 137], name: "Aeterne Rex altissime, O nata Lux de Lumine (O Wondrous Type! O Vision Fair)", artist: "William Knapp, St. Mark's Cathedral Choir, J. Melvin Butler", firstLine: "O wondrous type! O vision fair", spotifyUrl: "https://open.spotify.com/track/08fmM5rUDtuD44NDrfxztx", appleUrl: null, appleTrackId: null, seconds: 214 },
  { num: [140, 141], name: "Wilt thou forgive that sinne (An Hymne to God the Father)", artist: "John Hilton, Paul Hillier, John Donne, Nigel North", firstLine: null, spotifyUrl: "https://open.spotify.com/track/7AYPZD6sdNpSoWycYDdy2z", appleUrl: "https://music.apple.com/us/album/wilt-thou-forgive-that-sinne-an-hymne-to-god-the-father/584930302?i=584930565&uo=4", appleTrackId: "584930565", seconds: 139 },
  { num: [142], name: "Lord, Who Throughout These Forty Days", artist: "Claudia F. Hernaman, Richard Redhead", firstLine: null, spotifyUrl: "https://open.spotify.com/track/1Hifoq80M019TRKQEZnfmm", appleUrl: "https://music.apple.com/us/album/lord-who-throughout-these-forty-days/1526398013?i=1526398014&uo=4", appleTrackId: "1526398014", seconds: 158 },
  { num: [143], name: "The Glory of These Forty Days", artist: "Gregory the Great", firstLine: null, spotifyUrl: "https://open.spotify.com/track/425zdNm7ew1h2U7m04Dk4M", appleUrl: null, appleTrackId: null, seconds: 151 },
  { num: [146, 147], name: "Ex more docti mystico", artist: "Anonymous, Saint Frideswide Monks and Novices", firstLine: "Now let us all with one accord", spotifyUrl: "https://open.spotify.com/track/2aNZp0yvmmKyuEiEzRVXrI", appleUrl: "https://music.apple.com/us/album/ex-more-docti-mystico/825825692?i=825829038&uo=4", appleTrackId: "825829038", seconds: 115 },
  { num: [148], name: "Creator Of The Earth And Skies", artist: "Choir Of Yorkminster Park Baptist Church", firstLine: null, spotifyUrl: "https://open.spotify.com/track/28lwVVLt03vZRt9USH7vsO", appleUrl: "https://music.apple.com/us/album/creator-of-the-earth-and-skies/218468358?i=218468987&uo=4", appleTrackId: "218468987", seconds: 152 },
  { num: [150], name: "Forty Days and Forty Nights", artist: "Gloucester Cathedral Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/48beOyP1ScwzqSyYIkisJz", appleUrl: "https://music.apple.com/us/album/forty-days-and-forty-nights-aus-der-tiefe/1727401572?i=1727402351&uo=4", appleTrackId: "1727402351", seconds: 154 },
  { num: [152], name: "Kind Maker of the World", artist: "Discover Worship", firstLine: null, spotifyUrl: "https://open.spotify.com/track/7ckbEK1wyBI1QDd2O3Z9OX", appleUrl: null, appleTrackId: null, seconds: 183 },
  { num: [154, 155], name: "All Glory, Laud and Honor", artist: "Melchior Teschner, Cathedral Choral Society, Nicholas White, Gisele Becker", firstLine: "Thou art the King of Israel", spotifyUrl: "https://open.spotify.com/track/2CjiGwyAe39k5eOXPTfJKe", appleUrl: "https://music.apple.com/us/album/all-glory-laud-and-honor/1526398013?i=1526398794&uo=4", appleTrackId: "1526398794", seconds: 157 },
  { num: [156], name: "Ride On! Ride On in Majesty!", artist: "Graham George, William Neil", firstLine: null, spotifyUrl: "https://open.spotify.com/track/4bozEs2pGZVQJa5qER9RI6", appleUrl: null, appleTrackId: null, seconds: 147 },
  { num: [158], name: "Ah Holy Jesus How Hast Thou Offended (HERZLIEBSTER JESU)", artist: "The Redeemer Choir Austin Texas", firstLine: null, spotifyUrl: "https://open.spotify.com/track/00QH6VqleiXWNr9SVYzCJU", appleUrl: "https://music.apple.com/us/album/ah-holy-jesus-how-hast-thou-offended-herzliebster-jesu/1584708528?i=1584708668&uo=4", appleTrackId: "1584708668", seconds: 203 },
  { num: [159], name: "Stabat Mater \"At the Cross Her Station Keeping\"", artist: "Anonymous, Wakefield Cathedral Choir, Louise Marsh, Jonathan Bielby", firstLine: "At the cross her vigil keeping", spotifyUrl: "https://open.spotify.com/track/7kMS5YXVsshnJVAg4GSSt0", appleUrl: null, appleTrackId: null, seconds: 285 },
  { num: [160], name: "Cross of Jesus, Cross of Sorrow", artist: "John Stainer, Beverly Hills All Saints' Church Choir, Craig Phillips, Thomas Foster", firstLine: null, spotifyUrl: "https://open.spotify.com/track/7qQxSh3LxL8bPVu179Fq50", appleUrl: "https://music.apple.com/us/album/cross-of-jesus-cross-of-sorrow/385542034?i=385542217&uo=4", appleTrackId: "385542217", seconds: 125 },
  { num: [162], name: "Vexilla regis prodeunt \"The Royal Banners Forward Go\"", artist: "Anonymous, Ely Cathedral Choir, Jonathan Lilley, Paul Trepte", firstLine: "The royal banners forward go", spotifyUrl: "https://open.spotify.com/track/2L3zTpq0q6zLyuqyArIsj7", appleUrl: null, appleTrackId: null, seconds: 255 },
  { num: [164], name: "Alone Thou Goest Forth, O Lord", artist: "Michael Thomson, Choir of St. Machar’s Cathedral", firstLine: null, spotifyUrl: "https://open.spotify.com/track/2Ok9PpUdJctS8MooooTViA", appleUrl: null, appleTrackId: null, seconds: 196 },
  { num: [165, 166], name: "Pange lingua \"Sing, My Tongue, the Glorious Battle\"", artist: "Anonymous, Ely Cathedral Choir, Jonathan Lilley, Paul Trepte", firstLine: "Sing, my tongue, the glorious battle", spotifyUrl: "https://open.spotify.com/track/5uzv2KPNxrXLqKwvvOn75r", appleUrl: null, appleTrackId: null, seconds: 177 },
  { num: [167], name: "There Is A Green Hill Far Away", artist: "St. Michael's Choir", firstLine: null, spotifyUrl: "https://open.spotify.com/track/0L20tAr9V4fHiw57fypxXB", appleUrl: null, appleTrackId: null, seconds: 143 },
  { num: [168, 169], name: "Passion Chorale \"O Sacred Head, Now Wounded\"", artist: "Anonymous, The Choir of Llandaff Cathedral, Michael Hoeg, Richard Moorhouse", firstLine: "O sacred head, sore wounded", spotifyUrl: "https://open.spotify.com/track/7dzf7KaYQsWq0s3W71qZf3", appleUrl: "https://music.apple.com/us/album/passion-chorale-o-sacred-head-now-wounded-after-h-l-hassler/1564292901?i=1564292904&uo=4", appleTrackId: "1564292904", seconds: 305 },
  { num: [], name: "Verbum supernum prodiens (Chant)", artist: "Anonymous, Anonymous 4", firstLine: null, spotifyUrl: "https://open.spotify.com/track/1kaMAmAGxHiP0OkZw3L9hc", appleUrl: null, appleTrackId: null, seconds: 144 },
];

/** "154, 155" — how a hymn's number reads on its card and in search. */
export function hymnNumberLabel(h: Hymn): string {
  return h.num.length ? h.num.join(", ") : "—";
}
