// ── Album covers, matched against Apple's catalogue ─────────────────────────
//
// GENERATED by scripts/fetch-track-artwork.mjs — do not hand-edit; rerun it
// when a catalogue changes (owner, 2026-09-19: "Match the YouTube's with the
// Apple catalogue so we can have album covers").
//
// YouTube holds the recording, Apple holds the sleeve. A track is here only
// when the title AND the artist agreed; anything short of that has no entry
// and keeps the headphones placeholder, because a wrong sleeve tells somebody
// they listened to a record they did not.
//
// 86 of 104 tracks matched.

/** Keyed by the catalogue's route and the track's number: "/hildegard#3". */
const ARTWORK: Record<string, string> = {
  "/hildegard#1": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/8f/13/92/8f1392c5-d1a3-f79c-a03f-eb6f30ebe9e9/s05.nesbyjrd.jpg/600x600bb.jpg",
  "/hildegard#4": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/a4/7a/11/a47a1102-fc4e-d514-08ff-9dcd3cf9bf5d/artwork.jpg/600x600bb.jpg",
  "/hildegard#5": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/8f/13/92/8f1392c5-d1a3-f79c-a03f-eb6f30ebe9e9/s05.nesbyjrd.jpg/600x600bb.jpg",
  "/hildegard#7": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/6d/85/be/6d85bee4-2772-2b25-333b-5678caa57a61/23UMGIM97085.rgb.jpg/600x600bb.jpg",
  "/hildegard#9": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/8f/13/92/8f1392c5-d1a3-f79c-a03f-eb6f30ebe9e9/s05.nesbyjrd.jpg/600x600bb.jpg",
  "/hildegard#10": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/fb/b6/38/fbb6382f-9327-dd97-3cee-3d831fa2f3e5/22CRGIM32667.rgb.jpg/600x600bb.jpg",
  "/hildegard#11": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/50/a8/aa/50a8aaaa-1b91-02d6-ec51-cfbefef4f142/23UM1IM28666.rgb.jpg/600x600bb.jpg",
  "/hildegard#13": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/8f/13/92/8f1392c5-d1a3-f79c-a03f-eb6f30ebe9e9/s05.nesbyjrd.jpg/600x600bb.jpg",
  "/hildegard#14": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/a1/a8/e9/a1a8e994-3908-19a4-e296-7d1f3728c717/cover.jpg/600x600bb.jpg",
  "/hildegard#15": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/5f/c1/1b/5fc11bc5-dbcc-3ede-ca8f-3cecf43bb0bd/23UMGIM68765.rgb.jpg/600x600bb.jpg",
  "/hildegard#17": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/8f/13/92/8f1392c5-d1a3-f79c-a03f-eb6f30ebe9e9/s05.nesbyjrd.jpg/600x600bb.jpg",
  "/hildegard#18": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/71/37/a4/7137a4b4-91d5-7065-4df2-d2dc0e67df43/25UMGIM46259.rgb.jpg/600x600bb.jpg",
  "/hildegard#19": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/5f/c1/1b/5fc11bc5-dbcc-3ede-ca8f-3cecf43bb0bd/23UMGIM68765.rgb.jpg/600x600bb.jpg",
  "/hildegard#21": "https://is1-ssl.mzstatic.com/image/thumb/Music/3f/77/0a/mzi.mbdpdidc.jpg/600x600bb.jpg",
  "/hildegard#22": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/b7/98/1f/b7981f5c-5d37-3565-69bd-9c58269633d5/21CRGIM27528.rgb.jpg/600x600bb.jpg",
  "/hildegard#23": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/5f/c1/1b/5fc11bc5-dbcc-3ede-ca8f-3cecf43bb0bd/23UMGIM68765.rgb.jpg/600x600bb.jpg",
  "/hildegard#25": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/5f/c1/1b/5fc11bc5-dbcc-3ede-ca8f-3cecf43bb0bd/23UMGIM68765.rgb.jpg/600x600bb.jpg",
  "/hildegard#26": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/a1/a8/e9/a1a8e994-3908-19a4-e296-7d1f3728c717/cover.jpg/600x600bb.jpg",
  "/hildegard#27": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/5f/c1/1b/5fc11bc5-dbcc-3ede-ca8f-3cecf43bb0bd/23UMGIM68765.rgb.jpg/600x600bb.jpg",
  "/hildegard#28": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/06/9d/78/069d783e-4d07-db1b-97ad-f6eaa7793406/21UM1IM21923.rgb.jpg/600x600bb.jpg",
  "/hildegard#29": "https://is1-ssl.mzstatic.com/image/thumb/Music111/v4/27/e1/5d/27e15d49-d7a9-15a9-f7dc-19f10307753b/QT00174037.jpg/600x600bb.jpg",
  "/hildegard#30": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/fb/b6/38/fbb6382f-9327-dd97-3cee-3d831fa2f3e5/22CRGIM32667.rgb.jpg/600x600bb.jpg",
  "/hildegard#31": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/5f/c1/1b/5fc11bc5-dbcc-3ede-ca8f-3cecf43bb0bd/23UMGIM68765.rgb.jpg/600x600bb.jpg",
  "/hildegard#32": "https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/79/6d/7b/796d7b93-5f47-d817-7481-f1f069cd2779/00602517332195.rgb.jpg/600x600bb.jpg",
  "/hildegard#33": "https://is1-ssl.mzstatic.com/image/thumb/Music111/v4/27/e1/5d/27e15d49-d7a9-15a9-f7dc-19f10307753b/QT00174037.jpg/600x600bb.jpg",
  "/hildegard#34": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/31/f6/42/31f642aa-0576-ea5e-b5bd-2d6527e8cb0b/8720205730268.png/600x600bb.jpg",
  "/hildegard#37": "https://is1-ssl.mzstatic.com/image/thumb/Music111/v4/27/e1/5d/27e15d49-d7a9-15a9-f7dc-19f10307753b/QT00174037.jpg/600x600bb.jpg",
  "/hildegard#38": "https://is1-ssl.mzstatic.com/image/thumb/Music111/v4/27/e1/5d/27e15d49-d7a9-15a9-f7dc-19f10307753b/QT00174037.jpg/600x600bb.jpg",
  "/hildegard#39": "https://is1-ssl.mzstatic.com/image/thumb/Music111/v4/27/e1/5d/27e15d49-d7a9-15a9-f7dc-19f10307753b/QT00174037.jpg/600x600bb.jpg",
  "/mary-lous-mass#1": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#2": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#3": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/c0/43/51/c043518d-d759-a814-bc7d-ee36184951ed/mzi.vhxizpfe.jpg/600x600bb.jpg",
  "/mary-lous-mass#4": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#5": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#6": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#7": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#8": "https://is1-ssl.mzstatic.com/image/thumb/Music/40/28/b7/mzi.telbpqpw.jpg/600x600bb.jpg",
  "/mary-lous-mass#9": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#10": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#11": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#12": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#13": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#14": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#15": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#16": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#17": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#18": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#19": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#20": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#21": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#22": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#23": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/mary-lous-mass#24": "https://is1-ssl.mzstatic.com/image/thumb/Music/34/33/da/mzi.wjpxqihc.jpg/600x600bb.jpg",
  "/taize-songs#1": "https://is1-ssl.mzstatic.com/image/thumb/Music/6c/1c/ae/mzi.vghwqnyd.jpg/600x600bb.jpg",
  "/taize-songs#2": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/47/30/2e/47302eaa-46e7-5d21-12ea-03b35f3dbb2c/cover.jpg/600x600bb.jpg",
  "/taize-songs#3": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/47/30/2e/47302eaa-46e7-5d21-12ea-03b35f3dbb2c/cover.jpg/600x600bb.jpg",
  "/taize-songs#5": "https://is1-ssl.mzstatic.com/image/thumb/Music/a6/36/b7/mzi.pjkfrgrk.jpg/600x600bb.jpg",
  "/taize-songs#6": "https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/55/2b/97/552b97a4-3353-dcad-8d23-fe213b801923/cover.jpg/600x600bb.jpg",
  "/taize-songs#7": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/4a/af/51/4aaf51f5-eae6-dc02-50d6-a87738e5985d/cover.jpg/600x600bb.jpg",
  "/taize-songs#8": "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/4a/af/51/4aaf51f5-eae6-dc02-50d6-a87738e5985d/cover.jpg/600x600bb.jpg",
  "/taize-songs#10": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/ef/4f/0c/ef4f0c6c-506e-f876-1573-b40734c5c153/ticket.mgpdbfok.png/600x600bb.jpg",
  "/sakamoto#1": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/27/d4/ab/27d4ab41-977e-1e47-4ba7-e6c5e3ebecdf/339.jpg/600x600bb.jpg",
  "/sakamoto#3": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/e2/3a/8a/e23a8ac2-280e-82b1-bfd7-fee1c06c9cee/05099951940157.jpg/600x600bb.jpg",
  "/sakamoto#4": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/27/d4/ab/27d4ab41-977e-1e47-4ba7-e6c5e3ebecdf/339.jpg/600x600bb.jpg",
  "/sakamoto#5": "https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/7b/a2/ce/7ba2ce4d-a220-9715-7704-b11efff6a1be/881036000000_cover.jpg/600x600bb.jpg",
  "/sakamoto#6": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/27/d4/ab/27d4ab41-977e-1e47-4ba7-e6c5e3ebecdf/339.jpg/600x600bb.jpg",
  "/sakamoto#8": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/27/d4/ab/27d4ab41-977e-1e47-4ba7-e6c5e3ebecdf/339.jpg/600x600bb.jpg",
  "/sakamoto#10": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/b3/8d/f5/b38df529-bcf2-9840-ab92-992e464c00fc/00888072301917.rgb.jpg/600x600bb.jpg",
  "/sakamoto#12": "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/27/d4/ab/27d4ab41-977e-1e47-4ba7-e6c5e3ebecdf/339.jpg/600x600bb.jpg",
  "/sakamoto#13": "https://is1-ssl.mzstatic.com/image/thumb/Music113/v4/4d/d0/17/4dd017cf-bb56-6fd3-7a7f-2ef7086b6252/886448177968.jpg/600x600bb.jpg",
  "/spirituals-album#1": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#2": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#3": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#4": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#5": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#6": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#7": "https://is1-ssl.mzstatic.com/image/thumb/Music/b4/ba/4e/mzi.mzaxpune.jpg/600x600bb.jpg",
  "/spirituals-album#8": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#9": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#10": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#11": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#12": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#13": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#14": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#15": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg",
  "/spirituals-album#16": "https://is1-ssl.mzstatic.com/image/thumb/Features/fd/ab/eb/dj.qwdvjcjd.tif/600x600bb.jpg"
};

/** The sleeve for a track, or undefined — never a placeholder URL. */
export function trackArtwork(cataloguePath: string, n: number): string | undefined {
  return ARTWORK[`${cataloguePath}#${n}`];
}
