// APNs push sender for Phoebe Mobile.
//
// Reads the following env vars (set in Railway → api-server → Variables):
//   APNS_KEY_P8       — full .p8 contents (BEGIN/END lines incl.)
//   APNS_KEY_ID       — 10-char string from developer.apple.com → Keys
//   APNS_TEAM_ID      — 10-char string from developer.apple.com → Membership
//   APNS_BUNDLE_ID    — defaults to "app.withphoebe.mobile"
//   APNS_ENVIRONMENT  — "production" (default) | "sandbox"
//
// If APNS_KEY_P8 / APNS_KEY_ID / APNS_TEAM_ID are unset, the sender
// degrades to a log-only stub (`sendOneApns` returns "stub") so local
// dev and preview deploys don't 500 on every trigger.
//
// Flow: sendPushToUser() reads active device tokens for the user,
// signs a single ES256 JWT (cached for ~55 min via getApnsJwt), and
// POSTs a standard `aps` payload to api.push.apple.com. 410s and
// BadDeviceToken responses mark the row invalid so the next pass
// skips it.

import http2 from "node:http2";
import { and, eq, inArray, isNull, sql } from "drizzle-orm";
import { SignJWT, importPKCS8, type KeyLike } from "jose";
import webpush from "web-push";
import { db, deviceTokensTable, webPushSubscriptionsTable, prayerFeedSubscriptionsTable, usersTable } from "@workspace/db";
import { logger } from "./logger";

// VAPID config for browser Web Push (Android Chrome / Firefox / Edge,
// desktop too). Subject is required by the spec — must be either a
// `mailto:` or `https:` URL identifying the sender, used by push
// services for abuse contact. Falls through silently when unset so
// dev environments without VAPID keys keep working.
const VAPID_PUBLIC = process.env["VAPID_PUBLIC_KEY"] ?? null;
const VAPID_PRIVATE = process.env["VAPID_PRIVATE_KEY"] ?? null;
const VAPID_SUBJECT = process.env["VAPID_SUBJECT"] ?? "mailto:hello@withphoebe.app";
if (VAPID_PUBLIC && VAPID_PRIVATE) {
  webpush.setVapidDetails(VAPID_SUBJECT, VAPID_PUBLIC, VAPID_PRIVATE);
}

const APNS_ENV = (process.env["APNS_ENVIRONMENT"] ?? "production").toLowerCase();
const APNS_HOST = APNS_ENV === "sandbox"
  ? "https://api.sandbox.push.apple.com"
  : "https://api.push.apple.com";

// ── Android push (FCM HTTP v1) ──────────────────────────────────────────────
// Service-account credentials from the Firebase console. Like the APNs and
// VAPID blocks above, everything falls through silently when unset, so a dev
// environment — or production before the Firebase project exists — keeps
// working and simply stubs Android sends.
//
// FCM_PRIVATE_KEY is the service account's PEM. Railway (and most dashboards)
// can't hold real newlines in an env var, so the literal "\n" sequences are
// unescaped here — the same convention used for other PEM-bearing vars.
const FCM = {
  projectId: process.env["FCM_PROJECT_ID"] ?? null,
  clientEmail: process.env["FCM_CLIENT_EMAIL"] ?? null,
  privateKey: (process.env["FCM_PRIVATE_KEY"] ?? "").replace(/\\n/g, "\n") || null,
};

// Google's OAuth2 access token for FCM, cached until shortly before expiry.
// Unlike the APNs JWT cache this is invalidated on an auth failure (see
// sendOneFcm) rather than blindly replayed for the rest of the window.
let fcmToken: { value: string; expiresAt: number } | null = null;

async function getFcmAccessToken(): Promise<string | null> {
  if (!FCM.projectId || !FCM.clientEmail || !FCM.privateKey) return null;
  if (fcmToken && fcmToken.expiresAt > Date.now() + 60_000) return fcmToken.value;
  try {
    const key = await importPKCS8(FCM.privateKey, "RS256");
    const assertion = await new SignJWT({ scope: "https://www.googleapis.com/auth/firebase.messaging" })
      .setProtectedHeader({ alg: "RS256" })
      .setIssuer(FCM.clientEmail)
      .setSubject(FCM.clientEmail)
      .setAudience("https://oauth2.googleapis.com/token")
      .setIssuedAt()
      .setExpirationTime("1h")
      .sign(key);
    const res = await fetch("https://oauth2.googleapis.com/token", {
      method: "POST",
      headers: { "content-type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer",
        assertion,
      }),
      signal: AbortSignal.timeout(10_000),
    });
    if (!res.ok) {
      logger.warn({ status: res.status }, "[push] FCM token exchange failed");
      return null;
    }
    const json = (await res.json()) as { access_token?: string; expires_in?: number };
    if (!json.access_token) return null;
    fcmToken = {
      value: json.access_token,
      expiresAt: Date.now() + (json.expires_in ?? 3600) * 1000,
    };
    return fcmToken.value;
  } catch (err) {
    logger.warn({ err }, "[push] FCM token exchange threw");
    return null;
  }
}

// Custom notification sounds bundled in the iOS app
// (phoebe-mobile/ios/App/App/PhoebeRising*.caf — generated by
// scripts/build-rising-sound.mjs). The synthesized "rising swell" comes
// in three octave variants so different notification kinds feel
// distinct on the lock screen even when stacked. iOS falls back to the
// system default chime if a referenced .caf isn't bundled, so old
// builds keep working through the rollout.
const PHOEBE_SOUND_LOW = "PhoebeRising-low.caf";    // daily-rhythm pulses (bell, evening nudge)
const PHOEBE_SOUND_MID = "PhoebeRising.caf";        // group / community / letter pulses
const PHOEBE_SOUND_HIGH = "PhoebeRising-high.caf";  // someone-prayed-for-you / amen pulses

// Strip emoji and other pictographic glyphs out of any string before it
// hits a push title or body. The dashboard intentionally leans on
// emojis (🌿 Morning Prayer) but on the lock screen
// they read as visual clutter and break the calm tone we want. Names
// flow through this on the way into the payload so the user never sees
// "🌱 ___" or "🙏🏽 ___" pop up on their phone.
const EMOJI_RE = /[\p{Extended_Pictographic}\p{Emoji_Presentation}\u200D\uFE0F]/gu;
function clean(text: string | null | undefined): string {
  if (!text) return "";
  return text.replace(EMOJI_RE, "").replace(/\s{2,}/g, " ").trim();
}

// iOS renders the notification title on a SINGLE line and hard-crops the
// overflow mid-character ("Praying for the families affec\u2026"). Many of
// Phoebe's titles interpolate unbounded user content \u2014 display names,
// community / intercession / gathering names, even a full custom "how can
// we pray for you?" question \u2014 any of which can sail past what fits. We cap
// the title to a safe width and truncate at a word boundary with an
// ellipsis so the crop is controlled and readable instead of letting iOS
// sever a word. The body still carries the detail.
//
// 40 chars fits one line on standard iPhones. The narrowest devices
// (SE / mini) may still trim a little, but the ellipsis already signals
// "there's more" and nothing meaningful lives only in the title.
const MAX_TITLE_LEN = 40;
function truncateTitle(title: string): string {
  const t = title.trim();
  if (t.length <= MAX_TITLE_LEN) return t;
  // Reserve one slot for the ellipsis, then prefer cutting at the last
  // space so we don't sever a word \u2014 unless that throws away too much
  // (a single very long token), in which case hard-cut at the budget.
  const budget = MAX_TITLE_LEN - 1;
  const slice = t.slice(0, budget);
  const lastSpace = slice.lastIndexOf(" ");
  const cut = lastSpace > budget * 0.6 ? slice.slice(0, lastSpace) : slice;
  return cut.trimEnd() + "\u2026";
}

const CREDS = {
  keyP8: process.env["APNS_KEY_P8"] ?? null,
  keyId: process.env["APNS_KEY_ID"] ?? null,
  teamId: process.env["APNS_TEAM_ID"] ?? null,
  bundleId: process.env["APNS_BUNDLE_ID"] ?? "app.withphoebe.mobile",
};

export interface PushPayload {
  title: string;
  body: string;
  // Optional deep-link path that the Capacitor shell routes to on tap.
  // e.g. "/communities/phoebe-architects"
  path?: string;
  // iOS badge number; pass `null` to clear, `undefined` to leave alone.
  badge?: number | null;
  // APNs thread-id for notification grouping. Phoebe uses one thread per
  // "kind" (e.g. "bell", "prayer-request-new", "member-joined").
  threadId?: string;
  // APNs collapse-id — if set, iOS replaces any pending notification
  // with the same ID instead of stacking. Use for events that are
  // idempotent and shouldn't show more than once (e.g. "letter #42
  // arrived" — if the backend somehow sends twice, the second replaces
  // the first rather than showing a duplicate on the lock screen).
  // Max 64 bytes per APNs spec.
  collapseId?: string;
  // Sound name from the app bundle, or "default".
  sound?: string;
  // APNs interruption level. iOS uses this to decide whether the
  // notification breaks through Focus modes / Do Not Disturb:
  //
  //   • "passive"        — silent, never interrupts. For info that
  //                        can wait.
  //   • "active"         — default; uses the user's normal alert
  //                        settings.
  //   • "time-sensitive" — breaks through most Focus modes when the
  //                        user has granted the per-app "Time
  //                        Sensitive Notifications" toggle. Used by
  //                        Duolingo's daily streak reminder so the
  //                        bell still lands during a "Work" or
  //                        "Personal" focus.
  //   • "critical"       — bypasses everything including Do Not
  //                        Disturb; requires a special Apple
  //                        entitlement we don't have.
  //
  // We use "time-sensitive" for the daily bell + evening nudge so a
  // user who's gone heads-down still gets the appointed prompt,
  // matching the Duolingo-style "your streak depends on this" feel.
  interruptionLevel?: "passive" | "active" | "time-sensitive";
  // Arbitrary custom fields merged into the APNs JSON body alongside
  // `path`, and into the web-push JSON. Read by the native shell when
  // filtering delivered notifications for removal. Use this when a
  // group of pushes shares one APNs thread-id (so iOS auto-stacks
  // them on the lock screen) but each push still needs a per-record
  // identifier we can target for individual clearing — e.g. all
  // prayer-request pushes share `thread-id: "prayer-requests"` to
  // stack, but each carries `data.prayerRequestId` so the per-amen
  // sweep can remove only the matching banner.
  data?: Record<string, string | number | boolean>;
  // Silent / background push: no alert, no sound — just `content-available: 1`
  // so the app wakes (best-effort) to act on `data`. Used to REMOVE a delivered
  // notification remotely (e.g. withdraw "Join the breath" when the live count
  // drops below 3). iOS throttles background delivery, so this is best-effort.
  silent?: boolean;
  // Skip web-push subscriptions — send to iOS device tokens only. (A silent push
  // is always iOS-only; this also lets an alert be iOS-scoped.)
  iosOnly?: boolean;
}

interface SendResult {
  attempted: number;
  succeeded: number;
  invalidated: number;
  // Per-transport breakdown. A bare `succeeded > 0` conflates a phone that
  // got the push with a desktop browser that did, which sent a real
  // "reminders are broken" report chasing iOS Focus modes for an hour: the
  // owner's desktop web-push subscription answered while their iPhone's
  // APNs token was dead, and the diagnostic cheerfully said "Sent — check
  // your lock screen." Any surface reporting delivery to a human MUST say
  // WHICH device answered.
  deviceSucceeded: number; // native APNs/FCM tokens
  webSucceeded: number;    // browser web-push subscriptions
}

/**
 * Send a push to every active iOS/Android device token belonging to the
 * given user. Invalid tokens are automatically marked with
 * `invalidated_at = now()` so the next cron pass skips them.
 */
export async function sendPushToUser(userId: number, payload: PushPayload): Promise<SendResult> {
  // Master notifications switch (Settings → Notifications). Every push
  // passes through this function, so one flag here silences all of them
  // — the bell, reminders, digests, prayer-for-you, words of comfort —
  // regardless of device tokens or OS permission. `=== false` so a null
  // (legacy) or true value still sends.
  const [pref] = await db
    .select({ pushEnabled: usersTable.pushEnabled })
    .from(usersTable)
    .where(eq(usersTable.id, userId));
  if (pref?.pushEnabled === false) {
    return { attempted: 0, succeeded: 0, invalidated: 0, deviceSucceeded: 0, webSucceeded: 0 };
  }

  // Centralized emoji strip + title cap — every push goes through this
  // function, so sanitizing here means callers can pass moment / community
  // names with emoji (stripped) and over-long titles (truncated to fit
  // iOS's single line) and we still ship a clean lock-screen string.
  payload = { ...payload, title: truncateTitle(clean(payload.title)), body: clean(payload.body) };
  const [tokens, webSubs] = await Promise.all([
    db.select({
      id: deviceTokensTable.id,
      platform: deviceTokensTable.platform,
      token: deviceTokensTable.token,
    })
      .from(deviceTokensTable)
      .where(and(
        eq(deviceTokensTable.userId, userId),
        isNull(deviceTokensTable.invalidatedAt),
      )),
    db.select({
      id: webPushSubscriptionsTable.id,
      endpoint: webPushSubscriptionsTable.endpoint,
      p256dh: webPushSubscriptionsTable.p256dh,
      auth: webPushSubscriptionsTable.auth,
    })
      .from(webPushSubscriptionsTable)
      .where(and(
        eq(webPushSubscriptionsTable.userId, userId),
        isNull(webPushSubscriptionsTable.invalidatedAt),
      )),
  ]);

  // Silent + iOS-only pushes never go to the web (no service-worker silent path,
  // and a titleless web push would spawn a junk banner).
  const targetWebSubs = (payload.silent || payload.iosOnly) ? [] : webSubs;
  const totalTargets = tokens.length + targetWebSubs.length;
  if (totalTargets === 0) {
    // Two distinct "no tokens" cases worth separating in the log so we
    // can triage silenced users from Railway without a DB session:
    //   1. The user has NEVER registered (zero rows ever inserted).
    //      Usually means push permission denied, or device-token POST
    //      failed on first launch and never retried.
    //   2. The user HAS registered but every row is invalidated_at != NULL
    //      (APNs returned 410 / BadDeviceToken at some point). They
    //      need to reopen the app on iOS 3.3+ to trigger the on-resume
    //      re-register flow. Pre-3.3 bundles stay silenced forever.
    let stoneStateRow: { ever: number; live: number } | null = null;
    try {
      const counts = await db.execute<{ ever: number; live: number }>(sql`
        SELECT
          (SELECT COUNT(*)::int FROM device_tokens WHERE user_id = ${userId}) AS ever,
          (SELECT COUNT(*)::int FROM device_tokens WHERE user_id = ${userId} AND invalidated_at IS NULL) AS live
      `);
      stoneStateRow = (counts.rows?.[0] as { ever: number; live: number } | undefined) ?? null;
    } catch { /* diagnostic only — non-fatal */ }
    const everCount = stoneStateRow?.ever ?? 0;
    const liveCount = stoneStateRow?.live ?? 0;
    // Identify by userId + the static notification "kind" (threadId), never by
    // email or the rendered title (which can carry a name or content).
    logger.info(
      {
        userId,
        kind: payload.threadId ?? "generic",
        deviceTokensEver: everCount,
        deviceTokensLive: liveCount,
        reason:
          everCount === 0
            ? "never-registered"
            : liveCount === 0
              ? "all-invalidated"
              : "unknown",
      },
      "[push] no active device tokens or web subs — skipping send"
    );
    return { attempted: 0, succeeded: 0, invalidated: 0, deviceSucceeded: 0, webSucceeded: 0 };
  }
  logger.info(
    { userId, tokenCount: tokens.length, webSubCount: webSubs.length, kind: payload.threadId ?? "generic" },
    "[push] sending"
  );

  const result: SendResult = {
    attempted: totalTargets, succeeded: 0, invalidated: 0,
    deviceSucceeded: 0, webSucceeded: 0,
  };
  const invalidTokenIds: number[] = [];
  const invalidWebSubIds: number[] = [];

  for (const t of tokens) {
    // Route by the platform the device registered with. Anything unrecognised
    // is skipped rather than assumed to be Apple — sending an Android token to
    // APNs just burns a request and then retires a perfectly good row.
    const send = t.platform === "ios" ? sendOneApns
      : t.platform === "android" ? sendOneFcm
      : null;
    if (!send) continue;
    // One retry on transient errors (5xx or network blip). APNs returns
    // 200 on success, 410/400-BadDeviceToken on invalid token (no point
    // retrying), and 5xx on its own infrastructure trouble. Without the
    // retry every 5xx silently lost a push — Apple's SLA is good but
    // not perfect, and Phoebe's tiny volume means even one drop is a
    // visible "I didn't get the notification" complaint. FCM behaves the
    // same way, so it shares the loop.
    let outcome = await send(t.token, payload);
    if (outcome === "error") {
      await new Promise(r => setTimeout(r, 800));
      outcome = await send(t.token, payload);
    }
    if (outcome === "ok") { result.succeeded += 1; result.deviceSucceeded += 1; }
    else if (outcome === "invalid") invalidTokenIds.push(t.id);
  }

  for (const sub of targetWebSubs) {
    // Same retry pattern for web push. webpush.sendNotification returns
    // an Error subclass with statusCode on 4xx/5xx; sendOneWebPush
    // collapses that to "ok" / "invalid" / "error".
    let outcome = await sendOneWebPush(sub, payload);
    if (outcome === "error") {
      await new Promise(r => setTimeout(r, 800));
      outcome = await sendOneWebPush(sub, payload);
    }
    if (outcome === "ok") { result.succeeded += 1; result.webSucceeded += 1; }
    else if (outcome === "invalid") invalidWebSubIds.push(sub.id);
  }

  if (invalidTokenIds.length > 0) {
    await db.update(deviceTokensTable)
      .set({ invalidatedAt: sql`now()` })
      .where(inArray(deviceTokensTable.id, invalidTokenIds));
    result.invalidated += invalidTokenIds.length;
  }
  if (invalidWebSubIds.length > 0) {
    await db.update(webPushSubscriptionsTable)
      .set({ invalidatedAt: sql`now()` })
      .where(inArray(webPushSubscriptionsTable.id, invalidWebSubIds));
    result.invalidated += invalidWebSubIds.length;
  }

  return result;
}

type WebPushOutcome = "ok" | "invalid" | "error" | "stub";

/**
 * Send a single Web Push (VAPID). Returns:
 *   "ok"      — push service accepted (201)
 *   "invalid" — 404/410 (subscription gone — user revoked permission,
 *               cleared site data, or it expired). Caller invalidates.
 *   "error"   — any other failure (5xx, network). Caller retries next tick.
 *   "stub"    — VAPID env vars unset; logged and skipped.
 */
async function sendOneWebPush(
  sub: { endpoint: string; p256dh: string; auth: string },
  payload: PushPayload,
): Promise<WebPushOutcome> {
  if (!VAPID_PUBLIC || !VAPID_PRIVATE) {
    // Log only the non-sensitive shape — never the payload (its title/body can
    // carry a name or message/prayer text).
    logger.info({
      webpush: "stub",
      endpoint: sub.endpoint.slice(0, 40) + "…",
      kind: payload.threadId ?? "generic",
      path: payload.path ?? "/",
      titleLen: payload.title?.length ?? 0,
      bodyLen: payload.body?.length ?? 0,
    }, "[push] VAPID_* env vars not set — would have sent web push");
    return "stub";
  }

  // Service worker reads this JSON in its `push` listener and turns
  // it into a system notification. Keep the field shape stable —
  // the SW depends on it (title, body, path, tag).
  const json = JSON.stringify({
    title: payload.title,
    body: payload.body,
    path: payload.path ?? "/",
    tag: payload.collapseId ?? payload.threadId ?? undefined,
    threadId: payload.threadId ?? undefined,
    // Same merge as the APNs path — keeps web + iOS payloads in sync
    // for downstream consumers that key off custom fields.
    ...(payload.data ?? {}),
  });

  try {
    await webpush.sendNotification(
      {
        endpoint: sub.endpoint,
        keys: { p256dh: sub.p256dh, auth: sub.auth },
      },
      json,
      {
        // TTL controls how long the push service holds the message
        // if the device is offline. 24h matches the daily cadence —
        // an old bell waiting in queue is no longer useful.
        TTL: 60 * 60 * 24,
        // urgency=high mirrors APNs priority=10; the push service
        // delivers immediately even if the device is in deep sleep.
        urgency: "high",
      },
    );
    return "ok";
  } catch (err) {
    const status = (err as { statusCode?: number } | null)?.statusCode;
    if (status === 404 || status === 410) {
      // Subscription expired or user revoked permission — drop it.
      return "invalid";
    }
    logger.warn({ err, status, endpoint: sub.endpoint.slice(0, 40) + "…" }, "[push] web-push send failed");
    return status && status >= 400 && status < 500 ? "invalid" : "error";
  }
}

type ApnsOutcome = "ok" | "invalid" | "error" | "stub";

/**
 * Send a single APNs notification. Returns:
 *   "ok"      — APNs accepted the payload (200)
 *   "invalid" — APNs rejected the token (410 Unregistered or BadDeviceToken)
 *   "error"   — any other failure (5xx, network). Caller should retry
 *               next bell tick; we don't invalidate the token.
 *   "stub"    — credentials not configured; sender logged and skipped.
 */
/** Deliver one push to an Android device over FCM HTTP v1.
 *
 *  Same outcome contract as sendOneApns so the caller's retry/invalidate loop
 *  is identical: "stub" when unconfigured, "invalid" ONLY for a token FCM says
 *  is dead, "error" for anything retryable.
 *
 *  NOTE on invalidation — deliberately narrower than the APNs path. That one
 *  treats every 4xx as a dead token, which means one bad credential can mark
 *  the entire user base's tokens invalid in a single scheduler tick (see the
 *  2026-07-21 notification audit). Here 401/403 (auth), 429 (rate limit) and
 *  5xx are all retryable; only UNREGISTERED, and INVALID_ARGUMENT naming the
 *  registration token, retire a row. */
async function sendOneFcm(deviceToken: string, payload: PushPayload): Promise<ApnsOutcome> {
  if (!FCM.projectId) return "stub";
  const accessToken = await getFcmAccessToken();
  if (!accessToken) {
    logger.info({ kind: payload.threadId ?? "generic" }, "[push] FCM not configured — stubbing android send");
    return "stub";
  }

  // Every value in FCM's `data` map must be a string.
  const data: Record<string, string> = {};
  if (payload.path) data["path"] = payload.path;
  if (payload.threadId) data["thread-id"] = payload.threadId;
  for (const [k, v] of Object.entries(payload.data ?? {})) {
    if (v !== undefined && v !== null) data[k] = String(v);
  }

  // `collapse_key` + `tag` are Android's "replace the previous one" controls,
  // which is what collapseId means. threadId is iOS GROUPING and must NOT be
  // mapped to tag — that would make every notification of a kind replace the
  // last one. It rides in `data` instead, where the shell can read it.
  const message: Record<string, unknown> = payload.silent
    ? {
        token: deviceToken,
        data,
        android: { priority: "high" },
      }
    : {
        token: deviceToken,
        notification: { title: payload.title, body: payload.body },
        data,
        android: {
          priority: "high",
          ...(payload.collapseId ? { collapse_key: payload.collapseId.slice(0, 64) } : {}),
          notification: {
            sound: "default",
            // No explicit channel_id: on API 26+ a named channel must already
            // exist or the notification is dropped silently, and none is
            // created yet. Omitting it lets Android use the app's default
            // channel, which always works. Worth revisiting alongside a proper
            // "Daily prayer" channel once there's a device to test on.
            ...(payload.collapseId ? { tag: payload.collapseId.slice(0, 64) } : {}),
            ...(typeof payload.badge === "number" ? { notification_count: payload.badge } : {}),
          },
        },
      };

  try {
    const res = await fetch(
      `https://fcm.googleapis.com/v1/projects/${encodeURIComponent(FCM.projectId)}/messages:send`,
      {
        method: "POST",
        headers: {
          authorization: `Bearer ${accessToken}`,
          "content-type": "application/json",
        },
        body: JSON.stringify({ message }),
        // The APNs path has no timeout at all, so one half-open socket can
        // stall a whole scheduler run. Don't repeat that here.
        signal: AbortSignal.timeout(10_000),
      },
    );

    if (res.ok) return "ok";

    const text = await res.text().catch(() => "");
    if (res.status === 401 || res.status === 403) {
      // Credentials problem, not a dead device. Drop the cached access token
      // so the next attempt re-mints, and treat it as retryable.
      fcmToken = null;
      logger.warn({ status: res.status }, "[push] FCM auth rejected — token cache cleared");
      return "error";
    }
    if (res.status === 404 || /UNREGISTERED/i.test(text)) return "invalid";
    if (res.status === 400 && /INVALID_ARGUMENT/i.test(text) && /token/i.test(text)) return "invalid";
    logger.warn({ status: res.status, body: text.slice(0, 200) }, "[push] FCM send failed");
    return "error";
  } catch (err) {
    logger.warn({ err }, "[push] FCM send threw");
    return "error";
  }
}

async function sendOneApns(deviceToken: string, payload: PushPayload): Promise<ApnsOutcome> {
  if (!CREDS.keyP8 || !CREDS.keyId || !CREDS.teamId) {
    // Log only the non-sensitive shape — never the payload (its title/body can
    // carry a name or message/prayer text).
    logger.info({
      apns: "stub",
      bundleId: CREDS.bundleId,
      host: APNS_HOST,
      deviceToken: deviceToken.slice(0, 8) + "…",
      kind: payload.threadId ?? "generic",
      path: payload.path ?? "/",
      titleLen: payload.title?.length ?? 0,
      bodyLen: payload.body?.length ?? 0,
    }, "[push] APNS_* env vars not set — would have sent");
    return "stub";
  }

  // APNs accepts an ES256-signed JWT in the Authorization header. The same
  // JWT is valid for up to 1 hour across any number of requests; we cache
  // it module-scope to avoid re-signing on every push.
  let jwt: string;
  try {
    jwt = await getApnsJwt();
  } catch (err) {
    logger.error({ err }, "[push] APNs JWT sign failed");
    return "error";
  }

  // Silent/background push carries only `content-available` — no alert/sound —
  // so the app can act on `data` (e.g. remove a delivered banner) without
  // showing anything. Normal pushes carry the alert + sound + grouping fields.
  const apsPayload: Record<string, unknown> = payload.silent
    ? { "content-available": 1 }
    : {
        alert: { title: payload.title, body: payload.body },
        sound: payload.sound ?? "default",
      };
  if (!payload.silent) {
    if (payload.threadId) apsPayload["thread-id"] = payload.threadId;
    if (payload.badge !== undefined) apsPayload["badge"] = payload.badge;
    if (payload.interruptionLevel) apsPayload["interruption-level"] = payload.interruptionLevel;
  }

  const body = JSON.stringify({
    aps: apsPayload,
    // Custom fields below `aps` — read by the native shell's
    // `pushNotificationActionPerformed` listener to deep-link in-app,
    // and by the clear-notifications matcher to identify which
    // delivered push to remove (see PushPayload.data).
    ...(payload.path ? { path: payload.path } : {}),
    ...(payload.data ?? {}),
  });

  const headers: Record<string, string> = {
    authorization: `bearer ${jwt}`,
    "apns-topic": CREDS.bundleId as string,
    "apns-push-type": payload.silent ? "background" : "alert",
    "apns-priority": payload.silent ? "5" : "10",
    "content-type": "application/json",
  };
  if (payload.collapseId) {
    // APNs limits collapse-id to 64 bytes; truncate defensively.
    headers["apns-collapse-id"] = payload.collapseId.slice(0, 64);
  }

  // APNs requires HTTP/2 — Node's native fetch (undici) only speaks
  // HTTP/1.1, so the previous version failed every send with
  // "fetch failed: Response does not match the HTTP/..." We use the
  // built-in node:http2 module instead. apnsRequest opens a session
  // per call (cheap; no pooling complexity for our low push volume)
  // and returns parsed { status, reason }.
  let result: { status: number; reason: string };
  try {
    result = await apnsRequest(deviceToken, headers, body);
  } catch (err) {
    logger.warn({ err }, "[push] APNs network error");
    return "error";
  }

  if (result.status === 200) return "ok";
  // 410 Gone = Unregistered; 400 + "BadDeviceToken" reason = device
  // token doesn't match environment (sandbox/prod mixup or app
  // uninstall). Both mean we should stop sending to this token.
  if (result.status === 410) return "invalid";

  logger.warn(
    { status: result.status, reason: result.reason, deviceToken: deviceToken.slice(0, 8) + "…" },
    "[push] APNs send failed"
  );

  if (
    result.status === 400 &&
    (result.reason === "BadDeviceToken" || result.reason === "DeviceTokenNotForTopic")
  ) {
    return "invalid";
  }
  // 4xx generally = something about the request is wrong permanently;
  // invalidate so we don't keep retrying. 5xx = transient, retry later.
  return result.status >= 400 && result.status < 500 ? "invalid" : "error";
}

// Open an HTTP/2 session to APNs, send one request, return the response.
// We don't pool sessions — Phoebe's push volume is tiny and the
// per-request session cost (a TLS handshake) is dwarfed by the JWT cache
// hit and the actual notification round-trip. Pooling would force us to
// handle session lifecycle, GOAWAY frames, idle timeouts, etc., for
// negligible benefit. If we ever push thousands per minute, revisit.
async function apnsRequest(
  deviceToken: string,
  headers: Record<string, string>,
  body: string,
): Promise<{ status: number; reason: string }> {
  return new Promise((resolve, reject) => {
    const session = http2.connect(APNS_HOST);
    let settled = false;
    const finish = (resOrErr: { status: number; reason: string } | Error) => {
      if (settled) return;
      settled = true;
      try { session.close(); } catch { /* already closed */ }
      if (resOrErr instanceof Error) reject(resOrErr); else resolve(resOrErr);
    };

    session.on("error", err => finish(err));

    const req = session.request({
      ":method": "POST",
      ":path": `/3/device/${deviceToken}`,
      ...headers,
    });

    let status = 0;
    let bodyChunks = "";
    req.on("response", h => {
      status = Number(h[":status"] ?? 0);
    });
    req.on("error", err => finish(err));
    req.setEncoding("utf8");
    req.on("data", chunk => { bodyChunks += chunk; });
    req.on("end", () => {
      let reason = "";
      if (bodyChunks) {
        try {
          const parsed = JSON.parse(bodyChunks) as { reason?: string };
          reason = parsed.reason ?? bodyChunks;
        } catch {
          reason = bodyChunks;
        }
      }
      finish({ status, reason });
    });

    req.write(body);
    req.end();
  });
}

// ─── APNs JWT caching ──────────────────────────────────────────────────────
// Apple accepts a single ES256-signed JWT for up to 60 minutes per-token.
// Sign once, cache 55 min, resign.
const APNS_JWT_TTL_MS = 55 * 60 * 1000;
let apnsKeyCache: KeyLike | null = null;
let apnsJwtCache: { token: string; expiresAt: number } | null = null;

async function getApnsJwt(): Promise<string> {
  if (apnsJwtCache && apnsJwtCache.expiresAt > Date.now()) {
    return apnsJwtCache.token;
  }
  if (!apnsKeyCache) {
    apnsKeyCache = (await importPKCS8(
      CREDS.keyP8 as string,
      "ES256"
    )) as KeyLike;
  }
  const nowSec = Math.floor(Date.now() / 1000);
  const token = await new SignJWT({})
    .setProtectedHeader({ alg: "ES256", kid: CREDS.keyId as string })
    .setIssuer(CREDS.teamId as string)
    .setIssuedAt(nowSec)
    .sign(apnsKeyCache);
  apnsJwtCache = { token, expiresAt: Date.now() + APNS_JWT_TTL_MS };
  return token;
}

// Thin helpers for common notification kinds. Callers don't need to
// know payload conventions; they just call by name.

// Morning bell (9 AM local). The copy is deliberately
// relational — "your friends" — because the whole app frames prayer as
// carrying other people, not as a solo practice. Body is a gentle
// invitation rather than a metric; we deliberately avoid a per-user
// "N prayers waiting" count so the push says the same thing to
// everyone and stays readable when the count would be 0.
//
// Lands on /prayer-chooser — the time-of-day picker (Community
// Intercessions / Devotion / Office) — not the slideshow directly,
// so the user gets to pick how deep they want to go today.
export function sendBellPush(userId: number) {
  return sendPushToUser(userId, {
    title: "Time to pray for your friends",
    body: "Open to choose how to pray with your community today.",
    path: "/prayer-chooser",
    threadId: "bell",
    sound: PHOEBE_SOUND_LOW,
    // Time-sensitive so the bell breaks through Focus modes the
    // way Duolingo's daily streak reminder does — a user who's
    // gone heads-down still gets the appointed prompt at 9 AM
    // local. Requires the matching iOS entitlement
    // (com.apple.developer.usernotifications.time-sensitive) AND
    // the per-app "Time Sensitive Notifications" toggle in iOS
    // Settings; iOS silently downgrades to "active" if either is
    // missing, so we never need to fall back manually.
    interruptionLevel: "time-sensitive",
  });
}

// Evening nudge (20:00 local). Fires only if the recipient hasn't
// logged a prayer today AND at least one person in their garden has —
// the body is social-proof copy ("Join N people…") so it's pointless
// without a positive count. See runEveningNudgeSender for the gating.
//
// `communityPrayerCount` is the number of distinct garden members
// (group peers + letter correspondents) who have prayed today in the
// recipient's tz. The caller has already filtered to count > 0 before
// reaching here; we still defensively pluralise for count = 1.
export function sendEveningNudgePush(userId: number, communityPrayerCount: number) {
  const body = communityPrayerCount === 1
    ? "Join 1 person from your community who has prayed today."
    : `Join ${communityPrayerCount} people from your community who have prayed together today.`;
  return sendPushToUser(userId, {
    title: "Don't forget to pray for your friends",
    body,
    path: "/prayer-mode",
    threadId: "bell",
    sound: PHOEBE_SOUND_LOW,
    // Same time-sensitive treatment as the morning bell. The
    // evening nudge fires at 8 PM local; a user with a "Wind
    // down" Focus would otherwise miss it.
    interruptionLevel: "time-sensitive",
  });
}

// Run an async fn over items with a bounded number in flight. Used to cap
// push fan-out (see sendPushToUsers): each task touches the DB + APNs, so an
// unbounded Promise.all over thousands of recipients would exhaust the
// connection pool. Pulls from a shared cursor so faster tasks keep the
// workers busy.
async function mapLimit<T>(items: T[], limit: number, fn: (item: T) => Promise<void>): Promise<void> {
  let cursor = 0;
  const workerCount = Math.max(1, Math.min(limit, items.length));
  const workers = Array.from({ length: workerCount }, async () => {
    while (cursor < items.length) {
      const item = items[cursor++]!;
      await fn(item);
    }
  });
  await Promise.all(workers);
}

// At most this many recipients are in flight at once. Kept below the DB pool
// max so a large fan-out can't starve concurrent user requests of connections.
const PUSH_FANOUT_CONCURRENCY = Number(process.env.PUSH_FANOUT_CONCURRENCY ?? "8");

// Fan-out wrapper. Concurrency-limited (mapLimit) so a feed/parish with
// thousands of subscribers can't fire thousands of concurrent DB queries +
// APNs calls at once and exhaust the pool. A slow APNs call for one recipient
// still doesn't block others (up to the concurrency cap). Errors are swallowed
// per-user inside sendPushToUser → sendOneApns.
export async function sendPushToUsers(userIds: number[], payload: PushPayload): Promise<void> {
  if (userIds.length === 0) return;
  // Dedup — protects against overlapping member queries (e.g. someone is
  // both admin + member).
  const unique = Array.from(new Set(userIds.filter(id => Number.isFinite(id))));
  await mapLimit(unique, PUSH_FANOUT_CONCURRENCY, (id) =>
    sendPushToUser(id, payload).then(() => undefined).catch(() => undefined));
}

// "How did it go?" — the life-event follow-up, fired the evening of the event
// day by the cron. Taps into the request so the owner can post an update.
export function sendLifeEventFollowUpPush(
  ownerId: number,
  opts: { prayerRequestId: number; eventTitle: string | null },
) {
  const what = (opts.eventTitle || "").trim();
  return sendPushToUser(ownerId, {
    title: "How did it go?",
    body: what
      ? `Share how ${what} went with the people who prayed.`
      : "Share how it went with the people who prayed.",
    path: `/prayer-requests/${opts.prayerRequestId}`,
    threadId: "prayer-requests",
    data: { prayerRequestId: opts.prayerRequestId },
    sound: PHOEBE_SOUND_MID,
  });
}

// "{Name} shared how [title] went" — sent to everyone who prayed for a life
// event once its owner posts their update. Closes the loop with the people who
// actually showed up for it.
export async function sendLifeEventUpdatePush(
  userIds: number[],
  opts: { prayerRequestId: number; ownerName: string; eventTitle: string | null },
): Promise<void> {
  const firstName = (opts.ownerName || "Someone").split(/\s+/)[0] || "Someone";
  const what = (opts.eventTitle || "").trim();
  await sendPushToUsers(userIds, {
    title: what ? `${firstName} shared how ${what} went` : `${firstName} shared an update`,
    body: "Tap to read how the prayer was answered.",
    path: `/prayer-requests/${opts.prayerRequestId}`,
    threadId: "prayer-requests",
    data: { prayerRequestId: opts.prayerRequestId },
    sound: PHOEBE_SOUND_HIGH,
  });
}

// Fires when someone writes a "word of comfort" / prayer response on
// another user's prayer request. Sender-revealing (recipients want to
// know who cared enough to reach out). Tap lands on the recipient's
// prayer list so they can read it.
//
// We already gate at the route layer (only on FIRST insert per
// author+request, not on edits), but the collapse-id is belt-and-
// suspenders: if the route ever fires twice for the same pair,
// iOS replaces rather than stacks.
// Collapse-id formats shared by the word + first-amen pushes. Each format
// has ONE owner here because the merged variants deliberately cross-reference
// the other push's id (so iOS replaces the sibling banner instead of
// stacking) — a hand-written literal in one function would silently drift.
function firstAmenCollapseId(prayerRequestId: number): string {
  return `first-amen-${prayerRequestId}`;
}
function prayerWordCollapseId(prayerRequestId: number, authorUserId: number): string {
  return `prayer-word-${prayerRequestId}-${authorUserId}`;
}

export function sendPrayerWordPush(
  recipientUserId: number,
  opts: {
    authorUserId?: number;
    authorName: string;
    prayerRequestId?: number;
    /** True when this word's author is ALSO the request's first amen-er.
     *  The recipient already got (or will get) a first-amen push naming the
     *  same person, so this push MERGES the two moments: the body covers
     *  both, and the collapse-id reuses the first-amen one so iOS REPLACES
     *  that banner instead of stacking a second notification. */
    mergedFirstAmen?: boolean;
  }
) {
  const collapseId = opts.mergedFirstAmen && opts.prayerRequestId
    ? firstAmenCollapseId(opts.prayerRequestId)
    : opts.prayerRequestId && opts.authorUserId
      ? prayerWordCollapseId(opts.prayerRequestId, opts.authorUserId)
      : undefined;
  // Deep-link to the dedicated comment landing page — a slide-styled
  // view of the request and the latest word of comfort. Falls back to
  // the bare /prayer-list if the prayerRequestId is missing (defensive).
  const path = opts.prayerRequestId
    ? `/prayer-requests/${opts.prayerRequestId}`
    : "/prayer-list";
  const firstName = (opts.authorName || "Someone").split(/\s+/)[0] || "Someone";
  return sendPushToUser(recipientUserId, {
    title: `${firstName} prayed for you`,
    body: opts.mergedFirstAmen
      ? "They said the first amen and left you a word of comfort."
      : "Open Phoebe to read what they wrote.",
    path,
    threadId: opts.prayerRequestId ? `prayer-request-${opts.prayerRequestId}` : "prayer-word",
    collapseId,
    sound: PHOEBE_SOUND_HIGH,
  });
}

// Fires for every joined member of a group EXCEPT the requester
// when a new community prayer request is posted. The previous design
// suppressed this entirely ("noise"); product direction reversed for
// per-group requests because the request is the whole point of being
// in a community — silently sliding it onto a feed nobody opens
// regularly defeated the purpose. Push is community-scoped (only
// fires for `groupId`-bound requests), still gated to "joined" rows
// (pending invitees stay quiet), and the collapse-id makes the
// fan-out idempotent against any retry.
//
// Tap deep-links to the request's slide page (/prayer-requests/:id)
// where the recipient sees the prayer body, can leave a word of
// comfort, and can amen.
//
// Badge: we set the iOS app-icon badge to the recipient's current
// unprayed count (computed *after* the new request landed). This
// is the central UX nudge in the new "respond to requests" model —
// the app icon shows how many prayers are still owed without
// requiring the user to open the app. The number is the same one
// the dashboard's "X new prayers waiting" card shows.
export async function sendNewPrayerRequestPush(
  recipientUserId: number,
  opts: { authorName: string; isAnonymous: boolean; prayerRequestId: number },
) {
  const display = opts.isAnonymous
    ? "Someone"
    : ((opts.authorName || "Someone").split(/\s+/)[0] || "Someone");
  // No badge. The app-icon badge means ONE thing — how many practices are
  // left in today's rhythm — and the client is its only author (see
  // dashboard.tsx's setBadge sync off DailyProgressBody's remainingCount).
  // This used to send getUnprayedCount (unprayed prayer REQUESTS), a
  // different number entirely, so a push would overwrite the practice count
  // with an unrelated one and the icon would show e.g. 1 while three
  // practices were still undone. Leaving `badge` undefined means APNs
  // doesn't touch the icon at all and the client's value stands.
  return sendPushToUser(recipientUserId, {
    title: `${display} is asking for your prayers`,
    body: "Open Phoebe to pray for them.",
    path: `/prayer-requests/${opts.prayerRequestId}`,
    // Shared thread-id across ALL pending prayer-request pushes — iOS
    // auto-groups same-thread notifications into a single stack on
    // the lock screen, so a user with three or four unprayed asks
    // sees one "Phoebe • N notifications" stack instead of N
    // separate banners. The first one or two still render as full
    // cards; from the third onward iOS collapses them under the
    // app's group header. The grouping is automatic — nothing to
    // configure on the device.
    threadId: "prayer-requests",
    // Per-request identifier in the data payload. The shared thread-id
    // above means the clear-notifications matcher can't use thread-id
    // alone to identify which delivered banner belongs to which
    // request — so we carry the id explicitly and the native shell
    // matches on it (see native-shell.ts wireClearNotifications).
    data: { prayerRequestId: opts.prayerRequestId },
    collapseId: `new-prayer-request-${opts.prayerRequestId}`,
    sound: PHOEBE_SOUND_MID,
  });
}

// Community admin → all members: "How can we pray for you?" prompt.
// Rate-limited server-side to once per 7 days per group. Tap deep-
// links the member to /community/:slug/share-prayer where they can
// post a prayer request that gets carried by their whole garden.
// Sound is the gentle mid chime — this is an invitation, not an
// urgent ask.
export function sendPrayerInvitePush(
  recipientUserId: number,
  opts: { groupSlug: string; groupName: string; adminName: string; prompt?: string },
) {
  const firstName = (opts.adminName || "").split(/\s+/)[0] || "Someone";
  // The admin-chosen question is the push title (a preset or a custom
  // one); falls back to the default. The body names who's asking.
  const title = (opts.prompt ?? "").trim() || "How can we pray for you?";
  return sendPushToUser(recipientUserId, {
    title,
    body: `${firstName} from ${opts.groupName} is asking — tap to share.`,
    path: `/communities/${opts.groupSlug}/share-prayer`,
    threadId: `prayer-invite-${opts.groupSlug}`,
    collapseId: `prayer-invite-${opts.groupSlug}`,
    sound: PHOEBE_SOUND_MID,
  });
}

// Morning / evening office reminder. Fires at the user's chosen reminder
// time once per local day. The copy names the side's ACTUAL practice when we
// know it (`level` — the synced routine's per-side level, falling back to the
// flattened office/devotion reminder pref), so a Psalms-in-the-morning person
// is invited to the Psalms, not a generic office. Unknown/legacy levels keep
// the old generic copy. The tap opens /begin-prayer pinned to this side, so a
// late-morning reminder can't resolve to the evening office. parishTitle,
// when present, still names the parish in the body for a communal feel.
// Sound is the standard mid chime — a gentle invitation, not urgent.
export function sendParishOfficeReminderPush(
  userId: number,
  opts: {
    side: "morning" | "evening";
    parishTitle?: string | null;
    level?: string | null;
    // Owner: "have it in the second line of the notification include the
    // psalms and the readings for the day." A compact citation string
    // (bellSender.ts's officeReadingsLine) appended as its own line in the
    // body when present; omitted entirely (undefined/null) leaves the body
    // exactly as before — best-effort, never blocks the push itself.
    readingsLine?: string | null;
  }
) {
  const { side, parishTitle, level, readingsLine } = opts;
  const cap = side === "morning" ? "Morning" : "Evening";
  const practiceCopy: Record<string, { title: string; body: string }> = {
    office: {
      title: `${cap} Prayer`,
      body: side === "morning" ? "The office is ready — begin the day in prayer." : "The office is ready — close the day in prayer.",
    },
    devotion: {
      title: `${cap} Devotion`,
      body: side === "morning" ? "A short office to begin the day." : "A short office to close the day.",
    },
    psalms: {
      title: "Praying the Psalms",
      body: side === "morning" ? "This morning's appointed psalms are ready." : "This evening's appointed psalms are ready.",
    },
    "reflect-sit": {
      title: `${cap} Contemplation`,
      body: "A few minutes of loving God in silence.",
    },
    fdd: {
      title: "Forward Day by Day",
      body: "Today's reflection is ready.",
    },
    readings: {
      title: "Daily Scripture Readings",
      body: "Today's reading is ready.",
    },
    examen: {
      title: "The Examen",
      body: "Review the day with God.",
    },
  };
  const practice = level ? practiceCopy[level] : undefined;
  const title = practice?.title
    ?? (side === "morning" ? "Begin your day in prayer" : "Close your day in prayer");
  const firstLine = parishTitle
    ? `Pray with ${parishTitle}.`
    : practice?.body
      ?? (side === "morning"
        ? "A few quiet minutes to start the day."
        : "A few quiet minutes before the day ends.");
  const body = readingsLine ? `${firstLine}\n${readingsLine}` : firstLine;
  return sendPushToUser(userId, {
    title,
    body,
    path: `/begin-prayer?side=${side}`,
    threadId: `parish-office-${side}`,
    collapseId: `parish-office-${side}-${userId}`,
    sound: PHOEBE_SOUND_MID,
  });
}

// Daily contemplation goal — a gentle ~7pm nudge on days the user hasn't yet
// reached their minutes goal of silent prayer. Deep-links to the Contemplation
// page so a tap can begin a sit. Deduped to once per local day by the sender.
export function sendContemplationGoalReminderPush(
  userId: number,
  opts: { goalMinutes: number; doneMinutes: number }
) {
  const remaining = Math.max(1, opts.goalMinutes - opts.doneMinutes);
  const body = opts.doneMinutes > 0
    ? `${remaining} more min to reach your ${opts.goalMinutes}-minute goal today.`
    : `A few quiet minutes to reach your ${opts.goalMinutes}-minute goal today.`;
  return sendPushToUser(userId, {
    title: "Still time to hit your goal",
    body,
    // Same destination as tapping the home Contemplation card: ?begin=1 opens
    // straight into the sit (and the contemplation page redirects to Cobreathe
    // when that's the user's chosen style, matching the card).
    path: "/contemplation?begin=1",
    threadId: "contemplation-goal",
    collapseId: `contemplation-goal-${userId}`,
    sound: PHOEBE_SOUND_LOW,
  });
}

// Weekly Way of Love review — the Sunday-evening examen nudge. Invites the user
// to look back on the week and set the one ahead. Deep-links into the review;
// deduped to once per Sunday by the sender.
export function sendWeeklyReviewPush(userId: number) {
  return sendPushToUser(userId, {
    title: "A new week begins",
    body: "Look back on your Way of Love, and set the week ahead.",
    path: "/this-week/review",
    threadId: "weekly-review",
    collapseId: `weekly-review-${userId}`,
    sound: PHOEBE_SOUND_LOW,
  });
}


// Fires for each admin of a community when someone taps "Request to
// join" on /communities/browse. Deep-links to the requests management
// panel so the admin can accept or decline in two taps.
export function sendCommunityJoinRequestPush(
  adminUserId: number,
  opts: { groupSlug: string; groupName: string; requesterName: string }
) {
  return sendPushToUser(adminUserId, {
    title: opts.groupName || "Phoebe",
    body: `${opts.requesterName} would like to join.`,
    path: `/communities/${opts.groupSlug}/requests`,
    threadId: `join-requests-${opts.groupSlug}`,
    sound: PHOEBE_SOUND_MID,
  });
}

// Fires for the requester when an admin accepts. Deep-links to the
// community detail page so they land where they belong.
export function sendCommunityJoinAcceptedPush(
  userId: number,
  opts: { groupSlug: string; groupName: string }
) {
  return sendPushToUser(userId, {
    title: opts.groupName || "Phoebe",
    body: `You're in. Welcome to ${opts.groupName}.`,
    path: `/communities/${opts.groupSlug}`,
    threadId: `community-${opts.groupSlug}`,
    sound: PHOEBE_SOUND_MID,
  });
}

// "You prayed with N other people." Fires once, to every participant
// of an intercession, the moment the practice's goal is reached. Only
// goes to people who actually had a check-in — silent for members who
// joined the practice but never prayed. Body shapes:
//
//   • 0 others: "You completed this prayer." (edge: solo intercession)
//   • 1 other:  "You prayed with 1 other person."
//   • N others: "You prayed with N other people."
//
// Title is the intercession's name so the lock-screen carries the
// specific prayer, not a generic banner. Tap → /moments/:id (the
// intercession's detail / closing slide).
export function sendIntercessionGoalReachedPush(
  recipientUserId: number,
  opts: {
    momentId: number;
    intercessionName: string;
    otherPrayerCount: number;
  },
) {
  const body =
    opts.otherPrayerCount <= 0
      ? "You completed this prayer."
      : opts.otherPrayerCount === 1
        ? "You prayed with 1 other person."
        : `You prayed with ${opts.otherPrayerCount} other people.`;
  return sendPushToUser(recipientUserId, {
    title: opts.intercessionName || "Prayer complete",
    body,
    path: `/moments/${opts.momentId}`,
    threadId: `moment-${opts.momentId}`,
    collapseId: `goal-reached-${opts.momentId}`,
    sound: PHOEBE_SOUND_HIGH,
  });
}

// Fires for all group members except the creator. Copy branches by
// templateType so a new intercession reads differently from other
// spiritual practices.
export async function sendNewGroupMomentPush(
  userId: number,
  opts: { groupSlug: string; momentName: string; templateType: string; creatorName: string }
) {
  const verb = (() => {
    switch (opts.templateType) {
      case "intercession": return "is asking your prayers";
      case "fasting":      return "started a fast";
      case "morning-prayer":
      case "evening-prayer":
                           return "started a prayer practice";
      case "contemplative":
                           return "started a contemplative practice";
      default:             return "started a practice";
    }
  })();
  // Intercessions are treated as prayer requests on the client: the
  // recipient should be able to tap the push, land directly on the
  // prayer slideshow, and pray the new intercession without first
  // navigating to a community page.
  // No badge — see sendNewPrayerRequestPush above. The icon count means
  // "practices left today" and is client-owned; sending an unprayed-
  // intercession count here overwrote it with an unrelated number.
  const isIntercession = opts.templateType === "intercession";
  return sendPushToUser(userId, {
    title: opts.momentName || "Phoebe",
    body: `${opts.creatorName} ${verb}.`,
    path: isIntercession ? `/prayer-mode` : `/communities/${opts.groupSlug}`,
    threadId: `group-moment-${opts.groupSlug}`,
    sound: PHOEBE_SOUND_MID,
  });
}

// Concurrency-limited fan-out of the new-group-practice push. Each recipient's
// intercession badge is computed individually (getUnprayedCount is per-user), so
// publishing one intercession in a large community used to fire hundreds of
// garden COUNT queries + push pipelines AT ONCE (the caller looped with no
// bound) → pool/CPU spike. Cap concurrency like sendPushToUsers.
export async function sendNewGroupMomentPushToMany(
  userIds: number[],
  opts: { groupSlug: string; momentName: string; templateType: string; creatorName: string },
): Promise<void> {
  const unique = Array.from(new Set(userIds.filter(id => Number.isFinite(id))));
  await mapLimit(unique, PUSH_FANOUT_CONCURRENCY, (uid) =>
    sendNewGroupMomentPush(uid, opts).then(() => undefined).catch((err) => {
      logger.warn({ err, uid }, "[push] group moment push failed");
    }));
}

// First-ever amen on a brand-new prayer request — the moment the
// owner's ask stops being theirs alone. Names the first pray-er so the
// owner sees who started carrying it. Fires exactly once per request,
// gated server-side. The collapse-id makes that exactness idempotent
// against any race.
//
// Deep-links to the prayer-request detail slide (not the manage feed),
// so tapping the push lands the owner on a slide-styled view of the
// request itself: the prayer text, the avatar of who said amen, the
// running amen count, and any words of comfort that have been left.
// The earlier `/prayer-list` destination buried that context behind
// another tap.
export function sendFirstAmenPush(
  recipientUserId: number,
  opts: {
    prayerRequestId: number;
    prayerName: string;
    /** Set to the amen-er's user id when they ALREADY left a word of
     *  comfort on this request. The recipient got a word push naming the
     *  same person, so this push MERGES the two: the body covers both,
     *  and the collapse-id reuses the word one so iOS REPLACES that
     *  banner instead of stacking a second notification. */
    withWordFromUserId?: number;
  },
) {
  const firstName = (opts.prayerName || "Someone").split(/\s+/)[0] || "Someone";
  const merged = typeof opts.withWordFromUserId === "number";
  return sendPushToUser(recipientUserId, {
    title: "You've been held in prayer",
    body: merged
      ? `The first amen just went up for your request by ${firstName} — with a word of comfort.`
      : `The first amen just went up for your request by ${firstName}.`,
    // ?amen=1 tells the detail page this is the first-amen landing, so it
    // features the pray-er. Opening the request any other way (e.g. the
    // prayer list) omits the param and shows no single featured amen.
    path: `/prayer-requests/${opts.prayerRequestId}?amen=1`,
    threadId: `prayer-request-${opts.prayerRequestId}`,
    collapseId: merged
      ? prayerWordCollapseId(opts.prayerRequestId, opts.withWordFromUserId as number)
      : firstAmenCollapseId(opts.prayerRequestId),
    sound: PHOEBE_SOUND_HIGH,
  });
}

// "Your prayer is wrapping up tomorrow." Fires once per request, on
// the calendar day BEFORE expiresAt in the owner's timezone. The
// /prayer-requests/:id route doubles as a renewal landing page; tap
// the push to see how many people prayed and decide whether to renew
// or release. Dedup is handled at the caller site (renewalNudgeSentAt
// stamp on prayer_requests).
export function sendPrayerRenewalNudgePush(
  recipientUserId: number,
  opts: { prayerRequestId: number; amenCountTotal: number },
) {
  const carriedCopy = opts.amenCountTotal === 1
    ? "1 amen has gone up so far."
    : opts.amenCountTotal > 0
      ? `${opts.amenCountTotal} amens have gone up so far.`
      : "No rush — you can renew or let it close.";
  return sendPushToUser(recipientUserId, {
    title: "Your prayer is wrapping up tomorrow",
    body: carriedCopy,
    path: `/prayer-requests/${opts.prayerRequestId}?renew=1`,
    threadId: `prayer-request-${opts.prayerRequestId}`,
    collapseId: `renewal-nudge-${opts.prayerRequestId}`,
    sound: PHOEBE_SOUND_LOW,
  });
}

// Daily "you've been held in prayer today" — coalesced batch push.
// Fires 2 hours after the first non-owner amen on a day (in the
// requester's tz), aggregating across ALL of the requester's active
// requests so a user with two requests getting amens gets one warm
// ping, not two. One push per recipient per day, max. See
// prayerHeldScanner.ts for the trigger logic.
//
// Body shapes (where N = totalAmens across all of the user's requests):
//   • 1 request, 1 amen:  "Sara prayed for your request."
//   • 1 request, 2 amens: "Sara and 1 other prayed for your request."
//   • 1 request, N amens: "Sara and {N-1} others prayed for your request."
//   • 2+ requests:        "Sara and others prayed for your requests today."
//
// Always deep-links to a single prayer's detail slide — the same view
// (prayer body + the faces of everyone who prayed) the requester sees
// when they tap the prayer-request card. When the batch spans several
// requests the scanner picks the most-prayed one as the landing slide.
export function sendHeldInPrayerPush(
  recipientUserId: number,
  opts: {
    firstAmenName: string;
    firstAmenAvatarUrl: string | null;
    amenCount: number;
    requestCount: number;
    prayerRequestId: number | null;
    localYmd: string;
  },
) {
  const firstName = (opts.firstAmenName || "Someone").split(/\s+/)[0] || "Someone";
  const body =
    opts.requestCount >= 2
      ? `${firstName} and others prayed for your requests today.`
      : opts.amenCount <= 1
        ? `${firstName} prayed for your request.`
        : opts.amenCount === 2
          ? `${firstName} and 1 other prayed for your request.`
          : `${firstName} and ${opts.amenCount - 1} others prayed for your request.`;
  // Always deep-link to one prayer's detail slide so tapping the push
  // lands on the prayer + the faces of who prayed, exactly like tapping
  // the prayer-request card. The scanner chooses the most-prayed
  // request when the batch covers several. threadId / collapseId use
  // the recipient + day so iOS groups the daily ping under one stream.
  const path =
    opts.prayerRequestId !== null
      ? `/prayer-requests/${opts.prayerRequestId}`
      : `/my-prayer-requests`;
  const threadId = `held-in-prayer-${recipientUserId}-${opts.localYmd}`;
  const collapseId = threadId;
  // Note: opts.firstAmenAvatarUrl is plumbed but not yet surfaced on
  // the lock screen — iOS requires a Notification Service Extension
  // and APNs `mutable-content:1 + attachment-url`, neither of which
  // are wired in this codebase yet. Wiring those would let the
  // pray-er's avatar render next to the title. Keeping the field on
  // the helper so adding NSE support later is a 1-line change here.
  void opts.firstAmenAvatarUrl;
  return sendPushToUser(recipientUserId, {
    title: "You've been held in prayer today 🌿",
    body,
    path,
    threadId,
    collapseId,
    sound: PHOEBE_SOUND_HIGH,
  });
}

// "3 people are praying for you today." Fires the moment the third
// distinct (user, today-in-owner-tz) amen lands. Today is bucketed in
// the owner's timezone so the count matches what they see in the UI.
// Collapse-id includes the date so a request that crosses days can
// fire on each new day, but only once per day.
//
// Deep-links to the same detail slide as the first-amen push so the
// owner can see the three pray-ers + any words at a glance.
export function sendThirdAmenTodayPush(
  recipientUserId: number,
  opts: { prayerRequestId: number; localYmd: string },
) {
  return sendPushToUser(recipientUserId, {
    title: "3 people are praying for you today",
    body: "Your request is being carried.",
    path: `/prayer-requests/${opts.prayerRequestId}`,
    threadId: `prayer-request-${opts.prayerRequestId}`,
    collapseId: `third-amen-${opts.prayerRequestId}-${opts.localYmd}`,
    sound: PHOEBE_SOUND_HIGH,
  });
}

// Fires to all joined group members (except the creator) when an admin
// creates a new community gathering. Names the creator so members know
// who organised it. Tap lands on the community page.
export function sendNewGatheringPush(
  userId: number,
  opts: { ritualId: number; groupSlug: string; gatheringName: string; creatorName: string },
) {
  const firstName = (opts.creatorName || "Someone").split(/\s+/)[0] || "Someone";
  return sendPushToUser(userId, {
    title: opts.gatheringName,
    body: `${firstName} scheduled a gathering.`,
    path: `/communities/${opts.groupSlug}`,
    threadId: `gathering-${opts.ritualId}`,
    collapseId: `new-gathering-${opts.ritualId}`,
    sound: PHOEBE_SOUND_MID,
  });
}

// Day-before reminder for a community gathering. Fires once per meetup,
// deduplicated via meetups.reminder_sent_at. Location-aware body so
// members know where to show up without opening the app.
export function sendGatheringTomorrowPush(
  userId: number,
  opts: { meetupId: number; ritualId: number; groupSlug: string; gatheringName: string; location: string | null },
) {
  const body = opts.location ? `See you at ${opts.location}.` : "See you there.";
  return sendPushToUser(userId, {
    title: `${opts.gatheringName} is tomorrow`,
    body,
    path: `/communities/${opts.groupSlug}`,
    threadId: `gathering-${opts.ritualId}`,
    collapseId: `gathering-tomorrow-${opts.meetupId}`,
    sound: PHOEBE_SOUND_MID,
  });
}

// ── Prayer-feed events ──────────────────────────────────────────────
// Feed events fan out to ALL subscribers of the feed (a different,
// often large population than a community), so these resolve the
// recipient set themselves and use sendPushToUsers. Tap deep-links
// to the in-app feed detail page.

// Published-event push — fired when a feed manager creates an event.
export async function sendNewFeedEventPush(
  feedId: number,
  opts: { feedSlug: string; feedTitle: string; eventTitle: string; eventId: number },
): Promise<void> {
  const subs = await db
    .select({ userId: prayerFeedSubscriptionsTable.userId })
    .from(prayerFeedSubscriptionsTable)
    .where(eq(prayerFeedSubscriptionsTable.feedId, feedId));
  const userIds = subs.map(s => s.userId);
  if (userIds.length === 0) return;
  await sendPushToUsers(userIds, {
    title: opts.eventTitle,
    body: `New event from ${opts.feedTitle}.`,
    path: `/prayer-feeds/${opts.feedSlug}`,
    threadId: `feed-event-${opts.eventId}`,
    collapseId: `new-feed-event-${opts.eventId}`,
    sound: PHOEBE_SOUND_MID,
  });
}

// New-intercession push — fired when an editor publishes (or attaches)
// an intercession to a feed. Fans out to every subscriber of the feed,
// independent of the Tuesday weekly digest (this is the timely "a new
// one just landed" signal; the digest is the curated walk-through).
//
// Title carries the intercession topic so the lock-screen preview tells
// the subscriber what they're being asked to pray for; body names the
// feed for context. Tap deep-links to the feed page where the new card
// shows up at the top of the day's slots.
export async function sendNewFeedIntercessionPush(
  feedId: number,
  opts: {
    feedSlug: string;
    feedTitle: string;
    intercessionTitle: string;
    intercessionId: number;
    excludeUserId?: number; // typically the editor who just published
  },
): Promise<void> {
  const subs = await db
    .select({ userId: prayerFeedSubscriptionsTable.userId })
    .from(prayerFeedSubscriptionsTable)
    .where(eq(prayerFeedSubscriptionsTable.feedId, feedId));
  const userIds = subs
    .map(s => s.userId)
    .filter(id => id !== opts.excludeUserId);
  if (userIds.length === 0) return;
  await sendPushToUsers(userIds, {
    title: opts.intercessionTitle,
    body: `New intercession on ${opts.feedTitle}. Tap to pray.`,
    path: `/prayer-feeds/${opts.feedSlug}`,
    threadId: `feed-intercession-${opts.intercessionId}`,
    collapseId: `new-feed-intercession-${opts.intercessionId}`,
    sound: PHOEBE_SOUND_MID,
  });
}

// Day-before reminder for a feed event. Fired once per event by the
// bell scanner, deduped via prayer_feed_events.reminder_sent_at.
export async function sendFeedEventTomorrowPush(
  feedId: number,
  opts: { feedSlug: string; eventTitle: string; eventId: number; location: string | null },
): Promise<void> {
  const subs = await db
    .select({ userId: prayerFeedSubscriptionsTable.userId })
    .from(prayerFeedSubscriptionsTable)
    .where(eq(prayerFeedSubscriptionsTable.feedId, feedId));
  const userIds = subs.map(s => s.userId);
  if (userIds.length === 0) return;
  const body = opts.location ? `See you at ${opts.location}.` : "See you there.";
  await sendPushToUsers(userIds, {
    title: `${opts.eventTitle} is tomorrow`,
    body,
    path: `/prayer-feeds/${opts.feedSlug}`,
    threadId: `feed-event-${opts.eventId}`,
    collapseId: `feed-event-tomorrow-${opts.eventId}`,
    sound: PHOEBE_SOUND_MID,
  });
}

// (`sendLetterWindowOpenPush` removed — for one-to-one correspondences
// the moment a letter arrives IS the moment the recipient's write
// window opens, so we just branch sendNewLetterPush below by group
// type and use turn-focused copy. For small_group there's no "your
// turn" — anyone can write any time during the period — so the
// generic "you have a new letter" framing stays.)


// Weekly prayer-feed digest — fires Tuesday evening (user TZ) per the
// scheduler in bellSender. Title carries the new-intercession count;
// body adds a "you can act on N of these" line when any of the new
// items are action-type. Deep-links into the digest slideshow.
export function sendWeeklyDigestPush(
  userId: number,
  opts: { count: number; actionCount: number },
): Promise<SendResult> {
  const { count, actionCount } = opts;
  const title = count === 1
    ? "1 new intercession on your feeds"
    : `${count} new intercessions on your feeds`;
  const body =
    actionCount === 0
      ? "Tap to pray them together."
      : actionCount === 1
        ? "Including 1 you can act on. Tap to pray."
        : `Including ${actionCount} you can act on. Tap to pray.`;
  return sendPushToUser(userId, {
    title,
    body,
    path: "/prayer-mode?queue=feed-digest",
    threadId: "weekly-digest",
    // No badge. This hardcoded `badge: 1` was the most likely cause of an
    // icon stuck on "1" while three practices were still undone — see
    // sendNewPrayerRequestPush for why the badge is client-owned.
  });
}

