import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import ritualsRouter from "./rituals";
import authRouter from "./auth";
import peopleRouter from "./people";
import contactsRouter from "./contacts";
import scheduleRouter from "./schedule";
import inviteRouter from "./invite";
import prayerRouter from "./prayer";
import lettersRouter from "./letters";
import phoebeRouter from "./phoebe";
import momentsRouter from "./moments";
import officeRouter from "./office";
import lectioRouter from "./lectio";
import gatheringsRouter from "./gatherings";
import groupsRouter from "./groups";
import bellRouter from "./bell";
import feedbackRouter from "./feedback";
import mutesRouter from "./mutes";
import fellowsRouter from "./fellows";
import gratitudeRouter from "./gratitude";
import prayersForRouter from "./prayers-for";
import waitlistRouter from "./waitlist";
import prayerFeedsRouter from "./prayer-feeds";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(usersRouter);
router.use(ritualsRouter);
router.use(peopleRouter);
router.use(contactsRouter);
router.use(scheduleRouter);
router.use(inviteRouter);
router.use(prayerRouter);
router.use(lettersRouter);
router.use(phoebeRouter);
router.use(momentsRouter);
router.use(officeRouter);
router.use(lectioRouter);
router.use(gatheringsRouter);
router.use(groupsRouter);
router.use(bellRouter);
router.use(feedbackRouter);
router.use(mutesRouter);
router.use(fellowsRouter);
router.use(gratitudeRouter);
router.use(prayersForRouter);
router.use(waitlistRouter);
router.use(prayerFeedsRouter);

export default router;
