// AUTO-GENERATED DATA + seed for the worldwide Anglican Cycle of Prayer,
// turned into a public Prayer Feed (sibling to the Diocese of New York feed).
//
// Source: The Anglican Cycle of Prayer (1 September 2023 – 31 December 2026),
//   prepared for the Anglican Consultative Council.
//   https://www.anglicancommunion.org/resources/cycle-of-prayer.aspx
// LICENSE (printed in the source PDF): "The Anglican Cycle of Prayer may be
//   freely copied, adapted, distributed and shared without the need to acquire
//   specific permission from the copyright holder; on the condition that no
//   charge is made for its use." © The Anglican Consultative Council.
//   Phoebe's prayer feed is free, so this use falls within that grant; we
//   attribute the Communion in the feed tagline.
//
// One intention per calendar day for 2026 — the diocese or province the
// Communion prays for that day (parsed from the source, weekday-verified against
// the calendar). Platform-owned (creatorUserId NULL), live, and public so any
// signed-in account can find it in /prayer-feeds and subscribe. Seeded
// idempotently on every boot from migrate.ts — re-running keeps titles fresh
// without clobbering subscriptions or pray counts.
import { db, prayerFeedsTable, prayerFeedEntriesTable } from "@workspace/db";
import { eq, and, sql } from "drizzle-orm";

const FEED = {
  slug: "anglican-cycle-of-prayer",
  title: "Anglican Cycle of Prayer",
  tagline:
    "Pray with the worldwide Anglican Communion — one of its dioceses or provinces each day, from the Communion's own Cycle of Prayer.",
  coverEmoji: "🌍",
  timezone: "America/New_York",
};

// No body: the intention IS the entry title (the diocese/province to pray for),
// so an empty body hides the body box entirely — same as the Diocese of NY feed.
const BODY = "";

// One row per calendar day. `d` is a naive YYYY-MM-DD interpreted in the feed's
// timezone; `t` is that day's intention (diocese – province, or a province on
// Sundays / principal feasts).
const ENTRIES: { d: string; t: string }[] = [
  { d: "2026-01-01", t: "The Diocese of Seychelles – The Church of the Province of the Indian Ocean" },
  { d: "2026-01-02", t: "The Diocese of Sheffield – The Church of England" },
  { d: "2026-01-03", t: "The Diocese of Shinyanga – The Anglican Church of Tanzania" },
  { d: "2026-01-04", t: "The Church of the Province of Central Africa" },
  { d: "2026-01-05", t: "The Diocese of Upper Shire – The Church of the Province of Central Africa" },
  { d: "2026-01-06", t: "The Diocese of Shyira – Eglise Anglicane du Rwanda" },
  { d: "2026-01-07", t: "The Diocese of Shyogwe – Eglise Anglicane du Rwanda" },
  { d: "2026-01-08", t: "The Diocese of Sialkot – The Church of Pakistan (United)" },
  { d: "2026-01-09", t: "The Diocese of Singapore – Church of the Province of South East Asia" },
  { d: "2026-01-10", t: "The Diocese of Sittwe – The Church of the Province of Myanmar (Burma)" },
  { d: "2026-01-11", t: "Iglesia Anglicana de la Region Central de America" },
  { d: "2026-01-12", t: "The Diocese of Sodor and Man – The Church of England" },
  { d: "2026-01-13", t: "The Diocese of Sokoto – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-01-14", t: "The Diocese of Central Solomons – The Anglican Church of Melanesia" },
  { d: "2026-01-15", t: "The Diocese of Soroti – The Church of the Province of Uganda" },
  { d: "2026-01-16", t: "The Diocese of Southwark – The Church of England" },
  { d: "2026-01-17", t: "The Diocese of Southwell and Nottingham – The Church of England" },
  { d: "2026-01-18", t: "Province de L’Eglise Anglicane Du Congo" },
  { d: "2026-01-19", t: "The Reformed Episcopal Church of the Reformed Episcopal Church of Spain – (Extra Provincial)" },
  { d: "2026-01-20", t: "The Diocese of Spokane – The Episcopal Church" },
  { d: "2026-01-21", t: "The Diocese of Springfield – The Episcopal Church" },
  { d: "2026-01-22", t: "The Diocese of Port Sudan – Province of the Episcopal Church of Sudan" },
  { d: "2026-01-23", t: "The Diocese of Sul Occidental – Igreja Episcopal Anglicana do Brasil" },
  { d: "2026-01-24", t: "The Diocese of Sunyani – The Church of the Province of West Africa" },
  { d: "2026-01-25", t: "Iglesia Anglicana de Chile" },
  { d: "2026-01-26", t: "The Diocese of Sur – Iglesia Anglicana de Chile" },
  { d: "2026-01-27", t: "The Diocese of Del Sureste – La Iglesia Anglicana de Mexico" },
  { d: "2026-01-28", t: "The Diocese of Swansea and Brecon – The Church in Wales" },
  { d: "2026-01-29", t: "The Diocese of Sydney – The Anglican Church of Australia" },
  { d: "2026-01-30", t: "The Diocese of Tabora – The Anglican Church of Tanzania" },
  { d: "2026-01-31", t: "Te Pihopatanga o Te Tai Tokerau – The Anglican Church in Aotearoa, New Zealand and Polynesia" },
  { d: "2026-02-01", t: "The Church of England" },
  { d: "2026-02-02", t: "Te Pihopatanga o Te Tairawhiti – The Anglican Church in Aotearoa, New Zealand and Polynesia" },
  { d: "2026-02-03", t: "The Diocese of Taita-Taveta – The Anglican Church of Kenya" },
  { d: "2026-02-04", t: "The Diocese of Taiwan – The Episcopal Church" },
  { d: "2026-02-05", t: "The Diocese of Tamale – The Church of the Province of West Africa" },
  { d: "2026-02-06", t: "The Diocese of Tanga – The Anglican Church of Tanzania" },
  { d: "2026-02-07", t: "The Diocese of Central Tanganyika – The Anglican Church of Tanzania" },
  { d: "2026-02-08", t: "Hong Kong Sheng Kung Hui" },
  { d: "2026-02-09", t: "The Diocese of South West Tanganyika – The Anglican Church of Tanzania" },
  { d: "2026-02-10", t: "The Diocese of Western Tanganyika – The Anglican Church of Tanzania" },
  { d: "2026-02-11", t: "The Diocese of Tarime – The Anglican Church of Tanzania" },
  { d: "2026-02-12", t: "The Diocese of Tasmania – The Anglican Church of Australia" },
  { d: "2026-02-13", t: "The Diocese of Taungoo – The Church of the Province of Myanmar (Burma)" },
  { d: "2026-02-14", t: "The Diocese of Temotu – The Anglican Church of Melanesia" },
  { d: "2026-02-15", t: "The Church of the Province of the Indian Ocean" },
  { d: "2026-02-16", t: "The Diocese of Tennessee – The Episcopal Church" },
  { d: "2026-02-17", t: "The Diocese of East Tennessee – The Episcopal Church" },
  { d: "2026-02-18", t: "The Diocese of West Tennessee – The Episcopal Church" },
  { d: "2026-02-19", t: "The Diocese of Terekeka – Province of the Episcopal Church of South Sudan" },
  { d: "2026-02-20", t: "The Teritory of the People – The Anglican Church of Canada" },
  { d: "2026-02-21", t: "The Missionary Diocese of Tete – Igreja Anglicana de Mocambique e Angola" },
  { d: "2026-02-22", t: "The Church of Ireland" },
  { d: "2026-02-23", t: "The Diocese of Texas – The Episcopal Church" },
  { d: "2026-02-24", t: "The Diocese of Northwest Texas – The Episcopal Church" },
  { d: "2026-02-25", t: "The Diocese of West Texas – The Episcopal Church" },
  { d: "2026-02-26", t: "The Diocese of Thika – The Anglican Church of Kenya" },
  { d: "2026-02-27", t: "The Diocese of Thoothukudi – Nazareth – The Church of South India (United)" },
  { d: "2026-02-28", t: "The Diocese of Tirunelveli – The Church of South India (United)" },
  { d: "2026-03-01", t: "The Nippon Sei Ko Kai" },
  { d: "2026-03-02", t: "The Diocese of Toamasina – The Church of the Province of the Indian Ocean" },
  { d: "2026-03-03", t: "The Diocese of Tohoku – The Nippon Sei Ko Kai" },
  { d: "2026-03-04", t: "The Diocese of Tokyo – The Nippon Sei Ko Kai" },
  { d: "2026-03-05", t: "The Diocese of Toliara – The Church of the Province of the Indian Ocean" },
  { d: "2026-03-06", t: "The Diocese of Tonj – Province of the Episcopal Church of South Sudan" },
  { d: "2026-03-07", t: "The Diocese of Torit – Province of the Episcopal Church of South Sudan" },
  { d: "2026-03-08", t: "The Episcopal Church in Jerusalem & The Middle East" },
  { d: "2026-03-09", t: "The Diocese of Toronto – The Anglican Church of Canada" },
  { d: "2026-03-10", t: "The Diocese of Trichy-Tanjore – The Church of South India (United)" },
  { d: "2026-03-11", t: "The Diocese of Trinidad and Tobago – The Church in the Province of the West Indies" },
  { d: "2026-03-12", t: "The Diocese of Truro – The Church of England" },
  { d: "2026-03-13", t: "The Diocese of Tuam, Limerick and Killaloe – The Church of Ireland" },
  { d: "2026-03-14", t: "The Diocese of Twik East – Province of the Episcopal Church of South Sudan" },
  { d: "2026-03-15", t: "The Anglican Church of Kenya" },
  { d: "2026-03-16", t: "The Diocese of Udi – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-03-17", t: "The Diocese of Northern Uganda – The Church of the Province of Uganda" },
  { d: "2026-03-18", t: "The Diocese of Ughelli – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-03-19", t: "The Diocese of Ukwa – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-03-20", t: "The Diocese of Umuahia – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-03-21", t: "Te Pihopatanga o Te Upoko o Te Ika – The Anglican Church in Aotearoa, New Zealand and Polynesia" },
  { d: "2026-03-22", t: "The Anglican Church of Korea" },
  { d: "2026-03-23", t: "The Diocese of Uruguay – The Anglican Church of South America" },
  { d: "2026-03-24", t: "The Diocese of Utah – The Episcopal Church" },
  { d: "2026-03-25", t: "The Diocese of Uyo – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-03-26", t: "The Diocese of Valparaiso – Iglesia Anglicana de Chile" },
  { d: "2026-03-27", t: "The Diocese of Vanuatu – The Anglican Church of Melanesia" },
  { d: "2026-03-28", t: "The Diocese of Vellore – The Church of South India (United)" },
  { d: "2026-03-29", t: "The Anglican Church of Melanesia" },
  { d: "2026-03-30", t: "The Diocese of Venezuela – The Episcopal Church" },
  { d: "2026-03-31", t: "The Diocese of Vermont – The Episcopal Church" },
  { d: "2026-04-01", t: "The Diocese of Victoria Nyanza – The Anglican Church of Tanzania" },
  { d: "2026-04-02", t: "The Diocese of Virgin Islands – The Episcopal Church" },
  { d: "2026-04-03", t: "The Diocese of Virginia – The Episcopal Church" },
  { d: "2026-04-04", t: "The Diocese of Southern Virginia – The Episcopal Church" },
  { d: "2026-04-05", t: "La Iglesia Anglicana de Mexico" },
  { d: "2026-04-06", t: "The Diocese of Southwestern Virginia – The Episcopal Church" },
  { d: "2026-04-07", t: "The Diocese of West Virginia – The Episcopal Church" },
  { d: "2026-04-08", t: "The Diocese of Wad Medani – Province of the Episcopal Church of Sudan" },
  { d: "2026-04-09", t: "The Diocese of Waiapu – The Anglican Church in Aotearoa, New Zealand and Polynesia" },
  { d: "2026-04-10", t: "The Diocese of Waikato and Taranaki – The Anglican Church in Aotearoa, New Zealand and Polynesia" },
  { d: "2026-04-11", t: "Te Pihopatanga o Te Waipounamu – The Anglican Church in Aotearoa, New Zealand and Polynesia" },
  { d: "2026-04-12", t: "Igreja Anglicana de Mocambique e Angola" },
  { d: "2026-04-13", t: "The Diocese of Wandi – Province of the Episcopal Church of South Sudan" },
  { d: "2026-04-14", t: "The Diocese of Wangaratta – The Anglican Church of Australia" },
  { d: "2026-04-15", t: "The Diocese of Wanglei – Province of the Episcopal Church of South Sudan" },
  { d: "2026-04-16", t: "The Diocese of Wanyjok – Province of the Episcopal Church of South Sudan" },
  { d: "2026-04-17", t: "The Diocese of Warri – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-04-18", t: "The Diocese of Washington – The Episcopal Church" },
  { d: "2026-04-19", t: "The Church of the Province of Myanmar (Burma)" },
  { d: "2026-04-20", t: "The Diocese of Wau – Province of the Episcopal Church of South Sudan" },
  { d: "2026-04-21", t: "The Diocese of Wellington – The Anglican Church in Aotearoa, New Zealand and Polynesia" },
  { d: "2026-04-22", t: "The Diocese of Wernyol – Province of the Episcopal Church of South Sudan" },
  { d: "2026-04-23", t: "The Diocese of Wiawso – The Church of the Province of West Africa" },
  { d: "2026-04-24", t: "The Diocese of Willochra – The Anglican Church of Australia" },
  { d: "2026-04-25", t: "The Diocese of Winchester – The Church of England" },
  { d: "2026-04-26", t: "The Church of Nigeria (Anglican Communion)" },
  { d: "2026-04-27", t: "The Diocese of Windward Islands – The Church in the Province of the West Indies" },
  { d: "2026-04-28", t: "The Diocese of Wondurba – Province of the Episcopal Church of South Sudan" },
  { d: "2026-04-29", t: "The Diocese of Worcester – The Church of England" },
  { d: "2026-04-30", t: "The Diocese of Wulu – Province of the Episcopal Church of South Sudan" },
  { d: "2026-05-01", t: "The Diocese of Wusasa – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-05-02", t: "The Diocese of Wyoming – The Episcopal Church" },
  { d: "2026-05-03", t: "The Church of North India (United)" },
  { d: "2026-05-04", t: "The Diocese of Yambio – Province of the Episcopal Church of South Sudan" },
  { d: "2026-05-05", t: "The Diocese of Yangon – The Church of the Province of Myanmar (Burma)" },
  { d: "2026-05-06", t: "The Diocese of Yei – Province of the Episcopal Church of South Sudan" },
  { d: "2026-05-07", t: "The Diocese of Yeri – Province of the Episcopal Church of South Sudan" },
  { d: "2026-05-08", t: "The Diocese of Yewa – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-05-09", t: "The Diocese of Yirol – Province of the Episcopal Church of South Sudan" },
  { d: "2026-05-10", t: "The Church of Pakistan (United)" },
  { d: "2026-05-11", t: "The Diocese of Yokohama – The Nippon Sei Ko Kai" },
  { d: "2026-05-12", t: "The Diocese of Yola – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-05-13", t: "The Diocese of York – The Church of England" },
  { d: "2026-05-14", t: "The Diocese of New York – The Episcopal Church" },
  { d: "2026-05-15", t: "The Diocese of Western New York – The Episcopal Church" },
  { d: "2026-05-16", t: "The Diocese of Ysabel – The Anglican Church of Melanesia" },
  { d: "2026-05-17", t: "The Anglican Church of Papua New Guinea" },
  { d: "2026-05-18", t: "The Diocese of Yukon – The Anglican Church of Canada" },
  { d: "2026-05-19", t: "The Diocese of Zaki-Biam – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-05-20", t: "The Missionary Diocese of Zambezia – Igreja Anglicana de Mocambique e Angola" },
  { d: "2026-05-21", t: "The Diocese of Central Zambia – The Church of the Province of Central Africa" },
  { d: "2026-05-22", t: "The Diocese of Eastern Zambia – The Church of the Province of Central Africa" },
  { d: "2026-05-23", t: "The Diocese of Northern Zambia – The Church of the Province of Central Africa" },
  { d: "2026-05-24", t: "Anglican Communion Sunday Thy Kingdom Come The Episcopal Church in the Philippines" },
  { d: "2026-05-25", t: "The Diocese of Zanzibar – The Anglican Church of Tanzania" },
  { d: "2026-05-26", t: "The Diocese of Zaria – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-05-27", t: "The Diocese of Central Zimbabwe – The Church of the Province of Central Africa" },
  { d: "2026-05-28", t: "The Diocese of Ziwa Rukwa – The Anglican Church of Tanzania" },
  { d: "2026-05-29", t: "The Diocese of Zonkwa – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-05-30", t: "The Diocese of Zululand – The Anglican Church of Southern Africa" },
  { d: "2026-05-31", t: "Eglise Anglicane du Rwanda" },
  { d: "2026-06-01", t: "The Diocese of Aba – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-06-02", t: "The Diocese of Aba Ngwa North – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-06-03", t: "The Diocese of Abakaliki – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-06-04", t: "The Diocese of Aberdeen and Orkney – The Scottish Episcopal Church" },
  { d: "2026-06-05", t: "The Diocese of Abuja – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-06-06", t: "The Diocese of Abyei – Province of the Episcopal Church of South Sudan" },
  { d: "2026-06-07", t: "The Scottish Episcopal Church" },
  { d: "2026-06-08", t: "The Diocese of Accra – The Church of the Province of West Africa" },
  { d: "2026-06-09", t: "The Diocese of Adelaide – The Anglican Church of Australia" },
  { d: "2026-06-10", t: "The Diocese of Afikpo – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-06-11", t: "The Diocese of North Africa – The Episcopal / Anglican Province of Alexandria" },
  { d: "2026-06-12", t: "The Diocese of Agra – The Church of North India (United)" },
  { d: "2026-06-13", t: "The Diocese of Aguata – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-06-14", t: "Church of the Province of South East Asia" },
  { d: "2026-06-15", t: "The Diocese of Ahoada – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-06-16", t: "The Diocese of Aipo Rongo – The Anglican Church of Papua New Guinea" },
  { d: "2026-06-17", t: "The Diocese of Ajayi Crowther – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-06-18", t: "The Diocese of Akobo – Province of the Episcopal Church of South Sudan" },
  { d: "2026-06-19", t: "The Diocese of Akoko – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-06-20", t: "The Diocese of Akoko Edo – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-06-21", t: "The Church of South India (United)" },
  { d: "2026-06-22", t: "The Diocese of Akot – Province of the Episcopal Church of South Sudan" },
  { d: "2026-06-23", t: "The Diocese of Akure – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-06-24", t: "The Diocese of Alabama – The Episcopal Church" },
  { d: "2026-06-25", t: "The Diocese of Alaska – The Episcopal Church" },
  { d: "2026-06-26", t: "The Diocese of Saint Albans – The Church of England" },
  { d: "2026-06-27", t: "The Diocese of Albany – The Episcopal Church" },
  { d: "2026-06-28", t: "The Anglican Church of Southern Africa" },
  { d: "2026-06-29", t: "The Diocese of Algoma – The Anglican Church of Canada" },
  { d: "2026-06-30", t: "The Diocese of All Saints – The Anglican Church of Kenya" },
  { d: "2026-07-01", t: "The Diocese of Aluakluak – Province of the Episcopal Church of South Sudan" },
  { d: "2026-07-02", t: "The Diocese of Amazônia – Igreja Episcopal Anglicana do Brasil" },
  { d: "2026-07-03", t: "The Diocese of Amichi – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-07-04", t: "The Diocese of Amritsar – The Church of North India (United)" },
  { d: "2026-07-05", t: "The Anglican Church of South America" },
  { d: "2026-07-06", t: "The Diocese of Andaman and Car Nicobar Islands – The Church of North India (United)" },
  { d: "2026-07-07", t: "The Diocese of Saint Andrews, Dunkeld and Dunblane – The Scottish Episcopal Church" },
  { d: "2026-07-08", t: "The Missionary Diocese of Central and South Angola – Igreja Anglicana de Mocambique e Angola" },
  { d: "2026-07-09", t: "The Diocese of Ankole – The Church of the Province of Uganda" },
  { d: "2026-07-10", t: "The Diocese of North Ankole – The Church of the Province of Uganda" },
  { d: "2026-07-11", t: "The Diocese of Northwest Ankole – The Church of the Province of Uganda" },
  { d: "2026-07-12", t: "Province of the Episcopal Church of South Sudan" },
  { d: "2026-07-13", t: "The Diocese of South Ankole – The Church of the Province of Uganda" },
  { d: "2026-07-14", t: "The Diocese of West Ankole – The Church of the Province of Uganda" },
  { d: "2026-07-15", t: "The Diocese of Antananarivo – The Church of the Province of the Indian Ocean" },
  { d: "2026-07-16", t: "The Diocese of Antsiranana – The Church of the Province of the Indian Ocean" },
  { d: "2026-07-17", t: "Te Pihopatanga o Aotearoa – The Anglican Church in Aotearoa, New Zealand and Polynesia" },
  { d: "2026-07-18", t: "The Diocese of Araucanía – Iglesia Anglicana de Chile" },
  { d: "2026-07-19", t: "Province of the Episcopal Church of Sudan" },
  { d: "2026-07-20", t: "The Diocese of the Arctic – The Anglican Church of Canada" },
  { d: "2026-07-21", t: "The Diocese of Argentina – The Anglican Church of South America" },
  { d: "2026-07-22", t: "The Diocese of Northern Argentina – The Anglican Church of South America" },
  { d: "2026-07-23", t: "The Diocese of Argyll and The Isles – The Scottish Episcopal Church" },
  { d: "2026-07-24", t: "The Diocese of Arizona – The Episcopal Church" },
  { d: "2026-07-25", t: "The Diocese of Arkansas – The Episcopal Church" },
  { d: "2026-07-26", t: "The Anglican Church of Tanzania" },
  { d: "2026-07-27", t: "The Diocese of Armagh – The Church of Ireland" },
  { d: "2026-07-28", t: "The Diocese of Armidale – The Anglican Church of Australia" },
  { d: "2026-07-29", t: "The Diocese of Arochukwu / Ohafia – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-07-30", t: "The Diocese of Aru – Province de L’Eglise Anglicane Du Congo" },
  { d: "2026-07-31", t: "The Diocese of Asaba – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-08-01", t: "The Diocese of Asante-Mampong – The Church of the Province of West Africa" },
  { d: "2026-08-02", t: "The Church of the Province of Uganda" },
  { d: "2026-08-03", t: "The Diocese of Saint Asaph – The Church in Wales" },
  { d: "2026-08-04", t: "The Diocese of Athabasca – The Anglican Church of Canada" },
  { d: "2026-08-05", t: "The Diocese of Atlanta – The Episcopal Church" },
  { d: "2026-08-06", t: "The Diocese of Attooch – Province of the Episcopal Church of South Sudan" },
  { d: "2026-08-07", t: "The Diocese of Auckland – The Anglican Church in Aotearoa, New Zealand and Polynesia" },
  { d: "2026-08-08", t: "The Diocese of North West Australia – The Anglican Church of Australia" },
  { d: "2026-08-09", t: "The Episcopal Church" },
  { d: "2026-08-10", t: "The Diocese of Aweil – Province of the Episcopal Church of South Sudan" },
  { d: "2026-08-11", t: "The Diocese of Awerial – Province of the Episcopal Church of South Sudan" },
  { d: "2026-08-12", t: "The Diocese of Awgu / Aninri – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-08-13", t: "The Diocese of Awka – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-08-14", t: "The Diocese of Awori – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-08-15", t: "The Diocese of Ayod – Province of the Episcopal Church of South Sudan" },
  { d: "2026-08-16", t: "The Church in Wales" },
  { d: "2026-08-17", t: "The Diocese of Badagry – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-08-18", t: "The Diocese of Bahamas and The Turks and Caicos Islands – The Church in the Province of the West Indies" },
  { d: "2026-08-19", t: "The Diocese of Ballarat – The Anglican Church of Australia" },
  { d: "2026-08-20", t: "The Diocese of Bangor – The Church in Wales" },
  { d: "2026-08-21", t: "The Diocese of Banks and Torres – The Anglican Church of Melanesia" },
  { d: "2026-08-22", t: "The Diocese of Barbados – The Church in the Province of the West Indies" },
  { d: "2026-08-23", t: "The Church of the Province of West Africa" },
  { d: "2026-08-24", t: "The Diocese of Bari – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-08-25", t: "The Diocese of Baringo – The Anglican Church of Kenya" },
  { d: "2026-08-26", t: "The Diocese of Barisal – The Church of Bangladesh" },
  { d: "2026-08-27", t: "The Diocese of Barrackpore – The Church of North India (United)" },
  { d: "2026-08-28", t: "The Diocese of Bath and Wells – The Church of England" },
  { d: "2026-08-29", t: "The Diocese of Bathurst – The Anglican Church of Australia" },
  { d: "2026-08-30", t: "The Church in the Province of the West Indies" },
  { d: "2026-08-31", t: "The Diocese of Bauchi – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-09-01", t: "The Diocese of Belize – The Church in the Province of the West Indies" },
  { d: "2026-09-02", t: "The Diocese of Bendigo – The Anglican Church of Australia" },
  { d: "2026-09-03", t: "The Diocese of Beni – Province de L’Eglise Anglicane Du Congo" },
  { d: "2026-09-04", t: "The Diocese of Benin – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-09-05", t: "The Diocese of Bentiu – Province of the Episcopal Church of South Sudan" },
  { d: "2026-09-06", t: "The Episcopal / Anglican Province of Alexandria" },
  { d: "2026-09-07", t: "The Diocese of Bermuda – (Extra Provincial)" },
  { d: "2026-09-08", t: "The Diocese of Bethlehem – The Episcopal Church" },
  { d: "2026-09-09", t: "The Diocese of Bhopal – The Church of North India (United)" },
  { d: "2026-09-10", t: "The Diocese of Bida – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-09-11", t: "The Diocese of Biharamulo – The Anglican Church of Tanzania" },
  { d: "2026-09-12", t: "The Diocese of Birmingham – The Church of England" },
  { d: "2026-09-13", t: "The Anglican Church in Aotearoa, New Zealand and Polynesia" },
  { d: "2026-09-14", t: "The Diocese of Blackburn – The Church of England" },
  { d: "2026-09-15", t: "The Diocese of Bo – The Church of the Province of West Africa" },
  { d: "2026-09-16", t: "The Diocese of Boga – Province de L’Eglise Anglicane Du Congo" },
  { d: "2026-09-17", t: "The Diocese of Bolivia – The Anglican Church of South America" },
  { d: "2026-09-18", t: "The Diocese of Bondo – The Anglican Church of Kenya" },
  { d: "2026-09-19", t: "The Diocese of Bor – Province of the Episcopal Church of South Sudan" },
  { d: "2026-09-20", t: "The Anglican Church of Australia" },
  { d: "2026-09-21", t: "The Diocese of Botswana – The Church of the Province of Central Africa" },
  { d: "2026-09-22", t: "The Diocese of Brandon – The Anglican Church of Canada" },
  { d: "2026-09-23", t: "The Diocese of Brechin – The Scottish Episcopal Church" },
  { d: "2026-09-24", t: "The Diocese of Brisbane – The Anglican Church of Australia" },
  { d: "2026-09-25", t: "The Diocese of Bristol – The Church of England" },
  { d: "2026-09-26", t: "The Diocese of British Columbia – The Anglican Church of Canada" },
  { d: "2026-09-27", t: "The Church of Bangladesh" },
  { d: "2026-09-28", t: "The Diocese of Central Buganda – The Church of the Province of Uganda" },
  { d: "2026-09-29", t: "The Diocese of West Buganda – The Church of the Province of Uganda" },
  { d: "2026-09-30", t: "The Diocese of Buhiga – The Anglican Church of Burundi" },
  { d: "2026-10-01", t: "The Diocese of Bujumbura – The Anglican Church of Burundi" },
  { d: "2026-10-02", t: "The Diocese of Bukavu – Province de L’Eglise Anglicane Du Congo" },
  { d: "2026-10-03", t: "The Diocese of Bukedi – The Church of the Province of Uganda" },
  { d: "2026-10-04", t: "Igreja Episcopal Anglicana do Brasil" },
  { d: "2026-10-05", t: "The Diocese of Bukuru – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-10-06", t: "The Diocese of Bunbury – The Anglican Church of Australia" },
  { d: "2026-10-07", t: "The Diocese of Bungoma – The Anglican Church of Kenya" },
  { d: "2026-10-08", t: "The Diocese of Bunyoro-Kitara – The Church of the Province of Uganda" },
  { d: "2026-10-09", t: "The Diocese of Busan – The Anglican Church of Korea" },
  { d: "2026-10-10", t: "The Diocese of Busoga – The Church of the Province of Uganda" },
  { d: "2026-10-11", t: "The Anglican Church of Burundi" },
  { d: "2026-10-12", t: "The Diocese of Central Busoga – The Church of the Province of Uganda" },
  { d: "2026-10-13", t: "The Diocese of Butare – Eglise Anglicane du Rwanda" },
  { d: "2026-10-14", t: "The Diocese of Butere – The Anglican Church of Kenya" },
  { d: "2026-10-15", t: "The Diocese of Buye – The Anglican Church of Burundi" },
  { d: "2026-10-16", t: "The Diocese of Byumba – Eglise Anglicane du Rwanda" },
  { d: "2026-10-17", t: "The Diocese of Calabar – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-10-18", t: "The Anglican Church of Canada" },
  { d: "2026-10-19", t: "The Diocese of Calcutta – The Church of North India (United)" },
  { d: "2026-10-20", t: "The Diocese of Caledonia – The Anglican Church of Canada" },
  { d: "2026-10-21", t: "The Diocese of Calgary – The Anglican Church of Canada" },
  { d: "2026-10-22", t: "The Diocese of California – The Episcopal Church" },
  { d: "2026-10-23", t: "The Diocese of Northern California – The Episcopal Church" },
  { d: "2026-10-24", t: "The Diocese of Cameroon – The Church of the Province of West Africa" },
  { d: "2026-10-25", t: "The Church of the Province of Central Africa" },
  { d: "2026-10-26", t: "The Diocese of El Camino Real – The Episcopal Church" },
  { d: "2026-10-27", t: "The Diocese of Canberra and Goulburn – The Anglican Church of Australia" },
  { d: "2026-10-28", t: "The Diocese of Canterbury – The Church of England" },
  { d: "2026-10-29", t: "The Diocese of Cape Coast – The Church of the Province of West Africa" },
  { d: "2026-10-30", t: "The Diocese of Cape Town – The Anglican Church of Southern Africa" },
  { d: "2026-10-31", t: "The Diocese of North Eastern Caribbean and Aruba – The Church in the Province of the West Indies" },
  { d: "2026-11-01", t: "Iglesia Anglicana de la Region Central de America" },
  { d: "2026-11-02", t: "The Diocese of Carlisle – The Church of England" },
  { d: "2026-11-03", t: "The Diocese of East Carolina – The Episcopal Church" },
  { d: "2026-11-04", t: "The Diocese of North Carolina – The Episcopal Church" },
  { d: "2026-11-05", t: "The Diocese of South Carolina – The Episcopal Church" },
  { d: "2026-11-06", t: "The Diocese of Upper South Carolina – The Episcopal Church" },
  { d: "2026-11-07", t: "The Diocese of Western North Carolina – The Episcopal Church" },
  { d: "2026-11-08", t: "Province de L’Eglise Anglicane Du Congo" },
  { d: "2026-11-09", t: "The Diocese of Cashel, Ferns and Ossory – The Church of Ireland" },
  { d: "2026-11-10", t: "The Diocese of Chandigarh – The Church of North India (United)" },
  { d: "2026-11-11", t: "The Diocese of Chelmsford – The Church of England" },
  { d: "2026-11-12", t: "The Diocese of Chester – The Church of England" },
  { d: "2026-11-13", t: "The Diocese of Chhattisgarh – The Church of North India (United)" },
  { d: "2026-11-14", t: "The Diocese of Chicago – The Episcopal Church" },
  { d: "2026-11-15", t: "Iglesia Anglicana de Chile" },
  { d: "2026-11-16", t: "The Diocese of Chichester – The Church of England" },
  { d: "2026-11-17", t: "The Diocese of Chotanagpur – The Church of North India (United)" },
  { d: "2026-11-18", t: "The Diocese of Christ the King – Igreja Anglicana de Mocambique e Angola" },
  { d: "2026-11-19", t: "The Diocese of Christ the King – The Anglican Church of Southern Africa" },
  { d: "2026-11-20", t: "The Diocese of Christchurch – The Anglican Church in Aotearoa, New Zealand and Polynesia" },
  { d: "2026-11-21", t: "The Diocese of Chubu – The Nippon Sei Ko Kai" },
  { d: "2026-11-22", t: "The Church of England" },
  { d: "2026-11-23", t: "The Diocese of Clogher – The Church of Ireland" },
  { d: "2026-11-24", t: "The Diocese on the Coast – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-11-25", t: "The Diocese of Cochin – The Church of South India (United)" },
  { d: "2026-11-26", t: "The Diocese of Coimbatore – The Church of South India (United)" },
  { d: "2026-11-27", t: "The Diocese of Colombia – The Episcopal Church" },
  { d: "2026-11-28", t: "The Diocese of Colombo – The Church of Ceylon (Extra Provincial)" },
  { d: "2026-11-29", t: "Hong Kong Sheng Kung Hui" },
  { d: "2026-11-30", t: "The Diocese of Colorado – The Episcopal Church" },
  { d: "2026-12-01", t: "The Diocese of Congo Brazzaville – Province de L’Eglise Anglicane Du Congo" },
  { d: "2026-12-02", t: "The Diocese of Connecticut – The Episcopal Church" },
  { d: "2026-12-03", t: "The Diocese of Connor – The Church of Ireland" },
  { d: "2026-12-04", t: "The Diocese of Cork, Cloyne and Ross – The Church of Ireland" },
  { d: "2026-12-05", t: "The Diocese of Costa Rica – Iglesia Anglicana de la Region Central de America" },
  { d: "2026-12-06", t: "The Church of the Province of the Indian Ocean" },
  { d: "2026-12-07", t: "The Diocese of Coventry – The Church of England" },
  { d: "2026-12-08", t: "The Diocese of Cuba – The Episcopal Church" },
  { d: "2026-12-09", t: "The Diocese of Cueibet – Province of the Episcopal Church of South Sudan" },
  { d: "2026-12-10", t: "The Diocese of Cuernavaca – La Iglesia Anglicana de Mexico" },
  { d: "2026-12-11", t: "The Diocese of Cuttack – The Church of North India (United)" },
  { d: "2026-12-12", t: "The Diocese of Cyangugu – Eglise Anglicane du Rwanda" },
  { d: "2026-12-13", t: "The Church of Ireland" },
  { d: "2026-12-14", t: "The Diocese of Cyprus and the Gulf – The Episcopal Church in Jerusalem and The Middle East" },
  { d: "2026-12-15", t: "The Diocese of Daejeon – The Anglican Church of Korea" },
  { d: "2026-12-16", t: "The Diocese of North Dakota – The Episcopal Church" },
  { d: "2026-12-17", t: "The Diocese of South Dakota – The Episcopal Church" },
  { d: "2026-12-18", t: "The Diocese of Dallas – The Episcopal Church" },
  { d: "2026-12-19", t: "The Diocese of Damaturu – The Church of Nigeria (Anglican Communion)" },
  { d: "2026-12-20", t: "The Nippon Sei Ko Kai" },
  { d: "2026-12-21", t: "The Diocese of Dar-es-Salaam – The Anglican Church of Tanzania" },
  { d: "2026-12-22", t: "The Diocese of Davao – The Episcopal Church in the Philippines" },
  { d: "2026-12-23", t: "The Diocese of Saint Davids – The Church in Wales" },
  { d: "2026-12-24", t: "The Diocese of Delaware – The Episcopal Church" },
  { d: "2026-12-25", t: "The Diocese of Delhi – The Church of North India (United)" },
  { d: "2026-12-26", t: "The Diocese of Derby – The Church of England" },
  { d: "2026-12-27", t: "The Episcopal Church in Jerusalem & The Middle East" },
  { d: "2026-12-28", t: "The Diocese of Derry and Raphoe – The Church of Ireland" },
  { d: "2026-12-29", t: "The Diocese of Dhaka – The Church of Bangladesh" },
  { d: "2026-12-30", t: "The Diocese of San Diego – The Episcopal Church" },
  { d: "2026-12-31", t: "The Diocese of Divine Hope – Igreja Anglicana de Mocambique e Angola" },
];

export async function seedAnglicanCycleOfPrayer(): Promise<number> {
  // Upsert the feed itself (platform-owned). Keep presentation fields + public
  // visibility fresh on every boot; only PROMOTE a never-launched draft to live
  // so a deliberate admin "pause" is never silently undone.
  await db
    .insert(prayerFeedsTable)
    .values({
      slug: FEED.slug,
      title: FEED.title,
      tagline: FEED.tagline,
      coverEmoji: FEED.coverEmoji,
      timezone: FEED.timezone,
      state: "live",
      visibility: "public",
      kind: "general",
      creatorUserId: null,
    })
    .onConflictDoUpdate({
      target: prayerFeedsTable.slug,
      set: {
        title: FEED.title,
        tagline: FEED.tagline,
        coverEmoji: FEED.coverEmoji,
        timezone: FEED.timezone,
        visibility: "public",
        updatedAt: new Date(),
      },
    });
  await db
    .update(prayerFeedsTable)
    .set({ state: "live" })
    .where(and(eq(prayerFeedsTable.slug, FEED.slug), eq(prayerFeedsTable.state, "draft")));
  await db
    .update(prayerFeedsTable)
    .set({ creatorUserId: null })
    .where(eq(prayerFeedsTable.slug, FEED.slug));

  const [feed] = await db
    .select({ id: prayerFeedsTable.id })
    .from(prayerFeedsTable)
    .where(eq(prayerFeedsTable.slug, FEED.slug));
  if (!feed) return 0;

  // Date-programmed feed: one intention per calendar day in prayer_feed_entries.
  // lib/feedDailyPromotion mirrors each day's entry into the feed's live "today"
  // intercession moment, exactly like the Diocese of NY feed.
  const now = new Date();
  const rows = ENTRIES.map((e) => ({
    feedId: feed.id,
    entryDate: e.d,
    slot: 1,
    title: e.t,
    body: BODY,
    source: "custom",
    state: "published",
    publishedAt: now,
  }));

  // Upsert in chunks — keep each day's title fresh (so a future correction
  // propagates) while leaving pray counts and ids intact.
  const CHUNK = 100;
  for (let i = 0; i < rows.length; i += CHUNK) {
    await db
      .insert(prayerFeedEntriesTable)
      .values(rows.slice(i, i + CHUNK))
      .onConflictDoUpdate({
        target: [
          prayerFeedEntriesTable.feedId,
          prayerFeedEntriesTable.entryDate,
          prayerFeedEntriesTable.slot,
        ],
        set: {
          title: sql`excluded.title`,
          body: sql`excluded.body`,
          state: sql`excluded.state`,
          publishedAt: sql`excluded.published_at`,
          updatedAt: now,
        },
      });
  }

  return rows.length;
}
